### ISSUE TITLE
CSVデータに対応していない

### ISSUE THREAD

**Issue by tk-suzuki** [codeforsapporo/covid19#1]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 現在JSONを読み取る形。利用者のリテラシーを鑑みて、CSVが望ましい

## 期待する見せ方・挙動 / Expected behavior
* CSVからJSONを生成するスクリプト（サーバサイドかクライアントサイドかはまだ決めてない）を設置、それ経由でCSVファイルを叩く

**Comment by tk-suzuki** [comment]
[https://github.com/codeforsapporo/covid19/blob/development/tool/convert.php](https://github.com/codeforsapporo/covid19/blob/development/tool/convert.php)にXLSXからの変換機能はある？

**Comment by Yfuruchin** [comment]
本家に問い合わせたところでは公開権限の関係上XLSX変換機能は使っていないらしい
https://github.com/tokyo-metropolitan-gov/covid19/issues/446

**Comment by daisuke-fukuda** [comment]
## csvのパースについて

vue.jsを使っていますが、ロジックは普通にjavascriptなので（今回はtypeScriptですが、、）、javascriptのライブラリが使えます。

使った事ないですが、例えば↓ですね。
https://www.papaparse.com/

都度parserを呼ぶ作戦と、適当なスクリプトを作ってcsv->jsonに変換してコミットしておく作戦の2つが考えられそうです。

**Comment by daisuke-fukuda** [comment]
CSVはパーサーが既にあるので、このissueはcloseで良い？？

**Comment by NEKOYASAN** [comment]
csv->jsonのパーサーがあるためcloseします
