### ISSUE TITLE
陽性患者の属性のデータ作成

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#10]
# 道が公開しているデータをパースして、グラフ化出来る形に変換する。
関連: #1 #2

| | |
|--|--|
|対応するデータファイル| /data/patients.csv |
|取得元| http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijoukyou.htm |
|変換処理| 実装済み https://github.com/Kanahiro/covid19hokkaido_scraping |

## スクリーンショット / Screenshot
<img width="409" alt="スクリーンショット 2020-03-06 11 16 02" src="https://user-images.githubusercontent.com/3221619/76043785-e1bc3900-5f9b-11ea-8f53-f156b34f32fe.png">

## 期待する見せ方・挙動 / Expected behavior
基本は都の見せ方に準拠だが、必要なデータが無い場合は別途検討。
ex) 日毎のデータがないのでグラフではなくテキストにする等

**Comment by watanavex** [comment]
> データに関しては暫定版ですけど上がってます
ただしwebページがどんな変態フォーマット進化をするか未知数ではありますが

☝️ @Yfuruchin さん談 (slackにて)

具体的な残タスクなどあれば追記お願いします！

**Comment by tk-suzuki** [comment]
陽性患者の属性は[発生状況テーブル](http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijoukyou.htm)のパースで取得可能（現時点で @Yfuruchin がコミット済）。

退院日データが北海道版には存在しないが、完治した（と判断されている）かどうかは「健康観察終了」の文言をフラグにすれば取れそう。

**Comment by koukita** [comment]
基本は北海道のホームページから自動収集ですね。
内容のチェックを私がします。
patients.csvも私の方で作成しておきます。
ただ、感染者の居住地に、振興局、市町村、死亡の情報などが入っていて、情報が多いので、将来的にはカラムを分けたほうがいいかとも思います。

**Comment by Yfuruchin** [comment]
基本スクレイピング＋目視チェックなのでclose
