### ISSUE TITLE
当サイトについての外部リンクが別タブで開かない

### ISSUE THREAD

**Issue by aricone** [codeforsapporo/covid19#101]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 当サイトについてのリンク先が別タブ(target:_blank)で開かない

※該当リンク
*東京都公式 新型コロナウイルス対策サイト
*Code for Sapporo Slack ワークグループ
*JUST道ITFacebookページ
※fbのリンクは合わせてリンク範囲をFacebookページまで広げるのが良いと思いました

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/13171920/76162752-e2172880-6183-11ea-8b02-5e945471167a.png)

## 期待する見せ方・挙動 / Expected behavior
* target:_blankの設定がされ、別タブで開くこと

**Comment by NEKOYASAN** [comment]
対応終わりましたPR出します

**Comment by daisuke-fukuda** [comment]
速い！！

**Comment by ymgt-design** [comment]
すません、ブランクで開く場合rel="noopener"無いとセキュリティ的にまずいのでこちらで対応しますね!

**Comment by NEKOYASAN** [comment]
ごめんなさい！完全に忘れてました！！！

**Comment by NEKOYASAN** [comment]
components/DataView.vueの30行目の
`      {{ date }} 更新 <v-spacer /> <a class="DataView-Link" target="_blank" :href="sourceLink">出典: {{ sourceFrom }} <v-icon size="15">mdi-open-in-new</v-icon></a>
`
もrel="noopener"ないのでそちらも変更お願いしてもいいでしょうか？
