### ISSUE TITLE
ナビゲーションにマウスを乗せたとき、アイコンに下線がつく

### ISSUE THREAD

**Issue by aricone** [codeforsapporo/covid19#106]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 共通サイドナビゲーションで、mouse over時にアイコンに下線が表示される

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/13171920/76163325-6ff51280-6188-11ea-84b0-4929a6451699.png)

## 期待する見せ方・挙動 / Expected behavior
* マウスを乗せたときにアイコンに下線がつかないこと

**Comment by ymgt-design** [comment]
僕の環境(mac+safari,Chrome,edgeでは現象出ず）win特有かな？

**Comment by NEKOYASAN** [comment]
ロード直後は発生なしで、ページ移動してからだと発生しますね

**Comment by aricone** [comment]
つくものと付かないものあるなとは思ってたのですが・・・

**Comment by daisuke-fukuda** [comment]
ほんとだ、、本家でも再現しますね

**Comment by aricone** [comment]
本家で起きないとおもったらページ移動してなかったパターンかもしれません(´・ω・｀)

**Comment by Yfuruchin** [comment]
こんな
![Mar-08-2020 22-09-20](https://user-images.githubusercontent.com/4961152/76163450-8780cb00-6189-11ea-925e-e6fc77c12677.gif)

**Comment by NEKOYASAN** [comment]
Parent-Headingでcssがscopedされてないせいでなってるっぽいので修正してPR上げます

**Comment by Yfuruchin** [comment]
ですね、本家にもおないしやす
