### ISSUE TITLE
parentページのリストをpからui>liに変更する

### ISSUE THREAD

**Issue by aricone** [codeforsapporo/covid19#107]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 「臨時休校中の新型コロナウイルス感染症対応についてのお願い」ページの文章がリスト形式が正しいものであるが、ulタグを使われてない

## 期待する見せ方・挙動 / Expected behavior
* 適切なHTMLタグに変更されること

**Comment by Yfuruchin** [comment]
指摘場所の補足説明おねがいします🙇、どこのURLの箇所なのかしら

**Comment by NEKOYASAN** [comment]
https://admiring-davinci-e0cd70.netlify.com/parent
ここですね。〇ってかかれてるのをul > liに変更すべきですね

**Comment by aricone** [comment]
@Nekoya3 さんのご指摘どおりです。補足ありがとうございます。
