### ISSUE TITLE
iphoneでみるとタイトルに北海道が抜ける

### ISSUE THREAD

**Issue by aricone** [codeforsapporo/covid19#110]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* スマートフォンで閲覧したときにタイトルから北海道が抜けている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/13171920/76163671-881a6100-618b-11ea-8750-cff8419b8492.png)

## 期待する見せ方・挙動 / Expected behavior
* 北海道新型コロナウイルスまとめサイト とタイトルに表示されること

**Comment by ymgt-design** [comment]
確認しますー

**Comment by ymgt-design** [comment]
ここなやみどころですね。
> 新型コロナウイルスまとめサイト

が長いのでモバイル時に

> br

入れる設定になってますがこれのせいで上が切れちゃうんですね。
どうしましょ。

**Comment by aricone** [comment]
https://qiita.com/DaichiYamaguchi/items/02fe957c7dc201c2be3d
この辺で解決できるかなと。
Firefoxはスマホブラウザではないと認識すると、wbrでもよいかもです

**Comment by NEKOYASAN** [comment]
ちょっと試してみますね

**Comment by ymgt-design** [comment]
<img width="782" alt="スクリーンショット 2020-03-08 22 53 34" src="https://user-images.githubusercontent.com/61897769/76164135-b8fc9500-618f-11ea-9600-d6c722062e5a.png">
すでに対応されてそうなってるっぽいのですよねwあとは改行させないかかなあと。
モバイル時にフォントサイズ小さくするか画像置き換えとかしますか？

**Comment by daisuke-fukuda** [comment]
デザイン的に文字列の長さが悩ましいですね、、、

<img width="335" alt="スクリーンショット 2020-03-08 22 54 59" src="https://user-images.githubusercontent.com/32258949/76164153-e5b0ac80-618f-11ea-8d59-3b0cb89fee56.png">
<img width="333" alt="スクリーンショット 2020-03-08 22 54 00" src="https://user-images.githubusercontent.com/32258949/76164154-e77a7000-618f-11ea-8e92-8a6129a3f533.png">

**Comment by NEKOYASAN** [comment]
文字サイズ下げます？
もしくはまとめサイトの前で改行させるくらいですかね

**Comment by ymgt-design** [comment]
それか、もう横にHOKKAIDOって書いてるからいいかなっておもったりも。やっぱり日本語で表示あったほうがいいですかね。

**Comment by aricone** [comment]
![image](https://user-images.githubusercontent.com/13171920/76164175-142e8780-6190-11ea-9a4b-7d38b6d2b724.png)
iphoneSEのサイズだとこれくらいですかね・・・
実機で見てないのですが

**Comment by NEKOYASAN** [comment]
> それか、もう横にHOKKAIDOって書いてるからいいかなっておもったりも。やっぱり日本語で表示あったほうがいいですかね。

これは確かにそうかもしれないですね

**Comment by ymgt-design** [comment]
協議の結果v1に持ち越し

**Comment by watanavex** [comment]
本家にもこんな
https://github.com/tokyo-metropolitan-gov/covid19/pull/787

**Comment by tk-suzuki** [comment]
見た目ちょっとダサく感じるかもですが、これじゃダメですかね？（一定以下の横幅になったらpaddingなくして3行押し込む
![covid19-heading](https://user-images.githubusercontent.com/48782652/76174306-ed04a400-61e9-11ea-9c4f-977bf182387a.PNG)
）

**Comment by tk-suzuki** [comment]
微調整するとこんな感じ
![covid19-heading-v1](https://user-images.githubusercontent.com/48782652/76174419-79af6200-61ea-11ea-877a-dd435bdd61ac.PNG)

**Comment by NEKOYASAN** [comment]
時間たちましたが、北海道をいれなくてもロゴに入っているのでOKかなと思います
