### ISSUE TITLE
FBアイコンのJUST道ITへのリンクが管理者向けのURLになっている

### ISSUE THREAD

**Issue by takehirock** [codeforsapporo/covid19#112]
- [x] バグ / Bug

## 起こっている問題 / Occurred problem
FBのJUST道ITへのリンクが以下になっている
* https://www.facebook.com/JUST%E9%81%93IT-106299527656125/?modal=admin_todo_tour
## 期待する見せ方・挙動 / Expected behavior
* https://www.facebook.com/JUST%E9%81%93IT-106299527656125/

**Comment by NEKOYASAN** [comment]
ごめんなさい！どこのページで起きているかお教えください！！！

**Comment by takehirock** [comment]
![スクリーンショット 2020-03-08 22 41 18](https://user-images.githubusercontent.com/2949452/76163948-01b34e80-618e-11ea-857f-a2a38b003b32.png)
ここのFBアイコンのリンクです！

そもそも俺の共有が間違ってたという。。。。

**Comment by aricone** [comment]
fbのURLを取るのはFBページの管理者でなければと思うのですが、
まだURL発行がされてていない認識ですがいかがでしょうか。

**Comment by takehirock** [comment]
っとわいが管理者や！ごめんなさいURLが発行されてないとはどういう意味でしょうか？
どっちにしてもプライオリティは低でいいはず

**Comment by Yfuruchin** [comment]
リンク作成しました
https://www.facebook.com/Justdouit19/

**Comment by NEKOYASAN** [comment]
ありがとうございます！即修正します

**Comment by takehirock** [comment]
なるほど、任意でURLきるものなんですね。失礼しやした。

**Comment by aricone** [comment]
FBのURLは
*ナビゲーション
*当サイトについて /about
にあります！
どちらも変更をお願いいたします！

**Comment by Yfuruchin** [comment]
`Justdouit`はすでに取られてた、誰だよｗ

**Comment by NEKOYASAN** [comment]
justdouitがtwitterもとられてたんですよねｗ
