### ISSUE TITLE
患者数の前に＋がほしい

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#116]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 陽性患者数3人と表示され、現在３人しか患者がいないかのような誤解を与えてしまう

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4961152/76164168-037e1180-6190-11ea-9935-6e5c35084fed.png)

## 期待する見せ方・挙動 / Expected behavior
* 本家のように陽性患者数の前に「＋」を入れてはどうか
![image](https://user-images.githubusercontent.com/4961152/76164150-e0ebf880-618f-11ea-8b87-123c7b40a37c.png)

**Comment by watanavex** [comment]
あれ、今見ると本家から`+` 表記消えてる...

**Comment by Yfuruchin** [comment]
あああ、上の＋スクショはfork版だったのでいまみたら確かに表示されてないですね。ちょっときいてみます

**Comment by watanavex** [comment]
私はgitの履歴を辿ってみます

**Comment by ymgt-design** [comment]
下に（）書きで前日比っていう表現に変わってるっぽいですね

**Comment by Yfuruchin** [comment]
ありました、デフォを累計にしてるみたいです
https://github.com/tokyo-metropolitan-gov/covid19/issues/623

**Comment by watanavex** [comment]
あれ？でも、東京都まだデフォルトにはなってなさげ？ ()
ちょっとデフォルト変えれないか調べてみます

**Comment by Yfuruchin** [comment]
あああ失礼、たぶん東京の”開発版”ではデフォを累計にしているのではないかと

**Comment by watanavex** [comment]
東京の開発版もまだ未対応っぽ。
https://github.com/codeforsapporo/covid19/blob/726199d7161eca37ca7adbc6bd0901c973c2ddca/components/TimeBarChart.vue#L60
ここを `dataKind: 'cumulative'` っとすれば良いんだけど
vueの事はヨクワカラナイなぁ...
