### ISSUE TITLE
production の robots.txt が dev-pages と同じ disallow のものになっている

### ISSUE THREAD

**Issue by nobuh** [codeforsapporo/covid19#119]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem

producdtion の robots.txt が dev 用の disallow のものに

## スクリーンショット / Screenshot

https://stopcovid19.hokkaido.dev/robots.txt

```
User-agent: *
Disallow *
```

## 期待する見せ方・挙動 / Expected behavior

production 用の robots.txt としては

```
User-Agent: *
Allow: /
```

などがよいと思います。

とりあえず緊急的に本番サーバーでは .gitignore で robots.txt を指定して
ローカルに上記 robots.txt を置きました

その他解決策もご検討いただければと

## 起こっている問題の再現手段 / Steps to reproduce
1. xxx
2. xxx
3. xxx

**Comment by daisuke-fukuda** [comment]
robots.txtはGitHubActionで設定されています。（development->deb-pages、mater->productionブランチを作るとき）

なので、そこに細工すればproduction用のrobots.txtを設定できます。

が、設定すると公開されちゃうので、

## 本リリースするまで

現状のマニュアル運用

## リリース後
↑の設定いれる

でいかがでしょうか？
