### ISSUE TITLE
帰国者・接触者電話相談センター相談件数のデータ作成

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#12]
# 道が公開しているデータをパースして、グラフ化出来る形に変換する。
関連: #1 #2

| | |
|--|--|
|対応するデータファイル| /data/querents.csv |
|取得元| なさそう |
|変換処理| 未実装 |

## スクリーンショット / Screenshot
<img width="412" alt="スクリーンショット 2020-03-06 11 19 15" src="https://user-images.githubusercontent.com/3221619/76043991-60b17180-5f9c-11ea-9a71-a5a05342fc5c.png">

## 期待する見せ方・挙動 / Expected behavior
基本は都の見せ方に準拠だが、必要なデータが無い場合は別途検討。
ex) 日毎のデータがないのでグラフではなくテキストにする等

**Comment by watanavex** [comment]
> データに関しては暫定版ですけど上がってます
ただしwebページがどんな変態フォーマット進化をするか未知数ではありますが

☝️ @Yfuruchin さん談 (slackにて)

具体的な残タスクなどあれば追記お願いします！

**Comment by tk-suzuki** [comment]
センター相談件数は（2020-03-06現在では）道では公開していないので、提供をお願いする、あるいは機能をスポイルする必要があるかもしれない。

**Comment by Yfuruchin** [comment]
おそらく公表はされない（する余裕がなさそう）なので、相談件数は非表示でもよいかもしれない

**Comment by watanavex** [comment]
ひとまず、札幌市の情報を表示する案が浮上
#31 #40 
https://github.com/codeforsapporo/covid19/tree/development/data/sapporo

**Comment by Yfuruchin** [comment]
まずは札幌市の相談データが高頻度で更新されることになりました
https://ckan.pf-sapporo.jp/dataset/covid_19_soudan

**Comment by NEKOYASAN** [comment]
#43 にてCKANより相談データを持ってくることで一度確定、自動化済み。道のデータがもし来たらその時に差し替える（かも？）
ということでいったん落ち着いているため #11 とともにclose、道のデータを持ってくるという話になったらreopen
