### ISSUE TITLE
V0見ていて気になったもの

### ISSUE THREAD

**Issue by NEKOYASAN** [codeforsapporo/covid19#125]
- [x] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

**Comment by kken78** [comment]
![8F12F9E5-24E7-4B60-8C43-B742DBF39723](https://user-images.githubusercontent.com/35302518/76174029-f0972b80-61e7-11ea-94fe-cb0526f51664.jpeg)
iPhoneXで見たときのものです。PC、iPad Pro12.9では再現しないです。
些細なとこですので、「すこーし気になった」です。

**Comment by daisuke-fukuda** [comment]
日時更新のデータの更新日付が 「2020/03/09 00:00:00 更新」 となる。
（3/9未明のデータなので、正確ではなさそう）

**Comment by daisuke-fukuda** [comment]
新型コロナウイルス
↓
新型コロナウイルス感染症（COVID-19） 

が正式名称？

**Comment by daisuke-fukuda** [comment]
推奨環境にスマホ環境もいれたい（本家は対応してたはず

**Comment by tk-suzuki** [comment]
> 推奨環境にスマホ環境もいれたい（本家は対応してたはず

iPhoneでチェックしてる人いますか？Android / Chrome / Firefox / Edge / Operaはこちら確認しています。

**Comment by zakijun** [comment]
> iPhoneでチェックしてる人いますか？

iPhone7、iPhone11pro、Chrome、Safariは特に気になる点なしでした。主にレイアウト崩れ、リンク先の遷移など、基本動作の確認。

**Comment by NEKOYASAN** [comment]
いったんcloseします。後ほどここからissue立てるかもです
