### ISSUE TITLE
サイトにサクラーインターネットのロゴ表示

### ISSUE THREAD

**Issue by takehirock** [codeforsapporo/covid19#127]
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
*インフラリソースにご協力頂いたサクラさんの名前（ロゴ）をサイト内に表示

## 期待する見せ方・挙動 / Expected behavior
* FBのアイコンの下辺りにロゴ乗っける
https://www.sakura.ad.jp/brand-assets/

**Comment by Yfuruchin** [comment]
@tk-suzuki が対応
