### ISSUE TITLE
陽性患者数 のデータ収集

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#13]
<img width="331" alt="スクリーンショット 2020-03-06 11 10 39" src="https://user-images.githubusercontent.com/3221619/76044134-c1d94500-5f9c-11ea-9e21-a50672b53898.png">

道が公開しているデータを定期的にスクレイピング、反映させる。

関連: #9

**Comment by watanavex** [comment]
データ収集については #2 で議論が進んでる

**Comment by koukita** [comment]
ホームページから自動収集。
今後は知事のツイートから収集できれば。 #49 で議論

現状必要はないが、patients_summary.csvは喜多が更新。

**Comment by watanavex** [comment]
issue整理のためcloseします。 以降は #9 にて。
