### ISSUE TITLE
「正しい手の洗い方」リンク文言に「PDF」をつけたほうが良い

### ISSUE THREAD

**Issue by irasally** [codeforsapporo/covid19#133]
- [ ] バグ / Bug
- [ ✅ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 「お子様をお持ちの皆様へ」内のリンク「正しい手の洗い方」はリンク先がPDFなので、リンク文言の末尾に「(PDF)」をつけたほうが優しい

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-09 12 07 09（2）](https://user-images.githubusercontent.com/293996/76179565-a8373800-61fe-11ea-90ff-ab8c8398f5a8.png)

## 期待する見せ方・挙動 / Expected behavior
* 「正しい手の洗い方(PDF)」にする

## 起こっている問題の再現手段 / Steps to reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
*

**Comment by irasally** [comment]
他にPDF直リンクのところありますか？
一応探したけれど見つからず

**Comment by daisuke-fukuda** [comment]
本文ではないですが、ヘッダーの部分がpdf直リンクです！

<img width="802" alt="スクリーンショット 2020-03-09 12 13 02" src="https://user-images.githubusercontent.com/32258949/76179765-5b079600-61ff-11ea-8833-42a0d14a778a.png">

**Comment by irasally** [comment]
いま、そのリンク、componentに直書きなんですね。
ひとまず、現状のリンクの文言は直しておきます。
