### ISSUE TITLE
画面表示が画面の大きなAndroidスマートフォンで崩れる

### ISSUE THREAD

**Issue by tk-suzuki** [codeforsapporo/covid19#136]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 一部Android環境(画面が大きいスマートフォン)でPC版が表示されるために崩れる

## スクリーンショット / Screenshot

![Screenshot_20200309-140528](https://user-images.githubusercontent.com/48782652/76184522-9ad67980-620f-11ea-9d94-9a1b14ce7b5c.png)

## 期待する見せ方・挙動 / Expected behavior
* モバイル版ページとして表示したい

## 動作環境・ブラウザ / Environment
* Android 9
* SO-04K
* 内蔵ブラウザ(Chrome)

**Comment by NEKOYASAN** [comment]
breakpointずらしますか…？

**Comment by tk-suzuki** [comment]
そうですねぇ…
個別対応はやってられないですし、それが簡単ではないかと思います。

**Comment by tk-suzuki** [comment]
Androidスマートフォンで大きめの機種のCSS Pixelは480x853だそうです。
また、現時点のCSSのまま表示すると、451px ～569pxの間のモバイル機器において操作が困難なレベルの崩れが生じるようです。
570px～580pxを境に区切ると概ねのモバイル機器に対応できそうですね（600pxくらいになると今度は小型のタブレットに引っかかるので）

**Comment by NEKOYASAN** [comment]
であればBreakPoint 580pxに変更して様子見てみますか？

**Comment by tk-suzuki** [comment]
そうですね。
今出先で作業できないので、もしよろしければお願いします（18時以降でしたら私が修正します）

**Comment by NEKOYASAN** [comment]
いま修正かけちゃいますね
