### ISSUE TITLE
退院数（陰性確認数）のグラフを作成する

### ISSUE THREAD

**Issue by koukita** [codeforsapporo/covid19#144]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 退院数のグラフを作成する
* discharges_summary.csvを更新する

**Comment by koukita** [comment]
陰性確認数のデータをdataブランチで更新しました。
discharges_summary.csvは、東京都と同じカラムにしました

**Comment by koukita** [comment]
「陰性確認数」というのがわかりづらいとの意見がありました。前は退院数だったのですが、多分自宅待機の人もいるから変えたのですかね（想像）
説明分を追加したほうがいいかと。文字は小さくてもいいと思います。
「陰性確認数とは、陽性だった方が再検査により陰性となった人数です」

**Comment by koukita** [comment]
出典は知事の3月9日のツイートです
以下の、知事のツイート
【補足】
「陰性確認済累計」とは、陽性の患者が軽快してから48時間後の1回目のPCR検査で陰性が確認され、それから12時間後の2回目のPCR検査でも陰性が確認された方の累計となります。
退院後も適切にフォローして参ります。

**Comment by NEKOYASAN** [comment]
デザインの変更が必要なため少し時間がかかる内容なので時間かかってしまうかと思います。なるべく早く記載します

**Comment by koukita** [comment]
グラフの上か下に若干空白があるので、そこに小さく書いてもいいかも

**Comment by koukita** [comment]
タイトルは「治療終了」
補足説明に「治療終了とは道発表の「陰性確認数」と同じものです。陰性確認数とは～」
としましょうか？
ちょっと補足説明が長くなりますが・・・

**Comment by koukita** [comment]
出典も「3/9　鈴木知事のツイートを引用」としましょう。
「治療終了」は知事は言ってないので。
細かくてすみません・・・

**Comment by watanavex** [comment]
細い話をすると道庁とか知事は `陰性確認済累計` としていて、
`陰性確認数` とちょっと言い回しが違う...

**Comment by takainou** [comment]
はじめまして。

「治療終了者数」グラフにおける退院確認について確認させてください。必要であれば新たなIssueを起票します。

「治療終了者数」グラフには、以下補足が記載されています。

> 補足:
> 治療終了者数とは道発表の「陰性確認済累計」と同じものです。「陰性確認済累計」とは、陽性の患者が軽快してから48時間後の1回目のPCR検査で陰性が確認され、それから12時間後の2回目のPCR検査でも陰性が確認された方の累計のことです。（3/9 鈴木知事のツイートから引用）

その後、４月２日に、厚生労働省より、退院基準・解除基準が変更になった旨、通知されています。

https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000121431_00088.html

2020年４月２日掲載
感染症の予防及び感染症の患者に対する医療に関する法律における新型コロナウイルス感染症患者の退院及び就業制限の取扱いについて
https://www.mhlw.go.jp/content/000618523.pdf
（参考：退院基準について）
https://www.mhlw.go.jp/content/000618524.pdf

**旧：軽快から48時間後1回目、12時間後2回目
新：軽快から24時間後1回目、24時間後2回目**

新型コロナウイルス感染症患者が自宅療養を行う場合の患者へのフォローアップ及び自宅療養時の管理対策について
https://www.mhlw.go.jp/content/000618528.pdf
（参考：軽症者等の療養に関する対象者等の基本的考え方について）
https://www.mhlw.go.jp/content/000618529.pdf

> 宿泊療養・自宅療養の解除の基準
> 原則として、退院基準（PCR検査で2回連続陰転化を確認）と同様の基準で解除する。ただし、宿泊療養・自宅療養中の軽症者等にPCR検査を実施する体制を取ることにより、重症者に対する医療提供に支障が生じる可能性がある場合、**宿泊療養・自宅療養開始から14日間経過した場合に解除する。**


道発表の「陰性確認済累計」は、４月２日以降現時点も、3/9時点の基準のままで運用・発表されているという理解でよろしいでしょうか。

お忙しいところ恐れ入りますが、ご回答いただけると幸いです。

![image](https://user-images.githubusercontent.com/63571899/81027385-85509980-8eb8-11ea-89ca-7718bf9ef2de.png)

**Comment by koukita** [comment]
>道発表の「陰性確認済累計」は、４月２日以降現時点も、3/9時点の基準のままで運用・発表されているという理解でよろしいでしょうか。

道に直接問い合わせたほうが良いと思います。
その際は、「コロナ対策まとめサイトに書いてある」ではなく、「3月9日の知事のツイートにこう書いてあるが・・・」と問い合わせたほうがいいでしょう。
このまとめサイトは北海道の公式ではありません。
私達は道がホームページなどで発表した情報しか知ることはできません。

**Comment by takainou** [comment]
返信ありがとうございました。申し訳ありません、ご指摘の通りですね。

アドバイス頂いた通り、道に直接問合せようかと思いましたが、北海道庁もお忙しいと思うので、北海道HP内を調べたところ、同じ記載を見つける事が出来ました。

http://www.pref.hokkaido.lg.jp/ss/tkk/koronataisakukaigi.htm

【第３回】　令和２年４月３日（金）開催
2.資料２　感染症患者の退院及び就業制限について
http://www.pref.hokkaido.lg.jp/file.jsp?id=1287349

3.資料３　軽傷者等の宿泊療養等における対応について
http://www.pref.hokkaido.lg.jp/file.jsp?id=1287353

厚生労働省通知に伴い、４月３日以降、変更になっている事が確認出来ました。

最初からこうすべき所、誤解してしまい、お忙しいところ、お手数をおかけしました。心よりおわび申し上げます。

![image](https://user-images.githubusercontent.com/63571899/81030469-de71fa80-8ec3-11ea-90db-b4484dc5453d.png)
![image](https://user-images.githubusercontent.com/63571899/81030471-e5990880-8ec3-11ea-80d1-4f3991b83e30.png)

**Comment by koukita** [comment]
道の公表があったのであれば、まとめサイトの表記も変えたほうがいいでしょう。
新たなissueを上げていただければと思います

**Comment by takainou** [comment]
了解いたしました。

新たなIssue #436 起票させていただきましたので、確認をお願いします。

お手数をおかけしました。
