### ISSUE TITLE
データをdata.jsonひとつではなくデータごとのjsonファイルで管理すべきでは？

### ISSUE THREAD

**Issue by ysk8hori** [codeforsapporo/covid19#149]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* データをdata.jsonひとつで管理していてはいつか破綻するのではないか

## 理由
* 見通しが悪い
* データ更新のcommitがコンフリクトするリスクがある
* １種類のデータ更新でミスると全て壊れる（現状手でデータ作成して表示確認してからアップロードしているかもしれませんがいつか自動化した際にリスクがある）

## 改善案
以下のようなファイルに分ける。
* contacts.json
* querents.json
* patients.json
* patients_summary.json
* etc...

如何でしょうか？

**Comment by NEKOYASAN** [comment]
やるのであれば早い段階でやるべきですね...
できればそうやるべきだと私も思います...

**Comment by Kanahiro** [comment]
おっしゃられているdata.jsonの管理と、あとcsvファイルの取扱いは議論が必要だと思います。data.jsonで一括で管理しているのは都公式に準拠しているという他に理由はなく、項目ごとにデータを分割しても問題はないです。ただ、自動化のフロー次第と考えます。たとえば動的にjsonを読み込むとなると、ひとつのファイルに集中していた方が良いのかなと思います。

あと、システム上読み込んでいるファイルはdata.jsonだけなのに、dataフォルダ内には多数のデータが混在していて見通しが悪いのであわせてきれいにしても良いと思います。

**Comment by ysk8hori** [comment]
データの編集とコンフリクトしそうで怖いですが、出来ますので、アサインをお願いします。（githubよくわかってないんですが、自分で出来るのかな？）
やるとすれば、データブランチでやるべきですか？

**Comment by Kanahiro** [comment]
現状のdata.jsonの作成はスクリプトで行っていて、手作業ではありません（スクリプトの実行は手作業ですが）。
なので、データを手作業で分割するのではなく生成スクリプトを修正すべきです。

こちらのリポジトリにより生成されます
https://github.com/codeforsapporo/covid19hokkaido_scraping

**Comment by Nekoya3** [comment]
data.jsonを切り分けるとnuxt側もすべて修正が必要になるのでslackのほうにも上げるべきかもしれないですね...

**Comment by tk-suzuki** [comment]
dataフォルダにcsvをごちゃごちゃ置いているのは、当初複数のCSVを作成（→いずれ自治体がその形式でオープンデータ化）し、JSONにコンバート（できれば自動生成）することを想定していたからです。

> 現状のdata.jsonの作成はスクリプトで行っていて、手作業ではありません（スクリプトの実行は手作業ですが）。

という状況になったことにより、CSVもまた「生成される側」になったため、これらが同一ディレクトリに存在することは現在においては意味がありません。
ですから、今後の方針に合わせてcsvを削除しても構いませんし、ディレクトリ構造を見直しても大丈夫だと思います。

**Comment by Kanahiro** [comment]
> data.jsonを切り分けるとnuxt側もすべて修正が必要になるのでslackのほうにも上げるべきかもしれないですね...

ですね、フロント側の修正も小さくはないので、自動化のフローがある程度定まってからでないと手戻りがあると思います。

**Comment by Kanahiro** [comment]
> dataフォルダにcsvをごちゃごちゃ置いているのは、当初複数のCSVを作成（→いずれ自治体がその形式でオープンデータ化）し、JSONにコンバート（できれば自動生成）することを想定していたからです。

については、生成スクリプトがcsvインポートに対応しています。
なので、そういったCSVファイルをスクリプト側のリポジトリに配置しておけば、それらを反映したdata.jsonを出力出来ます（現状の窓口相談データなどは札幌市提供のCSVから生成しています）。

**Comment by NEKOYASAN** [comment]
SSRするのであれば、GraphQLのサーバを立てることもできるのでそちらからデータを引っ張ってくるようにもできるんですが....どうしましょう...?

**Comment by tk-suzuki** [comment]
現状、このレポジトリにおいてdataとimportを分けていないことが分かりづらさの一番の原因かもしれないですね。
サイトに読ませたいデータとJSON生成に使いたいデータを、このリポジトリ上でもそれぞれdata/とimport/に分けるべきかもしれません。

**Comment by Yfuruchin** [comment]
ここまでの議論+1 
データ更新フロウとともにこのフォルダまわりをすっきりさせたいです

**Comment by NEKOYASAN** [comment]
universal modeで開発自体は行ってるのでインフラだけ整えることができればSSRも可能かなと思いますが...どうなんでしょう？
現在より少し重くなるかとは思いますが許容範囲かなと思いますのでもしSSRが可能であればそちらにシフトするのも検討していいかもしれません

**Comment by Kanahiro** [comment]
GraphQLを使った事がないので有識者のお話を聞きたいところですね。
私が考えていたのは以下です。
1. 別のリポジトリにある生成スクリプトをActionsでスケジューリングさせて、出力されたデータをフロント側で取得する
2. 別のリポジトリにある生成スクリプトをActionsでスケジューリングさせて、出力されたデータを、本体リポジトリのActionsなどで自動的にプッシュする
3. 生成スクリプトを本体に内臓してActionsによるスケジューリングでdataを自動更新する

1は非同期通信が必要になり、フロントの修正がかなり大きいと思います。
2は現状を発展させた形ですが、3に対し冗長だと思います。
3は一番シンプルだと思いますが、取得先のデータ構造が変更されたりして、正常にデータが取得出来ない場合などに備える必要があります（バリデーションが通らなかったらdata.jsonを出力しない等）。

**Comment by NEKOYASAN** [comment]
1はCORBの回避が必要なためSSRを使うほうが楽かもしれません...(CORBについてそこまで詳しくないので正しい自信があまりありません）
2が現状だと1番良いかなと思うのですがどうでしょうか？

**Comment by koukita** [comment]
CSVファイルですが、現状使っていないCSVファイルは削除してもいいと思います。
東京都と北海道で合わない部分もあるので。
道庁との話がどうなるかわかりませんが、一番いいのは、道庁、札幌市にCSVデータを作ってもらって、それをホームページ等から自動で持ってくるのがいいと思います。
チェックも道庁でやってもらう。
もしかしたらCSVじゃなく、Excelとかになる可能性もありますし。そのときにはまた考える必要があるかもしれません。

**Comment by Kanahiro** [comment]
> 1はCORBの回避が必要なためSSRを使うほうが楽かもしれません...(CORBについてそこまで詳しくないので正しい自信があまりありません）
2が現状だと1番良いかなと思うのですがどうでしょうか？

私も2か3かなと思っていたので、2が良さそうですかね。
すぐに修正出来るか、となるとなんとも言えませんが、触ってみますｗ

**Comment by NEKOYASAN** [comment]
とりあえず、患者数データと退院人数のデータのみjsonを個別にしますね。
理由としてはフロントエンドもこれから実装のため

**Comment by NEKOYASAN** [comment]
https://github.com/Nekoya3/covid19hokkaido_scraping
ごめんなさい...患者数データと退院人数のデータのみjsonを個別にするために実装してたらもれなく全部分割できてしまいました......
責任をもってフロントエンドもやらせていただきます...w

**Comment by ysk8hori** [comment]
データとビルド成果物は切り離されていた方が良いと思ってますが、皆さんは如何でしょうか？

なので、私的には1が理想かと。

2や3のメリットは、ページ表示後にリクエストが発生しないことと思います。ただしデメリットはページ表示に結構時間が掛かることと、データ更新の度にビルドとデプロイが必要であることです。1のメリットは、2,3のデメリットの裏返しです。

1が本当にCORBに引っかかるのか検証が必要と思います。1で生成したファイルは何処に出力されるのでしょうか？（今はリポジトリにコミットしているだけ？）
また、同じドメインにスクレイピングのスクリプト？を配置して定期的に動かし、そのドメインの何処かアクセス可能な場所にファイルを置くことが可能なら、JSONPでなくとも取得できます。（多分）

ただ、1だとデータがリポジトリにコミットされなくなる点に注意が必要です。（ローカルでの挙動確認に影響します）

**Comment by NEKOYASAN** [comment]
1が理想であるとは私も思います。急に1に変更するよりも2を一度挟んだ方がいいかと思っているのですがどうでしょう？

**Comment by daisuke-fukuda** [comment]
https://github.com/codeforsapporo/covid19/issues/2#issuecomment-595662925
ここでも一度話題になりましたが、ここ難しいですよねぇ。

現状は2を手動で行っていますよね？

データがこなれるまでは、本番にデータを反映させるにも、目視確認をした方が良いかな〜と思っていたので2が良いかと思っていました。

ゆくゆくは1で、データとサイトを分離。
外部公開もしやすそうだし、jsonのまま公開するなり、GraphQLにするなり。

**Comment by NEKOYASAN** [comment]
https://github.com/Nekoya3/covid19-graphql
GraphQLについてはすでに作成を開始はしていて、getのみですが出来上がってはいます。
なにかしらの方法で外部公開できるといいなとは思いますね...

**Comment by daisuke-fukuda** [comment]
> データ更新の度にビルドとデプロイが必要であることです

ブランチにコミットしたのをhookにするのであれば（今のサイトの仕組みのように）仕組みを作る事自体はそんなに大変では無いと思います。

> 1が本当にCORBに引っかかるのか検証が必要と思います。1で生成したファイルは何処に出力されるのでしょうか？（今はリポジトリにコミットしているだけ？）

現状、サーバはさくらインターネットさんのVPSで実現するのが最速です。静的ファイルとしてデータをおくだけならば、単純にここにファイルを配置してしまえば良いと思います。

GraqhQLとSSRは、すごーく魅力的ではありますが、現状のインフラリソースではちょっと厳しいかな、、、という感じがします。（監視をちゃんといれないと運用がきつい & サーバ負荷が、、、

お金があればPaaS系になげたりできるのですが、、、

**Comment by NEKOYASAN** [comment]
一応GraphQLについては開発を続けはします。（利用するかどうかは別として）

サーバーリソースについてはインフラの方含め一回話す必要ありますね

**Comment by daisuke-fukuda** [comment]
> 1は非同期通信が必要になり、フロントの修正がかなり大きいと思います。

データファイルを外部からとってくるだけであれば、fetchなりaxiosなりで取得すればOKなので、そこまで大変ではないかな〜というイメージです。

うーん、どれも決定打にかけますねぇ、、

**Comment by daisuke-fukuda** [comment]
ホワイトボードがほしい

**Comment by Yfuruchin** [comment]
FYI　最近code for 界隈では
オンラインホワイトボードのmiroがよくつかわれています
https://utilly.jp/2019/03/31/about-miro/

**Comment by Kanahiro** [comment]
正直、1が一番簡単なので、個人的に少し試してみたのですが、現状のindex.vueはすべて同期通信が前提で作られており、非同期の値取得・変更を、いわゆるリアクティブに反映させられる状況になっておらず、その辺でフロント修正の手数が多そうだと考えていました。

（1なら、GitHubのリポジトリのリソースを直接参照すれば良いので、フロントだけの修正で済む…）

**Comment by NEKOYASAN** [comment]
1でもいいっちゃいいんですよねぇ...どうしましょう...
なんともぱっとしない...

**Comment by daisuke-fukuda** [comment]
1のフロント側、軽くやってみましょうか？

**Comment by NEKOYASAN** [comment]
@daisuke-fukuda ブランチ切ってやってみていただいてもいいです？

**Comment by daisuke-fukuda** [comment]
はーい。
data.jsonを外部リソースとしてhttpでとってきて、グラフに反映させるイメージで1時間くらいやってみますね。

**Comment by Kanahiro** [comment]
https://raw.githubusercontent.com/codeforsapporo/covid19hokkaido_scraping/gh-pages/data.json
上記ファイルはActionsで自動更新する事が出来ます（今はオフになっていますが）
これを読み込んで非同期でUIに反映させられれば…

**Comment by daisuke-fukuda** [comment]
お、了解です。↑のdata.jsonを取得してみますね。

**Comment by NEKOYASAN** [comment]
あざっす！
@daisuke-fukuda あとでjson切り分けた状態でのやつも試さないとですね

**Comment by NEKOYASAN** [comment]
@Kanahiro @daisuke-fukuda Jsonいじるついでといっては何ですがjsonのkeyを英語にしませんか？

**Comment by Kanahiro** [comment]
日本語だとまずい系ですかね？都公式に合わせただけなのでこだわりはありませんが、必要ない限りは修正箇所は少なくしておいた方がいいと思います…

**Comment by NEKOYASAN** [comment]
GraphQLとかで扱ううえでできればーっていうぐらいです
無理にする必要まではないと思います

**Comment by daisuke-fukuda** [comment]
雑ですが検証用という事で、、、特に問題なく動いてそうです。
https://github.com/daisuke-fukuda/covid19/tree/feature/data-external-fetch

変更箇所
https://github.com/daisuke-fukuda/covid19/commit/5d0392b718ea457ae498b754253a337474a1c2e5

![a1b1754965cc8531db08313969ba56cb](https://user-images.githubusercontent.com/32258949/76223303-b2891e80-625e-11ea-8a7e-4445f0b9b520.gif)

**Comment by ysk8hori** [comment]
> 日本語だとまずい系ですかね？都公式に合わせただけなのでこだわりはありませんが、必要ない限りは修正箇所は少なくしておいた方がいいと思います…

コレ、どこまで気にすべきでしょうね。
もうほぼほぼマージは無理かと思ってました。
別途議論が必要かもですね。

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/76223804-db111880-625e-11ea-9fad-57d2e8bd7c02.png)

> > 日本語だとまずい系ですかね？都公式に合わせただけなのでこだわりはありませんが、必要ない限りは修正箇所は少なくしておいた方がいいと思います…
> 
> コレ、どこまで気にすべきでしょうね。
> もうほぼほぼマージは無理かと思ってました。
> 別途議論が必要かもですね。

今自分のローカルのファイル群がこれなのですでになんというか...
これならもうkeyも変えてしまいましょうか....

**Comment by NEKOYASAN** [comment]
> 雑ですが検証用という事で、、、特に問題なく動いてそうです。
> https://github.com/daisuke-fukuda/covid19/tree/feature/data-external-fetch
> 
> 変更箇所
> [daisuke-fukuda@5d0392b](https://github.com/daisuke-fukuda/covid19/commit/5d0392b718ea457ae498b754253a337474a1c2e5)
> 
> ![a1b1754965cc8531db08313969ba56cb](https://user-images.githubusercontent.com/32258949/76223303-b2891e80-625e-11ea-8a7e-4445f0b9b520.gif)

良さげっすね...

**Comment by Kanahiro** [comment]
ありがとうございます、サイコーですね！
あとは生成スクリプトの方のバリデーションさえあればより安全に自動化出来そうですね

この実装だと、jsonデータは分割せずdata.json一本の方が良いと思いますがいかがですか？
（keyは別途議論ですね）

**Comment by daisuke-fukuda** [comment]
外部データが複数になっても、実装的にはそんなにかからず修正できます。

↑のコードの、

```
      // 感染者数グラフ
      this.patientsGraph = formatGraph(this.externalData.patients_summary.data)
      // 感染者数
      this.patientsTable = formatTable(this.externalData.patients.data)
      // 相談件数
      this.contactsGraph = formatGraph(this.externalData.contacts.data)
      // 帰国者・接触者電話相談センター相談件数
      this.querentsGraph = formatGraph(this.externalData.querents.data)
```

ここを、fetchして取得に差し替えるだけなので。

面倒だったのは各グラフが非同期処理を前提としてなくて、nullチェックを入れるのが面倒だったのですが、それはもうできていますので。（汚いけど）

外部ファイルの数だけリクエストが走っちゃうのが若干気になりますが、現状のデータ量なら気にするほどでもなさそう。

**Comment by NEKOYASAN** [comment]
あとのことを考えるとjson分けたいですよね...

**Comment by ysk8hori** [comment]
表やグラフごとのコンポーネントに分けた方が良いことあると思うんですが、それをするにはデータは分割した方が良いと思います。（ただし東京都とのマージがもっと難しくなる）

**Comment by daisuke-fukuda** [comment]
https://github.com/codeforsapporo/covid19/issues/23

東京都のマージですが、最近の本家のコミット量を見ると、もう無理なんじゃないか、という気がしています。激しすぎ・・

**Comment by ysk8hori** [comment]
このfetch方法、#43 で試していなかったのですが、ひょっとしてCKANからデータ取れたりしますかね？

**Comment by NEKOYASAN** [comment]
東京都とのマージはすでにできないようなものでもうそこを気にする必要もないのかなーとも思ってます

**Comment by daisuke-fukuda** [comment]
@ysk8hori 
単純にURL差し替えただけだとダメそうでした。

```
Access to fetch at 'https://ckan.pf-sapporo.jp/api/action/datastore_search?resource_id=39977340-d391-4b15-bfae-0946cce68812&limit=5' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

全然しらないのですが、CKANをAPIとして呼ぶ際のお作法次第ですね。

**Comment by Kanahiro** [comment]
1UI・1ソース（JSON、ゆくゆくAPIも）みたいなイメージですかね
確かにJSON分けた方がその辺りの見通しが良いですね！

**Comment by NEKOYASAN** [comment]
@daisuke-fukuda 外部ファイルから取得するのであればVuexでstoreするべきですかね？

**Comment by koukita** [comment]
北海道オープンデータポータルサイトにテスト用のCSVをアップしてみました。
ここからもデータが取れれば、道庁でデータ更新することも可能になってくるので、試してみていただければと思います
[https://www.harp.lg.jp/opendata/dataset/1369.html](https://www.harp.lg.jp/opendata/dataset/1369.html)

**Comment by daisuke-fukuda** [comment]
ちょっと話が広がってきたので、ここを親として、子issueに分割して検討したくなってきました！（私のキャパオーバー

**Comment by NEKOYASAN** [comment]
> 北海道オープンデータポータルサイトにテスト用のCSVをアップしてみました。
> ここからもデータが取れれば、道庁でデータ更新することも可能になってくるので、試してみていただければと思います
> https://www.harp.lg.jp/opendata/dataset/1369.html

これについては一回issueあけます

**Comment by NEKOYASAN** [comment]
上ででた外部からjson取得についてもissueあけますね

**Comment by ysk8hori** [comment]
@daisuke-fukuda 
検証ありがとうございます。

CORS policyに引っかかるなら、やはりクライアントからではダメなんですね。（おそらくhttps://raw.githubusercontent.com はCORSやCORBのポリシーを許容する設定になっているのですね）

**Comment by daisuke-fukuda** [comment]
ckanの件、オプション追加したらCORSは乗り越えられました。まだbodyがとれてないのだけど、もう少し頑張ればいけそう。

```
      fetch('https://ckan.pf-sapporo.jp/api/action/datastore_search?resource_id=39977340-d391-4b15-bfae-0946cce68812&limit=5',
        {
          mode: 'no-cors' // 'cors' by default
        })
```
<img width="801" alt="スクリーンショット 2020-03-09 23 56 52" src="https://user-images.githubusercontent.com/32258949/76226765-ad799e80-6261-11ea-8bbd-c2c62b98f580.png">

**Comment by NEKOYASAN** [comment]
#154 に北海道オープンデータポータルサイトからのissue、外部からjson取得をまとめちゃいます

**Comment by NEKOYASAN** [comment]
というわけで結論としてjson分ける方向で大丈夫でしょうか？

**Comment by daisuke-fukuda** [comment]
> 外部ファイルから取得するのであればVuexでstoreするべきですかね？

設計として議論するべき箇所かと思います。

個人的には、
- 外部ファイルを参照するのがこの画面だけ
- 他画面では共有しない
- 一度読み込んで、更新されることはない

ので、vuexにしなくても良いかな〜と思っています。

**Comment by daisuke-fukuda** [comment]
↑ #154 に転機するので無視してください

**Comment by Kanahiro** [comment]
> というわけで結論としてjson分ける方向で大丈夫でしょうか？

これについてスクリプトのリポジトリでissue立てようと思ったらたぶん権限なかったですｗ
出来る方お願いします

**Comment by ysk8hori** [comment]
> > というわけで結論としてjson分ける方向で大丈夫でしょうか？
> 
> これについてスクリプトのリポジトリでissue立てようと思ったらたぶん権限なかったですｗ
> 出来る方お願いします

議論ではなくて、作業のissueとしてということでしょうか？

**Comment by Kanahiro** [comment]
> 作業のissueとしてということでしょうか？

そのつもりでした。あちらのリポジトリ上ではいきなりPRだ出てきたように見えるかなと。
でもそのPRに経緯書いておけばいいなと今書いてて思いました、スルーしてください…ｗ

**Comment by daisuke-fukuda** [comment]
不要かもですが、スクリプト（scraping）のリポジトリのissueをたてられるようにしました。
（仮のdev環境作る時に権限いただいていたので。これくらいはやっちゃってもいいよね）
