### ISSUE TITLE
新型コロナコールセンター相談件数 のデータ収集

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#15]
<img width="403" alt="スクリーンショット 2020-03-06 11 17 36" src="https://user-images.githubusercontent.com/3221619/76044230-0b299480-5f9d-11ea-8633-305bc9e42e44.png">

道が公開しているデータを定期的にスクレイピング、反映させる。

関連: #11

**Comment by watanavex** [comment]
データ収集については #2 で議論が進んでる

**Comment by koukita** [comment]
現状は、札幌市保健所の件数が札幌市から提供される。  
道庁からのデータはなし。

**Comment by watanavex** [comment]
issue整理のためcloseします。 以降は #11 にて。
