### ISSUE TITLE
グラフがどんどん細くなっていく

### ISSUE THREAD

**Issue by koukita** [codeforsapporo/covid19#153]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 今後日数が増えていくと、棒グラフがどんどん細くなっていく。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/13256642/76220713-4a850900-625b-11ea-8d3a-3a282856f346.png)

## 期待する見せ方・挙動 / Expected behavior
* 横幅の限度を30日くらいにする
1. スクロールできるようにする？
2. 月ごとにタブなどで切り替えられるようにする？

**Comment by koukita** [comment]
機能的にできるかどうかわかりませんが、スクロールするってできるんですかね？
同じ問題、東京都でもありそうだとおもい、Issueみると、こんなのありました
[https://github.com/tokyo-metropolitan-gov/covid19/pull/636](https://github.com/tokyo-metropolitan-gov/covid19/pull/636)
14日で固定する？

**Comment by NEKOYASAN** [comment]
スクロールよりタブとかのがやりやすいかなとは思います。
いろいろ試してはみますね

**Comment by koukita** [comment]
東京もまだ実装はされていないようですね

**Comment by ysk8hori** [comment]
提案ですが、ダッシュボードのグラフなり表なりをクリック等した際に、そのグラフなり表なりを大きく表示するというのはどうでしょ？（ダッシュボードのページから別ページに遷移するイメージ）

ダッシュボードには最新データのみ表示する。

**Comment by koukita** [comment]
いいですね。ダッシュボードでは、直近の20日分くらいを表示して、全体は、クリックで表示するとわかりやすいですね

**Comment by ysk8hori** [comment]
あっ、でも、スマホだときっと意味ないですね・・・。（すみません、基本PCで見てました。）

**Comment by hasumirihito** [comment]
申し越し細かくフィルタ出来るようにしたほうがいいのでは？と思います。
シンプルのほうがいいのでしょうけど、月指定などできたほうがいいのかなと

**Comment by NEKOYASAN** [comment]
v-slider使って対応してみます
