### ISSUE TITLE
外部ファイルからデータを自動取得する

### ISSUE THREAD

**Issue by NEKOYASAN** [codeforsapporo/covid19#154]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 手動でjsonの更新が必要
* #149 から分岐

## 期待する見せ方・挙動 / Expected behavior
* 外部ファイルからデータの自動取得
* 北海道オープンデータポータルサイトからcsvを取得し、jsonにパースする

**Comment by daisuke-fukuda** [comment]
data.jsonを外部ファイル（https://raw.githubusercontent.com/codeforsapporo/covid19hokkaido_scraping/gh-pages/data.json）として読み込む実装テスト。


https://github.com/codeforsapporo/covid19/issues/149#issuecomment-596569515

雑ですが検証用という事で、、、特に問題なく動いてそうです。
https://github.com/daisuke-fukuda/covid19/tree/feature/data-external-fetch

変更箇所
daisuke-fukuda@5d0392b

**Comment by NEKOYASAN** [comment]
ほかのページ移動後indexに戻った場合って通信発生しないんですっけ？

**Comment by ysk8hori** [comment]
https://jp.vuejs.org/v2/guide/instance.html#%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B5%E3%82%A4%E3%82%AF%E3%83%AB%E3%83%80%E3%82%A4%E3%82%A2%E3%82%B0%E3%83%A9%E3%83%A0

mountedか、updatedでデータのリフレッシュをするなりすれば、大丈夫です。

**Comment by daisuke-fukuda** [comment]
外部データが複数になっても、実装的にはそんなにかからず修正できます。

↑のコードの、

      // 感染者数グラフ
      this.patientsGraph = formatGraph(this.externalData.patients_summary.data)
      // 感染者数
      this.patientsTable = formatTable(this.externalData.patients.data)
      // 相談件数
      this.contactsGraph = formatGraph(this.externalData.contacts.data)
      // 帰国者・接触者電話相談センター相談件数
      this.querentsGraph = formatGraph(this.externalData.querents.data)
ここを、fetchして取得に差し替えるだけなので。

面倒だったのは各グラフが非同期処理を前提としてなくて、nullチェックを入れるのが面倒だったのですが、それはもうできていますので。（汚いけど）

外部ファイルの数だけリクエストが走っちゃうのが若干気になりますが、現状のデータ量なら気にするほどでもなさそう。

**Comment by daisuke-fukuda** [comment]
> #43 で試していなかったのですが、ひょっとしてCKANからデータ取れたりしますかね？

ckanの件、オプション追加したらCORSは乗り越えられました。まだbodyがとれてないのだけど、もう少し頑張ればいけそう。

```
      fetch('https://ckan.pf-sapporo.jp/api/action/datastore_search?resource_id=39977340-d391-4b15-bfae-0946cce68812&limit=5',
        {
          mode: 'no-cors' // 'cors' by default
        })
```


<img width="801" alt="スクリーンショット 2020-03-09 23 56 52" src="https://user-images.githubusercontent.com/32258949/76227543-cfbfec00-6262-11ea-8a61-cc1f06cda9f9.png">

**Comment by NEKOYASAN** [comment]
> https://jp.vuejs.org/v2/guide/instance.html#%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B5%E3%82%A4%E3%82%AF%E3%83%AB%E3%83%80%E3%82%A4%E3%82%A2%E3%82%B0%E3%83%A9%E3%83%A0
> 
> mountedか、updatedでデータのリフレッシュをするなりすれば、大丈夫です。

その都度新しいデータ持ってくるべきなのか、最初にアクセスしたときのみにするべきなのか...っていうのがわかんないです...どっちがいいんでしょう？

**Comment by daisuke-fukuda** [comment]
検証すること

- [x] 外部の静的ファイルからデータを取得する（1ファイルのみ）
  - ファイルの置き場所の検討は必要だが、実装としては大丈夫そう
- [x] 外部の静的ファイルからデータを取得する（複数ファイル）
  - 試してないけど多分大丈夫
- [ ] vuex使うべき？
- [ ] ckanから取得

**Comment by ysk8hori** [comment]
それでvuex使ったらどうかっていう話をしていたのですね。

案としては以下でしょうか。
1. 画面表示時にのみデータ取得する
2. mountedまたはupdatedでデータ取得する
3. データリロードボタンを付けボタン押下時にデータ取得する

更新頻度を考えると1で十分な気がしますが、確実に更新できるのは3でしょうかね。

**Comment by NEKOYASAN** [comment]
私も1で十分かと思います。そんなにめちゃめちゃ急ぎのデータを配信しているわけではないですし、長時間アクセスし続けるユーザーも少ないのかなーと思います...

**Comment by daisuke-fukuda** [comment]
1がvuex使うパターンですかね？

**Comment by NEKOYASAN** [comment]
> 1がvuex使うパターンですかね？

ですね（SPAのindex再ロード時にアクセスが発生するのであればですが...多分発生します...vuexないとデータ保持できないはずですよね)

**Comment by ysk8hori** [comment]
そうですね、とするとvuexのようにデータを保持・管理する仕組みがあると良いですね。

ただし、個人的にはvuexはあまり使いたくないです。
（Vuex+TypeScriptのクラスで実装した際に、すごく使いにくかったのと、クラスにgetterとかrefreshメソッド定義すれば事足りるので。）

TypeScriptなら、クラス作って管理する方が、私の経験からはベターと思ってます。

**Comment by daisuke-fukuda** [comment]
2に一票です。

- 今のところ、そんなに画面遷移をするような構成になっていない（ほとんど外部リンク
   - ので、画面遷移して戻ってきた時の通信コストはそこまでシビアに考えなくてよいのでは
- vuexめんどくさい

**Comment by NEKOYASAN** [comment]
@ysk8hori nuxt-linkでやってる場合ってデータ保持できるんでしたっけ

**Comment by NEKOYASAN** [comment]
> 2に一票です。
> 
> * 今のところ、そんなに画面遷移をするような構成になっていない（ほとんど外部リンク
>   
>   * ので、画面遷移して戻ってきた時の通信コストはそこまでシビアに考えなくてよいのでは

この考え方でもいいようには思いますね

**Comment by ysk8hori** [comment]
SPAならクラスのstaticフィールドに保持できるんではないでしょうか？画面遷移したらダメな気がします。（すみませんnuxtは実は未経験・・・）

それと、mountedとupdatedもちゃんと動くか検証した方が良いかもです。

以下に、

> このフックはサーバサイドレンダリングでは呼ばれません。

の記載があります。

https://jp.vuejs.org/v2/api/#mounted

**Comment by NEKOYASAN** [comment]
> 北海道オープンデータポータルサイトにテスト用のCSVをアップしてみました。
> ここからもデータが取れれば、道庁でデータ更新することも可能になってくるので、試してみて> いただければと思います
> https://www.harp.lg.jp/opendata/dataset/1369.html

こちらから自動更新が可能なことを確認しました。

**Comment by ysk8hori** [comment]
> > 北海道オープンデータポータルサイトにテスト用のCSVをアップしてみました。
> > ここからもデータが取れれば、道庁でデータ更新することも可能になってくるので、試してみて> いただければと思います
> > https://www.harp.lg.jp/opendata/dataset/1369.html
> 
> こちらから自動更新が可能なことを確認しました。

ここ、CSVアップロードでもURL変わらないなら、CKANのデータもこっちに上げてもらうと良いかもですね！

**Comment by koukita** [comment]
確認ありがとうございます。
ポータルでは上書きしていればURLは変わりません。
道庁と話をするときも、ポータルにアップしてもらうように話します。
札幌市もポータルを使うことは可能です。

**Comment by koukita** [comment]
ポータルのCSVからの自動更新をするとして、CSVを更新したことはお知らせしたほうがいいでしょうか？
それとも、更新日時の変更などで自動的に変更を取得できますか？
道庁の発表とは少しタイムラグがあると思うので・・・

**Comment by Kanahiro** [comment]
定期的にCSVにアクセスして、変更があればデータが更新される形になると思いますので、通知は不要だと思います。

**Comment by koukita** [comment]
CSVへのアクセスの間隔は自由に設定できますか？通常はどのくらい？５分とか？

**Comment by Kanahiro** [comment]
自由に設定出来ます。通常は、なんとも言えないですが1秒以内にすると怒られますｗ
5分程度で問題ないと思います。masterにも即時反映される訳ではないので。

**Comment by koukita** [comment]
データをアップしてからしばらく時間がかかるのが、少しネックになるかもしれませんね。
役所はすぐに自分で確認したくなりますので・・・
「まだ更新されない」とかF5アタックしそう

**Comment by Kanahiro** [comment]
あーすみません、今後は生成されるjsonファイルを直接読みに行く形になると思うので、やはり更新頻度はCSVファイルへのアクセス頻度に依存します。それでも5分程度の間隔でも良いような気がしますがｗ

**Comment by NEKOYASAN** [comment]
F5アタックされてもキャッシュからになるのでオリジンに対してあまり負荷かからないので問題にはあまりならなさそうですが、5分おきぐらいにcsvからのパースにはなると思います...

**Comment by koukita** [comment]
５分おきなら、データ更新を感知してからどのくらいで一般公開のサイトが更新されるんでしょう。５分後ですか？

**Comment by NEKOYASAN** [comment]
最長で10分というところでしょうか...

**Comment by NEKOYASAN** [comment]
あ、直接jsonにパースしたファイルをクライアントが読む方式になれば5分以下になりますね

**Comment by Kanahiro** [comment]
> 最長で10分というところでしょうか...

キャッシュ時間込みということですかね？

**Comment by NEKOYASAN** [comment]
そうですね、キャッシュに反映されるのを考えると8分~10分...でしょうか...

**Comment by koukita** [comment]
ありがとうございます。了解しました。

**Comment by Kanahiro** [comment]
データ取得・json生成のスクリプトを、外部ファイルの読み取りにあわせて修正しようと思います。
ので、データを確認しておきたいです。

|  data  |  source  | url  |
| ---- | ---- | ---- |
|  patients  | ODP |  https://www.harp.lg.jp/opendata/api/package_show?id=752c577e-0cbe-46e0-bebd-eb47b71b38bf  |
|  patients_summary  | ODP |  https://www.harp.lg.jp/opendata/api/package_show?id=752c577e-0cbe-46e0-bebd-eb47b71b38bf  |
|  contacts  | CKAN |  https://ckan.pf-sapporo.jp/dataset/f6338cc2-dd6b-43b6-98a3-cd80b05b6a36/resource/e9e6f062-cafd-4aea-992f-039e2e26f4ac/download/contacts.csv  |
|  querents  | CKAN |  https://ckan.pf-sapporo.jp/dataset/f6338cc2-dd6b-43b6-98a3-cd80b05b6a36/resource/a89ba566-93d1-416a-a269-e0ba48a06636/download/querents.csv  |
|  current_patients  | ODP |  不明  |
|  discharges_summary  | ODP |  不明  |

contactsとquerentsはひとまずこれで良さそうです
patientsとpatients_summaryは、URLがテストページなので本ページに変更する必要がありそうです
current_patientsとdischarges_summaryもODPでしょうか？
また、その他のURLに誤り・更新などありましたら教えてください。

> current_patientsとdischarges_summaryもODPの予定です。

**Comment by NEKOYASAN** [comment]
current_patientsとdischarges_summaryもODPの予定です。

**Comment by NEKOYASAN** [comment]
あとできればjsonの取得は明日は手動でdataフォルダに追加して今の方式のまま配信したいです

**Comment by Kanahiro** [comment]
そうですね、あまり急ぐつもりもないです。
最低限ODPのURLなどが確定してからですね。

**Comment by koukita** [comment]
道庁のcsvデータはこちらにあります
https://www.harp.lg.jp/opendata/dataset/1369.html

**Comment by Kanahiro** [comment]
ありがとうございます、これ今テストデータって書いてありますけど、本番になってもURLは変わらないんですよね？

**Comment by koukita** [comment]
変えないつもりですが、変わったら結構大変？
あと、ダウンロード間隔、1時間とかでもいいかも。
ダウンロード数が、多くなりすぎると、人気ランキングに出てきちゃうので

**Comment by Kanahiro** [comment]
以後も随時URLが変わるようだと大変ですが、取得スクリプトの実装までにいくら変わっても問題ありません。

ダウンロード間隔は要検討ですが、実際、1時間に一度程度でも差し支えないですね。

**Comment by koukita** [comment]
URLは、基本変わりませんが、今後道庁の本当の担当が更新しようとするとそのときに変わる可能性は高いあります

**Comment by koukita** [comment]
現在は私が更新してますので文字コードはutf-8にしてますが、他の職員が編集しようとしたらEXCELで編集するので、shift-JISになる可能性があるのですが、大丈夫ですか？
今のうちにshift-JISでテストしておいた方がいいでしょうか？

**Comment by Kanahiro** [comment]
OfficeだとShift-JISのcsvしか出力出来ませんもんね！
複数エンコード対応はスクリプト側で対応可能です。自動化前にはテストは必要だと思います、今はまだ大丈夫です。

**Comment by Kanahiro** [comment]
https://github.com/codeforsapporo/covid19hokkaido_scraping
ODP、CKANからのデータ取得に対応しました。
また処理はGitHub Actionsで自動化されています（15分間隔で実行）。

jsonのバリデーションの必要性などあると思いますが、今後フロント側で自動更新されたjsonに非同期通信する事で、完全自動でデータが更新される事になります。

以下はpatients.jsonのURLです、他のデータも同じくあります。
https://raw.githubusercontent.com/codeforsapporo/covid19hokkaido_scraping/gh-pages/patients.json

**Comment by Nar-Ogasawara** [comment]
現状確認なのですが、自動更新は実装前でしょうか？
実は本日のコールセンター受付数データ(contacts.csvとquerents.csv)の更新を日中出来なかったので、夜になってから作業しました。
自動更新実装済みであればこのまま待ちます。実装前であれば昨日分までの受付件数データを更新済みなので、反映させていただけると助かります。
あと、更新時間は15分になりますか？
DATA-SMART CITY SAPPOROは10分更新のAPIを実装しているので負荷は問題ないと思いますが、当面更新は平日1日1回になるので、@koukitaさんが仰るとおり1時間更新で十分かと思います。

**Comment by NEKOYASAN** [comment]
csv to jsonについては現在自動ですが jsonをwebへ渡す部分がまだ未実装なためすぐに更新させていただきます！

**Comment by Kanahiro** [comment]
データの更新ありがとうございます。
自動更新はまだ未実装です（データの生成自体は自動化されていますが、内容チェックの意味を含めて手動で更新しています）。

**Comment by Nar-Ogasawara** [comment]
@Nekoya3 @Kanahiro 解説ありがとうございます。ご面倒じゃなければ、JSON→WEBの自動化が実装されるまでは、データ更新後に反映作業をお願いした方がいいでしょうか？

**Comment by Kanahiro** [comment]
本番ページへの反映は不定期なので、slackにてデータを更新した旨を報告して頂ければ、反映までが早いと思います。ただ、いずれにせよデータの更新は1日に2,3回程度はしているので、その頻度で差し支えなければ（報告がなくとも）大丈夫です:)

**Comment by Nar-Ogasawara** [comment]
ご丁寧にありがとうございます。
では日中データ更新した場合は報告なし、夜間にデータ更新する事になってしまった場合はSlackで報告、という運用にさせていただいても大丈夫でしょうか？

**Comment by Kanahiro** [comment]
それで問題ありません！
ただ、有志のボランティアによる手動更新である事から、ご報告頂いてからの反映速度はメンバーの都合に依存する事をご承知ください😃

**Comment by Nar-Ogasawara** [comment]
もちろん即反映されずとも全く問題ありませんし、皆様に依存してしまい逆に大変申し訳なく思っております…

**Comment by NEKOYASAN** [comment]
こちらこそデータを提供いただき大変ありがたく思っております....本当にありがとうございます...

**Comment by daisuke-fukuda** [comment]
revertしたのでreopen
