### ISSUE TITLE
北海道以外のCOVID-19対策サイトにリンクを貼りたい

### ISSUE THREAD

**Issue by tk-suzuki** [codeforsapporo/covid19#155]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 各自治体ごとに孤立したサイトになっているので、相互アクセス可能にしたい

## 期待する見せ方・挙動 / Expected behavior
* サイドバー下部に小さいリンクを設置、東京、神奈川、その他今後サイトが増えれば順次追加

**Comment by Yfuruchin** [comment]
https://github.com/codeforsapporo/covid19/pull/157#issuecomment-596859781

**Comment by Yfuruchin** [comment]
#157 より
__
「他自治体の対策サイト」は見出しにしたかったのでリンクを貼っていませんが、マウスオーバーするとクリッカブルに見えます。必要であれば修正します。もしくは見出しをなくしてしまう方が修正は簡単ですが、要望ありますでしょうか？

文字サイズは他メニューより小さくした方が良いでしょうか？

issueには東京、神奈川と書いてあるのですが、神奈川のサイトを見つけることができませんでした。どこにあるかご存知でしょうか？(もしくはこれから？)
__

→
神奈川版は
https://stopcovid19.kanagawa.work/
です🙇

**Comment by harada4atsushi** [comment]
@Yfuruchin コメントありがとうございます。後ほど続きやりますね。

**Comment by tk-suzuki** [comment]
#168 にてclose
