### ISSUE TITLE
OGPとQRコードを組み合わせて印刷可能なページがあるとうれしい？

### ISSUE THREAD

**Issue by irasally** [codeforsapporo/covid19#159]
- [ ] バグ / Bug
- [ ✔️ ] 改善提案 / Suggestions for improvement

## 期待する見せ方・挙動 / Expected behavior
* OGPとQRコードを組み合わせた、印刷可能なシンプル静的ページがあると、各自印刷して回してください、というような形で、ページにアクセスできる人が増えるかもしれない

**Comment by NEKOYASAN** [comment]
表示イメージとかあればありがたいです

**Comment by irasally** [comment]
![flierimage](https://user-images.githubusercontent.com/293996/76370844-8dd69900-637b-11ea-9c52-38f430232c92.png)

こんな感じのイメージです

**Comment by irasally** [comment]
↑PDFおいておきます。
[flier.pdf](https://github.com/codeforsapporo/covid19/files/4315914/flier.pdf)
