### ISSUE TITLE
帰国者・接触者電話相談センター相談件数 のデータ収集

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#16]
<img width="412" alt="スクリーンショット 2020-03-06 11 19 15" src="https://user-images.githubusercontent.com/3221619/76044263-2dbbad80-5f9d-11ea-9b9c-eac521c52177.png">

道が公開しているデータを定期的にスクレイピング、反映させる。

関連: #12

**Comment by watanavex** [comment]
データ収集については #2 で議論が進んでる

**Comment by koukita** [comment]
現状は、札幌市保健所の件数が札幌市から提供される。
道庁からのデータはなし。

**Comment by watanavex** [comment]
issue整理のためcloseします。 以降は #12 にて。
