### ISSUE TITLE
development環境のrobots.txtのdiallowが効いていない

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#163]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem

-robots.txtの構文が誤っているため、disallowが効いていない

## 期待する見せ方・挙動 / Expected behavior

```
User-agent: *
Disallow: /
```

本家にもissueあげておきました。

https://github.com/tokyo-metropolitan-gov/covid19/issues/972

北海道版のデプロイプレビューは対応済です。

**Comment by NEKOYASAN** [comment]
対応済みのようなのでクローズします

**Comment by daisuke-fukuda** [comment]
あ、北海道版はまだです！

**Comment by daisuke-fukuda** [comment]
developmentの対応がまだ。（本家が対応してるのでcherry-pickすればOK

**Comment by NEKOYASAN** [comment]
了解しましたーごめんなさーい
