### ISSUE TITLE
インフラのモニタリングと可視化

### ISSUE THREAD

**Issue by nobuh** [codeforsapporo/covid19#165]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 現状さくらのアカウントのクラウドコンソールでアクセラレーターやサーバーの負荷状況など見れるが、パブリックに共有するには不向きなのでグラフダッシュボードみたいな機能があるのが望ましい
* 同様にモニタリングからのアラート整備

**Comment by NEKOYASAN** [comment]
さくらのAPIからデータ持ってきて表示できるようにしてみますか？
前にやったことあるのでできるかと思いますが...

**Comment by daisuke-fukuda** [comment]
さくらのアカウントがnobuhさんの個人アカウントになっている件はここで議論しますか？

なんかしらダッシュボード的なのを組むにせよ、個人管理ではなくて複数人で管理できる体制にしたいですよね・・・

**Comment by NEKOYASAN** [comment]
さくらのクラウドってIAM的なことできるんでしたっけ

**Comment by nobuh** [comment]
そうなんでよね、アカウントやサーバーの共有方法ともからむところなので、悩ましいところですね。。。

アカウントの件は時間かかりそうななので、先にこのへんはリファレンス実装みたいなのを push してもらって、それをサーバー上で実体化する、みたいな感じとかどうかなと思ったところでした。

アカウント自体の問題は別 issue のほうがよいかなと思います

**Comment by daisuke-fukuda** [comment]
> アカウント自体の問題は別 issue のほうがよいかなと思います

了解です。issueたてますね。

**Comment by NEKOYASAN** [comment]
Dashboard的なもの(GAとかも一括でみれるようなもの)試しにやってみますか...?

**Comment by daisuke-fukuda** [comment]
https://github.com/codeforsapporo/covid19/issues/166

**Comment by nobuh** [comment]
ダッシュボードいいですねｗ

今回さくらさんからご支援頂いていてそれは活用したい＆運用は無人運転でありたいし、構築もミニマムだとありがたいので、インフラ的には

- 出来るだけさくらのクラウドのサービスの中のものを使う
- 無いところはセルフホストするとして、シンプルにミニマムに実装

とかがよいかなと思ったりしています。どうしても時間限られてますし。。。

**Comment by Yfuruchin** [comment]
さっき森さんとも（生で）はなしてたんですが、そろそろサステイナブルなことをかんがえたリソース配分もかんがえないといてけないので、本家もみていると、自動デプロイなどのほうのプライオリティを上げるほうがよいかもしれないですー

**Comment by NEKOYASAN** [comment]
> さっき森さんとも（生で）はなしてたんですが、そろそろサステイナブルなことをかんがえたリソース配分もかんがえないといてけないので、本家もみていると、自動デプロイなどのほうのプライオリティを上げるほうがよいかもしれないですー

ここで言って申し訳ないんですが、issueにタグつける権限だけでもいただけるとプライオリティの管理がしやすくなります…（あとできればassignも…）

**Comment by Yfuruchin** [comment]
おおそうですね！あざます！では付与します！

**Comment by takayuki-fuwa** [comment]
サーバの運用監視面なのですが、さくらのクラウドにはダッシュボードを公開出来るような機能が無く、Sensuとかprometheusを使うといいのかなって思ってます。
(どこのサーバに置くの？っていう話は置いておいて)

個人的にはMackerel使うと楽かなぁと思ってます。

**Comment by NEKOYASAN** [comment]
Vultrのクレジット余ってるのでお貸しできるので必要であれば言っていただければと…

インフラ周り詳しいわけではないので一旦退散しますw

**Comment by takayuki-fuwa** [comment]
ちなみにMackerelなら自分で既にアカウント持ってるし、提供できますよ。

**Comment by daisuke-fukuda** [comment]
Mackerelは使った事がありますが、agentをinstallすると、CPUやらメモリやらディスク容量が取得できて、しきい値もうけたりSlackに通知できて便利ですよね！

今の環境だとすごく良さそう。

**Comment by nobuh** [comment]
さくらのシンプル監視で
* stopcovid19.hokkaido.dev の https 
* オリジンサーバー 133.242.52.161 の http
* stopcovid19.hokkaido.dev の SSL 期限20日以下通知
の３つ設置しました

**Comment by nobuh** [comment]
こちら仕組みいくつか実装されましたし close しますー
