### ISSUE TITLE
サーバの管理アカウントの共有に関すること

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#166]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem

* 使用しているさくらインターネットアカウントはnobuhさんの個人アカウント
  * ログイン情報共有するとnobuhさんの個人の情報も見えちゃうので、アカウント共有もできていない
  * なんかしら改修の必要や障害起きた時に、nobuhさん個人に頼らざるを得ない
* サーバにsshする鍵はさくらインターネットのアカウントとは無関係なので、どうにでもなる（現状、nobuhさんとdaisuke-fukudaがアクセスできる状況）

## 期待する見せ方・挙動 / Expected behavior
* 複数人で協力して管理ができる体制であること

**Comment by NEKOYASAN** [comment]
https://manual.sakura.ad.jp/cloud/controlpanel/user-account.html

この機能で共有できませんか？

**Comment by takehirock** [comment]
>無償化処理回しますので会員IDとか分かり次第シェアお願いしますー。
会員ID単位でサービス頂いてるので、名称の変更等は問題ないと思います

**Comment by nobuh** [comment]
クラウドの運用アカウントは権限設定して限定メンバーで共有するのは出来ると思いますのでまずはそちらでやりますね

難しいのはさくらインターネットの会員自体の共有ですねー　全部一旦森さんに変更するのも手かもです

**Comment by nobuh** [comment]
以下の４名の方のご協力を頂いて ssh やさくらのクラウド（一部制限）アカウントを共有しました
- Takayuki Fuwa
- Taiyu Yoshizawa
- T.Suzuki
- daisuke-fukuda

**Comment by NEKOYASAN** [comment]
解決した模様なのでcloseですー
