### ISSUE TITLE
アイコンが崩れる

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#169]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* xxxx(できるだけ簡潔に/as concise as possible)

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
*

**Comment by daisuke-fukuda** [comment]
https://github.com/nuxt-community/vuetify-module/issues/298

**Comment by NEKOYASAN** [comment]
修正済みのためcloseしますー
