### ISSUE TITLE
外部リンクの北海道化

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#17]
- [*] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 各種リンク先が都のurlになっている
* リンクのテキストが都の名称になっている

## 期待する見せ方・挙動 / Expected behavior
* 該当する道の情報へリンクする

**Comment by watanavex** [comment]
まずは洗い出しから。

**Comment by zakijun** [comment]
⭐️が北海道関連のURL。マークダウンにちょいと慣れてなく、とりあえず貼り付けます。

- お子様をお持ちの皆様へ

    【参考】感染症予防のための正しい手洗い方法（動画）
    https://tokyodouga.jp/lViN9C_BS-0.html

        ⭐️自宅での消毒方法について
        http://www.pref.hokkaido.lg.jp/hf/kth/kak/syoudokumatome.pdf

    「新型コロナウイルス感染症にかかる相談窓口について」（東京都福祉保健局）
    https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html

        ⭐️相談窓口及び帰国者・接触者相談センターについて
        http://www.pref.hokkaido.lg.jp/hf/kth/kak/singatakoronahaien.htm#%E7%9B%B8%E8%AB%87%E7%AA%93%E5%8F%A3

- 都民の皆様へ

https://www.metro.tokyo.lg.jp/tosei/tosei/news/2019-ncov.html

    ⭐️このURLが、道庁からのコロナ関連のポータルっぽい。
    http://www.pref.hokkaido.lg.jp/ss/tkk/singatakoronahaien.htm
    http://www.pref.hokkaido.lg.jp/hf/kth/kak/singatakoronahaien.htm

- 企業の皆様・はたらく皆様へ

    中小企業者等特別相談窓口
    https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/01/30/15.html

        ⭐️新型コロナウイルス関連肺炎の流行に伴う中小企業向け相談窓口及び融資取扱について
        http://www.pref.hokkaido.lg.jp/kz/csk/kny/yuushi/korona.htm

    緊急労働相談ダイヤル
    https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/02/26/22.html

        ⭐️今般の新型コロナウイルス感染症により影響を受ける事業主、労働者の方向けの、相談窓口や各種支援措置をお知らせします。
        http://www.pref.hokkaido.lg.jp/kz/rkr/korona.htm

    新しいワークスタイルや企業活動の東京モデル「スムーズビズ」
    https://smooth-biz.metro.tokyo.lg.jp/

        ⭐️まとめてるサイトは無さそう。。。。


- 東京都新型コロナウイルス感染症対策本部報

https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html

    ⭐️新型コロナウイルス感染症の道内の発生状況 と
    　発表資料のPDF一覧
    http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijoukyou.htm

- 【東京都主催等】中止又は延期するイベント・説明会等

https://www.seisakukikaku.metro.tokyo.lg.jp/information/event02.html

    ⭐️まとめてるサイトは無さそう。。。あちこちに散財してる。
    以下、一例。
    http://www.pref.hokkaido.lg.jp/page.jsp?id=1274949&version=&0.0221183048993292

- 知事からのメッセージ

https://www.metro.tokyo.lg.jp/tosei/governor/governor/katsudo/2020/03/03_00.html

    ⭐️知事記者会見
    http://www.pref.hokkaido.lg.jp/ss/tkk/hodo/pressconference/r1.htm
    記者会見内容のページへの一覧

    ⭐️知事記者会見動画
    https://sites.google.com/site/hokkaidouchotv/home/torikumi/chijikaiken
    youtube の一覧

- 東京都公式ホームページ

https://www.metro.tokyo.lg.jp/

    ⭐️北海道庁公式ホームページ
    http://www.pref.hokkaido.lg.jp/index.htm

**Comment by watanavex** [comment]
#30 の対応で一旦完了かなと思います。
Closeします！
