### ISSUE TITLE
SEO対策

### ISSUE THREAD

**Issue by takehirock** [codeforsapporo/covid19#178]
適切なキーワードで流入させたい

**Comment by tk-suzuki** [comment]
気になった点:

1. **descriptionが冗長**
descriptionは「サイトの内容を説明するもの」なので、もっと内容を絞るべき。
ここは今日プルリク送ります。
2. **keywordsがない**
description同様、簡潔かつ重要なものだけを表記。
ここは今日プルリク送ります。
3. **ヘッダタグがh1しか使われていない**
コンテンツの中で目立つべきキーワードがなく、すべてが等価にマークアップされている。
「現在患者数」などのタイトル部分はh2タグにした方がよいのでは。

**Comment by NEKOYASAN** [comment]
1は同意します...
2って今google botが読んでなかった気がするんですが...
3はDataView.vueを書き換えればある程度対応可能ですが、デザイン考えたりしないとなので少しつらいかも...?

**Comment by tk-suzuki** [comment]
2、Googleは見てないと明言してますけど、正直この辺はよくわからんです。
順位付けには使ってないけど、構造見るときの参考にはしてるんじゃないかみたいな話もあったり、正直憶測が飛び交うばかりなので、個人的には「負担にならないなら入れとこう」って感覚です。

3、多分一番効果があるんですが、そうなんですよね。CSSもちゃんと直さないとスタイル崩れると思います。

**Comment by NEKOYASAN** [comment]
了解です！1,2お願いします、3は落ち着いたらやれるタイミングでやりましょう

**Comment by tk-suzuki** [comment]
あと Powered by さくらインターネット の上か下に Operated by JUST道IT 入れたい（現状、JUST道ITという文言がサイト内のどこにもない）

あるいは、ページタイトルの後ろに by JUST道IT って入れてもいいかも？

**Comment by NEKOYASAN** [comment]
りょーかいですロゴ作ってもらいます？

**Comment by daisuke-fukuda** [comment]
JUST道IT はaboutにはありますね。

**Comment by tk-suzuki** [comment]
ありがとうございます！

**Comment by tk-suzuki** [comment]
> JUST道IT はaboutにはありますね。

あ、ごめんなさい、私が間違った書き方したせいで変な伝わり方しました。
JUST道ITって言葉がトップページにないので、現状では報道を見聞きしてJUST道ITで検索しても引っかからないと思うんですよね。
それを何とかしたいという話でした。

**Comment by tk-suzuki** [comment]
@takkundayo 提供のこれ使います。
![JUST道IT](https://user-images.githubusercontent.com/48782652/76392186-605a1180-63b4-11ea-839b-12743a5ccf4f.png)

**Comment by tk-suzuki** [comment]
リンク増やすのもSEO対策になるし、ついでにオープンソースらしさが出てよい気がするので、GitHubへのリンクをつけたい（東京の方はついてるんですね）

**Comment by daisuke-fukuda** [comment]
以下のページをSearchConsoleでIndex登録のリクエストを出しました。

https://stopcovid19.hokkaido.dev/parent
https://stopcovid19.hokkaido.dev/worker
https://stopcovid19.hokkaido.dev/about

**Comment by NEKOYASAN** [comment]
#405 などでPageSpeed Insightのスコア改善、検索上位になるようになったためclose
