### ISSUE TITLE
データの更新方法のフローについて

### ISSUE THREAD

**Issue by koukita** [codeforsapporo/covid19#179]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* v0のデータ更新はすべて手動？
* 今後は行政がオープンデータで出すときに、自動で更新するようになると良い

## 期待する見せ方・挙動 / Expected behavior
* 陽性患者属性（patients）→北海道オープンデータポータルにある「patients.json.csv」から「patients.json.json」を更新
* 陽性患者数（patients_summary）→北海道オープンデータポータルにある「patients_summary.csv」から「patients_summary.json」を更新
* 現在患者数（current_patients）→北海道オープンデータポータルにある「current_patients.csv」から「current_patients.json」を更新
* 陰性確認数（discharges_summary）→北海道オープンデータポータルにある「discharges_summary.csv」から「discharges_summary.json」を更新
* 新型コロナコールセンター相談件数（contacts）→Data-Smart City Sapporoにある「札幌市新型コロナウイルス一般電話相談窓口の相談件数」から「contacts.json」を更新
* 帰国者・接触者電話相談センター相談件数（querents）→Data-Smart City Sapporoにある「救急安心センターさっぽろ（帰国者・接触者電話相談センター）の相談件数」から「querents.json」を更新

**Comment by koukita** [comment]
札幌市のデータの自動更新もできるようになってきたので、道庁分のデータも、北海道オープンデータポータルで更新していこうと思いますがどうでしょう？
事実情報ですので著作権など無いですが、色々心情的なものもあると思うので、道庁と話ができるまでは「テストデータ」として更新してきたいと思いますが・・・

**Comment by NEKOYASAN** [comment]
期待する見せ方・挙動についてですが
- [ ] 陽性患者属性（patients）→北海道オープンデータポータルにある「patients.json.csv」から「patients.json.json」を更新
- [ ] 陽性患者数（patients_summary）→北海道オープンデータポータルにある「patients_summary.csv」から「patients_summary.json」を更新
- [ ] 現在患者数（current_patients）→北海道オープンデータポータルにある「current_patients.csv」から「current_patients.json」を更新
- [ ] 陰性確認数（discharges_summary）→北海道オープンデータポータルにある「discharges_summary.csv」から「discharges_summary.json」を更新
- [x] 新型コロナコールセンター相談件数（contacts）→Data-Smart City Sapporoにある「札幌市新型コロナウイルス一般電話相談窓口の相談件数」から「contacts.json」を更新
- [x] 帰国者・接触者電話相談センター相談件数（querents）→Data-Smart City Sapporoにある「救急安心センターさっぽろ（帰国者・接触者電話相談センター）の相談件数」から「querents.json」を更新

現在すでに自動化が終了しているのはチェックがついている２項目です
仕組み自体はすでに作成を終えているため上の４つについてもいつでも自動化可能です。
北海道オープンデータポータルで更新していただけると自動更新に組み込めるためとても助かります。

**Comment by koukita** [comment]
では、明日の更新分から、北海道分のデータは北海道オープンデータポータルで更新するようにします。

**Comment by koukita** [comment]
データの内容について、別のIssueを立てます

**Comment by NEKOYASAN** [comment]
わかりました。ここのissueをcloseしてもいいですか？

**Comment by koukita** [comment]
いいです。

**Comment by NEKOYASAN** [comment]
解決のためクローズします
