### ISSUE TITLE
画像・アイコンの北海道化

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#18]
- [*] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* アイコン、画像で表現されるコンテンツが都の情報になっている

## 差し替えが必要なもの
- https://github.com/codeforsapporo/covid19/blob/development/static/apple-touch-icon-precomposed.png
- https://github.com/codeforsapporo/covid19/blob/development/static/favicon.ico
- https://github.com/codeforsapporo/covid19/blob/development/static/icon.png
- https://github.com/codeforsapporo/covid19/blob/development/static/logo.svg

## 動作環境・ブラウザ / Environment
*

**Comment by watanavex** [comment]
特に、このページは全て画像リソースで表現されている
https://stopcovid19.metro.tokyo.lg.jp/flow

が、都がローカライズのために改修するようで、その動向にも注意
https://github.com/tokyo-metropolitan-gov/covid19/issues/576

**Comment by daisuke-fukuda** [comment]
https://www.figma.com/file/V7vt80p2gauhdgTZeVNbgj/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=121%3A533

デザイン系はこちらで管理しているようです。

**Comment by watanavex** [comment]
あぁ〜そっか、figmaで公開されてるんですね！
どうしようかな... ひとまず、デザイナーさんがSlackでアイコン作ってくださったので、そこは手動で取り込みます。
追々独自デザインとか出てきたら何か考えようかな...
ネックはコレなんですよね https://stopcovid19.metro.tokyo.lg.jp/flow
このページが本家でどう変わるかで、管理の仕方が大きく変わるかなと...

**Comment by watanavex** [comment]
画像リソースは差し替え済み。 8864c43314ce16c1791a4e00776de1ccb867ff75
残りは https://stopcovid19.metro.tokyo.lg.jp/flow をどうするか。

**Comment by watanavex** [comment]
#30 の対応で完了する見込み。なので、このissueは閉じちゃいます！
