### ISSUE TITLE
陽性患者属性のデータカラム

### ISSUE THREAD

**Issue by koukita** [codeforsapporo/covid19#180]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 北海道庁、[札幌市](https://ckan.pf-sapporo.jp/dataset/covid_19_patients/resource/44d92c21-f11b-4ee5-833e-9f9ec13eafef)、[東京都](https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068/resource/c2d997db-1450-43fa-8037-ebb11ec28d4c)（オリジナル）で、陽性患者属性のデータカラムが違う。
* 北海道はカラムが少なすぎるので、札幌市か東京都に合わせたい。
* カラム名が変わったら、自動更新に影響がある

**Comment by koukita** [comment]
北海道のデータには揺れが大きいため、今後データを使うとき（地図化や分析など）に扱いづらいと考えています。
できれば、[札幌市のデータセット](https://ckan.pf-sapporo.jp/dataset/covid_19_patients/resource/44d92c21-f11b-4ee5-833e-9f9ec13eafef)に合わせたいけど、システム側で問題ありますか？

**Comment by koukita** [comment]
当初とデータの作りがだいぶ変わってきたので、現在の状況で、一度整理したいと思います。
Jsonのキーも英字になったので対応表を作ります

**Comment by koukita** [comment]
日付のデータは、CSVは「2020-01-28T08:00:00.000Z」、jsonは「2020-01-28T00:00:00+09:00」ですが、合わせなくてもいいですか？
もしくは、CSVは日付のみでもいいでしょうか？
（役所の人が入力する場合、日付/時間の入力に慣れていなく、入力内容が揺れる可能性があります）

**Comment by daisuke-fukuda** [comment]
timezone付きじゃないとsaffariで表示がくずれちゃうバグがあったような、、、

**Comment by daisuke-fukuda** [comment]
https://github.com/codeforsapporo/covid19/issues/121

データフローによってどこで吸収するか変わるので、私の理解では回答できないです。ごめんなさい。

ひとまず参考情報として↑。

**Comment by koukita** [comment]
今まで通りで、全然問題ないなら、いままでと同じ型でCSV作ります

**Comment by NEKOYASAN** [comment]
webkit系（iPhoneの全ブラウザやMacのSafari）の表示がバグるためjsonに変換するときにJSTを指定しているため2020-01-28T00:00:00+09:00という表示になっています。
いただいたcsvのタイムゾーンがJST（日本標準時）で固定されていれば日付のみ、日付・時刻両方の部分は揺れても大丈夫です。（2020-01-28T08:00:00.000Z csvだとこの形が一般的なのかな...?)

**Comment by koukita** [comment]
了解しました。とりあえず、今までのままにします。
スプレッドシートにテーブル対応表を作成しました。
[https://docs.google.com/spreadsheets/d/1JuUGlxLRA7EDAMh17f-Nfi3E8z2HI_PV3GZZ3PTU55g/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1JuUGlxLRA7EDAMh17f-Nfi3E8z2HI_PV3GZZ3PTU55g/edit?usp=sharing)

**Comment by NEKOYASAN** [comment]
@koukita 要請患者属性の居住地はjsonのkeyはplaceですね、そして陽性患者属性ってこんなに細かく記録されてたんですね...
退院の部分って1が退院済み、0が入院中とかだったりしますか？
csvにあるデータでできればあまり公開しないほうがいいと思われるデータがあれば教えていただけると助かります

**Comment by koukita** [comment]
[北海道オープンデータポータル](https://www.harp.lg.jp/opendata/dataset/1369.html)に4つのCSVを置きました。

自動更新できるようにしていただければと思います。
データが変わっているので、[対応表](https://docs.google.com/spreadsheets/d/1JuUGlxLRA7EDAMh17f-Nfi3E8z2HI_PV3GZZ3PTU55g/edit?usp=sharing)を参照してください。
データを使用する、しないも記載しました。

**Comment by NEKOYASAN** [comment]
自動更新可能なようにプログラムをすぐに更新します。
今後こちらの4つのcsvからのみのデータ更新で問題ないでしょうか？
（問題なければこちらのcsvからjsonを生成しそのままwebに反映するようにします）
Webから引っ張ってきているデータも含まれているのでそれができるとスクレイピングを止めることができます....

**Comment by koukita** [comment]
@Nekoya3 
はい、今後はこのCSVでデータを更新します。
道庁の担当が行えるようになるまでは（なるかどうかわかりませんが）、私が更新するので、できるだけ早く更新しますが、道の発表とはタイムラグがあると思いますが、オープンデータポータルであれば職場からも更新できるので、更新しやすいです。
Githibが職場から見られないので・・・

**Comment by NEKOYASAN** [comment]
了解しました！ありがとうございます。すでにプログラムは出来上がりましたのでいつでも更新は可能です。

**Comment by NEKOYASAN** [comment]
これでデータカラム確定かと思いますのでissueクローズします
何かあれば連絡いただければreopenします
