### ISSUE TITLE
SSRどこまで考慮するか検討

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#185]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* Nuxtの設定的にはuniversal（SSR対応）
* デプロイフロー、サーバ環境的にはspa

で、どっちつかず。

可能性を考慮しながら開発するのすごく迷うので、どちらかに振り切りたい思い。

**Comment by NEKOYASAN** [comment]
nuxt generate でもOGPを各ページに設定するうえでunivasalにする必要があるためuniversalモードで確定ではあるんですけど...

**Comment by daisuke-fukuda** [comment]
あ〜、そういう謎縛りがあるんですねぇ、、、

今のところは全ページ共通ですよね？？

**Comment by NEKOYASAN** [comment]
ですねー、私としては
https://github.com/tokyo-metropolitan-gov/covid19/issues/774#issue-577347665
をやりたいなーって考えてはいます

**Comment by daisuke-fukuda** [comment]
あ〜、これは、、、やれるならやりたいですねぇ。

では設定的にはuniversalは残した方が良さそうですね。


あとは実装上、SSRされる事を見越して実装するかどうかかな？

**Comment by NEKOYASAN** [comment]
SSRはサーバーリソースがががってなりそうではありますねぇ...

**Comment by daisuke-fukuda** [comment]
SSR無視して作って、後からSSRに対応するのってどれくらい大変そうかわかりますでしょうか？

私SSRで作った事がなくて、どれくらい大変かわからず、、、

**Comment by NEKOYASAN** [comment]
nuxtの場合そのままでssrほぼ対応されます...なのでほぼ気にしなくてもよいかと思います...

**Comment by NEKOYASAN** [comment]
window.とかのクライアント描画系がno-ssrを指定する必要は出ますが

**Comment by NEKOYASAN** [comment]
generateしてるのでSSRしないとOGPが適用されないためSSR必須
何か特別考慮すべきことがNuxtにはないためclose
