### ISSUE TITLE
サイドメニューの「他自治体の対策サイト」が選択できそう

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#188]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 特にスマホだと誤ってタップするとメニューが閉じてしまうので、ちょっとストレスかも

## 期待する見せ方・挙動 / Expected behavior

↓は案です。

* 単純に見た目を変えて、他の要素と差別化
* 冗長だけど、「他自治体の対策サイト」は消して、「東京都〜まとめサイト」「神奈川〜まとめサイト」とそのまま書く
* アコーディオンにする

**Comment by watanavex** [comment]
> 冗長だけど、「他自治体の対策サイト」は消して、「東京都〜まとめサイト」「神奈川〜まとめサイト」とそのまま書く

に、一票🕺

**Comment by NEKOYASAN** [comment]
> 冗長だけど、「他自治体の対策サイト」は消して、「東京都〜まとめサイト」「神奈川〜まとめサイト」とそのまま書く

に一票！

**Comment by daisuke-fukuda** [comment]
じゃ、これでやっちゃいます。神奈川の削除とあわせて対応しますね
