### ISSUE TITLE
本番環境構築

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#19]

**Comment by watanavex** [comment]
有識者の方、アイディアをお願いします！

**Comment by daisuke-fukuda** [comment]
関連issue

#21 
#20

**Comment by daisuke-fukuda** [comment]
stagingとデプロイ運用周りもセットで一旦お話します。

本家の方は、

CI：GitHubAction
https://github.com/codeforsapporo/covid19/tree/development/.github/workflows

サーバ（stagingも本番も）
Netlify

を使って構築されているようです。

同じ環境に揃えられれば、本家で作成されたCI系のスクリプト等、設定がほぼそのまま使えますので、環境構築の工数が大きく削減できます。

というわけで、タスクとしては以下のようになるかと思います。


- 本家側と調整
  -  使用しているSaaS系サービスを教えてもらう
  - それぞれについての費用周りを確認
  - 可能であれば設定の閲覧権限をいただけないか調整
- 内部調整
  - ↑が有料プランを使っている場合
    - 費用をどうにかできないか検討
    - 無料プランで運用できないか検討

**Comment by watanavex** [comment]
サーバーはさくらインターネットさんを利用させて頂くお話が浮上していました！ (slackで💦)
確かに、yaml流用できれば工数削減できますね！

**Comment by daisuke-fukuda** [comment]
https://codeforsapporo.slack.com/archives/CUKTK3R4K/p1583458929064400

さくらさんの話はこちらですね

**Comment by daisuke-fukuda** [comment]
個人的には、データ取得のAPI等はさくらさんを利用させてもらいつつ、ホスティングは本家と同じ方式が良いのでは？と思っています。

理由としては、

- NuxtのSSRを使っている
  - SSRで動く環境を一から作るのは大変
    - SSRしないとう作戦もあり（静的ファイルを置くだけなので）
- 負荷分散等を丸投げできる
  - 落ちてしまったら意味が無いので、、、
  - 負荷対策にかける時間がもったいない

です。

と、思っていたのですが、

あ〜、お金周りの調整工数考えたら、SSRしないでさくらインターネットさんにホスティングするのが最速かなぁ、、、石狩のデータセンターに頑張ってもらう。うーん。

**Comment by watanavex** [comment]
@daisuke-fukuda すいません、私インフラはシロウトなのでアレなんで
いろいろアイディア頂けたらと思います！

**Comment by daisuke-fukuda** [comment]
お昼ご飯食べてたら、GithubPagesの存在も思い出しました。
とりあえずstaging環境はこれで十分だと思うのでちょっと試してみますね。

**Comment by daisuke-fukuda** [comment]
https://app.netlify.com/sites/dev-covid19-tokyo/deploys/5e61d5b5684ca7000b148660

netlifyのデプロイログ。
名前的にsekiさんが管理しているっぽいので、ちょっと聞いてみます。

**Comment by daisuke-fukuda** [comment]
GithubPages試してみました。

↓fork先で実験したものです
https://daisuke-fukuda.github.io/covid19-githubpage-test/

- 1リポジトリに1サイトしか作れない（複数ブランチ対応ができない）
- customドメインを設定しないと、ルートに`/<リポジトリ名>/` がついてしまうため、nuxt側の設定をいじらないとだめ
  - 画像のpathの解決が若干手間 https://github.com/nuxt/nuxt.js/issues/4544


というわけで、イマイチですね。
1リポジトリに1サイトしか作れないのが致命的で、本番とstagingを同環境で、というのができないです。

**Comment by daisuke-fukuda** [comment]
メモ：本家でもSSRはしてない気がする

**Comment by aruneko** [comment]
Nuxtのモードとしてはuniversalになってますが、デプロイ前にgenerateしているので静的サイトになっていると思われます。

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/nuxt.config.js#L6
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/workflows/deploy.yml#L29

**Comment by daisuke-fukuda** [comment]
いったん私の個人環境netlifyにあげてみました。（何もしなくて良いので一瞬でした

https://boring-shockley-101165.netlify.com/

**Comment by daisuke-fukuda** [comment]
Netlifyにあげる設定手順メモ

## Actionを有効にする

forkした状態だと無効になってるので。

## Netlify設定

「New Site From Git」からリポジトリとブランチを指定。
ブランチの対応は以下の通り。

本番：production
staging：gh-pages
development：dev-pages


かんたん。

**Comment by nobuh** [comment]
さくらのクラウドに以下の環境を git pull でのデプロイで立てました

```
dev (dev-pages) http://133.242.52.161:58000/
staging (gh-pages) http://133.242.52.161:50080/
production (production) http://133.242.52.161/ ここは鈴木さんに stopcovid19.hokkaido.dev ドメインご提供頂いて、＋アクセラレーターで SSL 予定です
```

**Comment by daisuke-fukuda** [comment]
メモ
https://codeforsapporo.slack.com/archives/CUKTJMVS7/p1583591286054400?thread_ts=1583589700.053600&cid=CUKTJMVS7

本リリースするときにrobots.txt消す

**Comment by nobuh** [comment]
133.242.52.161 の前面にさくらのアクセラレターを立て、そこに stopcovid19.hokkaido.dev の Lets Encrypt 証明書を置き、https://stopcovid19.hokkaido.dev で動きました

**Comment by nobuh** [comment]
アクセラレーターの方は無効化すると DNS の内容の再設定が必要になる可能性があったので、とりいそぎ一旦本番サイトはオリジンサーバーの方で停止しました

**Comment by NEKOYASAN** [comment]
本番環境がすでに構築済みなためcloseします
