### ISSUE TITLE
北海道のCOVID19にまつわる機械可読性の高いデータがない

### ISSUE THREAD

**Issue by tk-suzuki** [codeforsapporo/covid19#2]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* HTML +PDFの状況なので、パース不可
* そもそも東京都JSONと同様のデータがあるのか（私が）未検証

## 期待する見せ方・挙動 / Expected behavior
* データをCSV化する

**Comment by Yfuruchin** [comment]
道の体制が整うまでこのスクリプトを用いる

> Kanahiro Iguchi  19:11
>http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijoukyou.htm
>とりあえず、このページをスクレイピングしてjsonに書き出すスクリプトを書いてみました
>https://github.com/Kanahiro/covid19hokkaido_scraping
>使い物になるかはまだわかりません笑

**Comment by Yfuruchin** [comment]
-  東京都サイトのデータ項目を確認
- 使えそうな北海道庁データで上記スクリプトでcsvへパース可能に

**Comment by Kanahiro** [comment]
https://github.com/Kanahiro/covid19hokkaido_scraping
私用のリポジトリ上で、15分おきにCSVとJSONに書き出すようになりました。使えそうなら本体に取り込めれば…

**Comment by watanavex** [comment]
codeforsapporo/covid19 のプロジェクトに上記のスクリプトを取り込んで、
同じようにworkflow組めばOKって理解で合ってます？

**Comment by Kanahiro** [comment]
です。現状、出力先ブランチがgh-pages、出力先ディレクトリがルートになっているので適宜修正は必要です。

**Comment by watanavex** [comment]
すいません、私アプリ屋なので変なこと言ってるかもなんですが、
- 別リポジトリとして、このorganizationにforkする
- 定期ジョブは公開コンテンツとは別で管理する

の方がキレイかなと思ったりしました。
あとでAPI化された時も、本体に影響しないので。
どうでしょう？

**Comment by Kanahiro** [comment]
はい、私もそれがよいと思います！

**Comment by watanavex** [comment]
どんなアーキテクチャにするかアイディアありますか？

**Comment by daisuke-fukuda** [comment]
本番の環境次第なところはありますが、さくらインターネットさんのサーバをお借りするとして、

- ひとまず積極的に同じリポジトリにする理由は無いので別リポジトリとして管理
- 別リポジトリで定期的に実行 & 出力結果をサーバにアップロード

が良いと思いました。

**Comment by watanavex** [comment]
Nuxt.jsぜーんぜん知らないんですが、いまデプロイ用？にビルドしてみました
`yarn run generate`
/dataディレクトリはjsonのまんまじゃなくて、何かにコンパイルされるっぽい？
(/dataディレクトリはない)

なので、、、デプロイワークフローの中で
1. 別リポジトリからスクリプト取得
1. データ取得してjson化
1. ビルド&デプロイ

みたいな流れになるんですかね？

東京のワークフローはそんな事してるように見えないなぁ...
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/workflows/deploy.yml

**Comment by Kanahiro** [comment]
私もNuxtはそこまで詳しくないで推測というか予想ですが、ビルド時にJSのオブジェクトとして取り込まれ、静的ファイルとしては持たないのかも？（index.vueでdata/data.jsonが参照されている）

**Comment by daisuke-fukuda** [comment]
javascriptのobjectとしてimportされているので、webpackでjsファイルにコンパイルされた状態で公開されていますね。

**Comment by daisuke-fukuda** [comment]
データはAPI化される可能性を見越して、外部（ファイル/API）から取ってくるように改修しちゃうのかとイメージしていました。

**Comment by watanavex** [comment]
静的に埋め込むんじゃなくて、動的に取りにいく感じって事ですね？！

**Comment by daisuke-fukuda** [comment]
前提条件が色々ありそうなので、まとめてみました。


## 完全自動化案1 データを外部データとして扱う

- 自動でscrapingを回す
- 自動でscrapingした結果のデータをアップロードする
- nuxtは、↑のデータを外部データとして参照するように改修しておく

### メリット

- データがapi形式で公開された時に対応しやすい

### デメリット

- 自動化するために色々仕込んでおく必要がある
- データが自動で更新されるので、突然データが壊れる（スクレイピング元形式が変わったとか）可能性がある


## 完全自動化案2 データを内部データとして取り込む

- 自動でscrapingを回す
- 自動でscrapingした結果のデータを、nuxtにコミット
- コミットされたら自動でデプロイされる

### メリット

- 内部データとして扱われるので動作が早い

### デメリット

- データ更新のタイミングでnuxtも自動更新されるので、突然データが壊れる（スクレイピング元形式が変わったとか）可能性がある
- nuxtにコミットする時にコンフリクトとか起きそう（要検証


## 案1' 案1に手動作業含める

- 自動でアップロードするところはデータを確認してからアップロードするようにするとか


## 案2' 案2に手動作業含める

- nuxtにコミットするところはデータを確認してからコミットするようにするとか

**Comment by Kanahiro** [comment]
案2で考えてました。
data.jsonが都公式に準拠していれば既存のコードの変更が少なく済むかなと。

**Comment by watanavex** [comment]
案1の完全自動化を専用ブランチで粛々と進める。
完全自動化ブランチをマージするまでは `案2' 案2に手動作業含める` で運用する。
っとすると、いいとこ取り出来るかなぁなんて...

**Comment by Kanahiro** [comment]
案2'に沿って、手動でdata.jsonを差し替えてPRしようかなと思ったのですが、現状、patientsとpatients_summary以外のデータがありません。その他（コールセンター相談件数など）はすぐに出てくるデータではないと思うので、そのままPRしちゃってもよいのですかね？その場合、pages/index.vueも修正しないとエラーが出ると思われます。

https://github.com/Kanahiro/covid19hokkaido_scraping
ちなみに、こちらのリポジトリのコードを、今後のデータソース追加に備えて書き換えました。

**Comment by watanavex** [comment]
いま、コールセンターの情報はいったん札幌市の情報を出してはどうか という議論があります！
#31

**Comment by Kanahiro** [comment]
了解です！
v0でどのデータを表示するか決まるのを待った方が良さそうですね

**Comment by watanavex** [comment]
個人的にはコールセンター関係の情報を札幌のデータ利用するのは賛成です。
(ひとまずV0では。V1以降はまた別途考える)

なので、patientsとpatients_summaryはスクリプトで更新。
それ以外の札幌市から頂くデータは手動で更新。
☝️で運用できる形にするのがV0の目標として良いんじゃないかなと思います。

どうでしょ？

**Comment by Kanahiro** [comment]
賛成です😃
一応、都公式データと同じ構造のcsvなら、スクリプトで読み込んでpatientsとかとまとめてdata.jsonを吐き出せるようにしてあります。

**Comment by watanavex** [comment]
あざます！
では、コールセンター系のデータに整形作業が必要な場合は別issue、別PRで対応するとして、
patientsとpatients_summaryを更新するPRを出して頂けたらと思います！

**Comment by watanavex** [comment]
@Kanahiro さんのリポジトリ、code for sapporoにフォークしました！
(勝手にやっちゃいました。。。)

現状の再確認ですが、

||patients|patients_summary|contacts|querents|
|--|--|--|--|--|
|サイトでの名称|陽性患者の属性|陽性患者数|新型コロナコールセンター相談件数|帰国者・接触者電話相談センター相談件数|
|取得元|http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijoukyou.htm|http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijoukyou.htm|札幌市から直 (/import配下)|札幌市から直 (/import配下)|

この理解で合ってます？

**Comment by watanavex** [comment]
あ、すいません、READMEに書いてある通りですね！失礼しました！

**Comment by Kanahiro** [comment]
フォークして頂いて構いません！ありがとうございます😃
そしてその表のとおりの理解で間違いありません。

**Comment by koukita** [comment]
データ別の今後の取り扱いについて、[スプレッドシート](https://docs.google.com/spreadsheets/d/1JuUGlxLRA7EDAMh17f-Nfi3E8z2HI_PV3GZZ3PTU55g/edit?usp=sharing)でまとめてみました。

いまのところ、「陽性患者数の属性」と「陽性患者数」はCSVが必要なさそうですが、今後道庁の職員にデータ公開してもらうようになればいいと思いますので、それまでは私がデータが更新されたらCSVを作成しておきます。
地図の更新もありますし。

**Comment by koukita** [comment]
CSVデータを３月７日現在の北海道発表データに更新しました。

**Comment by koukita** [comment]
dataフォルダ内のCSVファイルを更新しました。
北海道に合うようにいくつかフィールドを追加したりしているので、対応表を作りました。
参考としてください。
「東京カラムとの比較」シートに作りました。
[https://docs.google.com/spreadsheets/d/1JuUGlxLRA7EDAMh17f-Nfi3E8z2HI_PV3GZZ3PTU55g/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1JuUGlxLRA7EDAMh17f-Nfi3E8z2HI_PV3GZZ3PTU55g/edit?usp=sharing)

**Comment by NEKOYASAN** [comment]
今後COVID19にまつわるデータを自動更新可能なレベルまでデータが集まりました。なのでcloseします
