### ISSUE TITLE
デプロイフロー構築

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#20]

**Comment by nobuh** [comment]
さくらのクラウドのサーバーで、dev / staging / production のバーチャルホストをホストしています。

５分毎に cron で以下のスクリプトを実行しています

```
#!/bin/bash
cd /home/covid19/dev-pages
git pull
cd /home/covid19/gh-pages
git pull
cd /home/covid19/production
git pull
```

同じく５分毎に systemctl reload nginx しています。アクセス毎にファイル更新チェックするホットロード設定、迷ったんですが、パフォーマンスが下がるので今回見送って定期 reload にとりあえずしています

production は前面にさくらさんのアクセラレーターをつけてそこで SSL ターミネーションする予定です

**Comment by daisuke-fukuda** [comment]
developmentまで（と、そこから派生してdev-pagesブランチ）までは、問題なく稼働できてると思います。

あとは、stagingとmasterへの反映フローをどうするかを決めればOK？
（システム的にはstaging環境と本番環境への自動反映までできているはず。forkしてから一度もコミットしてないので動作未確認だけど）
