### ISSUE TITLE
オープンデータポータルのCSVのSHIFT-JIS対応

### ISSUE THREAD

**Issue by koukita** [codeforsapporo/covid19#209]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 北海道オープンデータポータルにアップされるCSVは、SHIFT-JISなので、自動更新の対応をする

**Comment by koukita** [comment]
オープンデータポータルには、Shift-JISのCSVをアップしました
https://www.harp.lg.jp/opendata/dataset/1369.html

**Comment by koukita** [comment]
CSVの日付ですが、今後私でない職員が更新することを考えると、時間がないほうがいいと考えています。時間をなくして、日にちだけでも大丈夫ですか？
「日付＝2020-02-19」としたいです

**Comment by NEKOYASAN** [comment]
OKです！

**Comment by koukita** [comment]
![image](https://user-images.githubusercontent.com/13256642/76412920-dae85880-63d7-11ea-8348-b498b93de8aa.png)
日付に時間が入っていると、時間によって日付がずれる

**Comment by Kanahiro** [comment]
なお、以下のデータ取得・生成スクリプトでShift-JIS対応は完了しています。
https://github.com/codeforsapporo/covid19hokkaido_scraping

**Comment by koukita** [comment]
Rawデータは日本標準時ですがJavaScriptは問答無用でUTCで読み込んだのちに、実行環境で（？）JSTに解釈されてます
ODPのデータでは、patientsとsummaryのdateに時間が入力されるようになったため発生しています（＋9時間されると日付が変わる場合に問題となる）

**Comment by koukita** [comment]
時間を固定することは可能か？
↓
フロント側か、生成スクリプトか、いずれかで処理する事は可能ですが、もし可能であれば、元データ自体をyyyy-mm-dd形式になれば問題は発生しません

**Comment by koukita** [comment]
日付は、yyyy-mm-dd形式で記載する

**Comment by koukita** [comment]
陽性患者数、治療完了数の数値のカラムが両方「小計」なので、編集しているとどっちがどっちかわからなくなります。
間違いをなくすためにも、カラム名を「日陽性数」「日治療完了数」としたいです。いいでしょうか？

**Comment by koukita** [comment]
@Kanahiro わかりました、スクリプト側での対応が必要となるので、修正後であれば問題なしです！

**Comment by koukita** [comment]
日付と一緒に修正してODPに上げておきますので、確認をお願いします。
