### ISSUE TITLE
ステージ環境構築

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#21]

**Comment by daisuke-fukuda** [comment]
何もないのも困ると思うので、超超仮ですが作りました。

https://boring-shockley-101165.netlify.com/

forkした私のリポジトリのdevelopmentブランチ経由で反映していますので、私のforkリポジトリにmergeしないと反映されないです。

**Comment by daisuke-fukuda** [comment]
↑と同じものでよければ、仮のstaging環境として運用するのはいかがでしょうか？（さくらインターネットさんの環境が整うまで）

進行状態が見えた方が捗ると思いますので。


問題なければ、以下が可能なリポジトリの権限をいただきたいです。

- GitHubActionの有効化
- Netlifyからこのリポジトリを選択

もしくは、権限ある方が↓を対応いただければ、、
https://github.com/codeforsapporo/covid19/issues/19#issuecomment-595644229

**Comment by Yfuruchin** [comment]
CFSの@yuskesuzki さんと相談しまして@daisuke-fukuda さんにも権限付与inviteしました

**Comment by daisuke-fukuda** [comment]
やー、ありがとうございます。確認できました。

では、こちら着手いたしますね。

**Comment by watanavex** [comment]
自動でデプロイされた...感動❗️

**Comment by nobuh** [comment]
netlify 便利なので後ろ髪ひかれるところはありますが、さくらのクラウドでサーバー立てましたのでこちらにも記載しておきます。

git pull してるだけですので他のデプロイ環境と併用して頂くのも可能です

```
dev (dev-pages) http://133.242.52.161:58000/
staging (gh-pages) http://133.242.52.161:50080/
production (production) http://133.242.52.161/ ここは鈴木さんに stopcovid19.hokkaido.dev ドメインご提供頂いて、＋アクセラレーターで SSL 予定です
```

**Comment by daisuke-fukuda** [comment]
さくらのクラウド版が稼働しはじめたので、netlifyは落とします & このissueもクローズ。
