### ISSUE TITLE
サイドバーのpowerd by付近がごちゃごちゃしてる

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#212]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## スクリーンショット / Screenshot

<img width="336" alt="スクリーンショット 2020-03-11 19 21 34" src="https://user-images.githubusercontent.com/32258949/76406844-c43d0400-63cd-11ea-9108-64c1fee30c51.png">

## 期待する見せ方・挙動 / Expected behavior
* 仕切りの線とかあった方がよい？？
* Just道ITとさくらインターネットのログが同じくらいのサイズ感になってほしい
* さくらインターネットの左下に青い点が見える（link？）

**Comment by NEKOYASAN** [comment]
ちょっとやってみまーす

**Comment by tk-suzuki** [comment]
@Nekoya3 リンク追加するついででここ巻き取ってよいですか？
text-decorationとpadding でなおりそうなので。

**Comment by tk-suzuki** [comment]
やっちゃいます🙇

**Comment by NEKOYASAN** [comment]
申し訳ねっす…クローズします
