### ISSUE TITLE
本番同等の検証環境があるとうれしい

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#214]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* インフラ周りの設定変更をする時の検証環境が無い
* 本番とdev環境が同じサーバ
* 本番にのみアクセラレータが導入されている

## 期待する見せ方・挙動 / Expected behavior

案です。

* 本番と同じ設定のステージングサーバーを別で用意する
* ↑にはアクセラレータを設定する
* ↑は本番と同じproductionブランチを参照する（stagingブランチの運用してないので
* 念の為、dev環境も↑の新サーバに移行

**Comment by nobuh** [comment]
### 本番と同じproductionブランチを参照する

この点なんですが 本番も検証も production ブランチを参照している場合。この場合は本番のデプロイ（自己 pull であれ外からの push であれ）を止め、適用する操作手段が必要になると思います。管理ページのボタンであったり ChatOps のチャットであったり方法はいろいろありますが、人間の操作が必要だと。データの方は人が確認してのマージが必要になっているので、同じなのかもしれませんが、インフラ的にはさらに手動操作のいる方向は避けたいかなーという気も若干

### 検証環境とdev 環境を別サーバーにしてアクセラレーターもつける

これは技術的にも全然可能ですし、さくらについてきているドメインでよければドメイン購入とかも要らないですし、時間つくって準備したいと思いますー　ただ検証環境がどのブランチを実体化するのか、というところは要検討かなと。gh-pages あたりがいいかなーという気もしますねｗ

**Comment by daisuke-fukuda** [comment]
確認ありがとうございます〜。

> 本番と同じproductionブランチを参照する

前提として、インフラの変更をしたい時の検証環境、という事を念頭においておりましたので、今と同じく自動でデプロイされる方式で特に問題無いと考えておりました。（動いているコードは同じで、インフラ設定だけ変えて検証するイメージ）

具体的にどういった点が懸念でしたでしょうか？

**Comment by nobuh** [comment]
GitHub 上の production ブランチにデプロイされますと、本番にも検証にも、両方同時にデプロイされてしまうのでそこですねｗ　検証中はまだ本番反映したくない、そういうときも出てくるのではないかと。もし何か認識まちがってましたらご指摘くださいー

**Comment by daisuke-fukuda** [comment]
なるほど〜。そういう場合もありますね。

それに対応しようとした場合は、stagingブランチの運用をするようなイメージになって、それはそれで面倒かな〜と考えておりました。

**Comment by daisuke-fukuda** [comment]
![IMG20200312191201](https://user-images.githubusercontent.com/32258949/76510842-98855100-6495-11ea-88fe-426f1f3ed7e4.jpg)


汚い絵で恐縮ですが、右上の案1が、私がissueで書いていたイメージです。
シンプルに案2で良い気がしてきました。

**Comment by nobuh** [comment]
絵ありがとうございます！図だとわかりやすいですねw

ブランチ運用とデプロイ自動も現状と同じで、本番と同様インフラで検証も可能なので、案２の方ですすめさせてもらいますー

**Comment by nobuh** [comment]
- さくらのクラウドで最小 1CPU1G の dev サーバー 133.242.70.111 を立てました
- アクセス情報、公開鍵などは現状本番と IP 以外同じになっています
- dev のアクセラレーターはここ https://q7913g02.user.webaccel.jp/
- 覚えやすいように名前つけたいところ

**Comment by nobuh** [comment]
suzuki さんにご提供いただいたサブドメインをアクセラレーター付きの２台目の dev に設定して Lets Encrpt をつけました。

https://stopcovid19-dev.hokkaido.dev

です。↑でお伝えした https://q7913g02.user.webaccel.jp/ の方は停止しておきます

以上でほぼ達成しましたのでどなかた issue close お願いいたしますー

**Comment by NEKOYASAN** [comment]
クローズします！！！！
