### ISSUE TITLE
フロントから非同期でdata.jsonを分割したデータを見に行く実装検証

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#215]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

https://github.com/codeforsapporo/covid19/issues/154 から分岐

### 前提

* データの自動取得、更新まではできている
* 自動更新されたデータはここに自動コミットされる 
 * https://github.com/codeforsapporo/covid19hokkaido_scraping/tree/gh-pages
* ↑はGitHubPagesとして公開されているので、httpで取得可能

### やること

* vue.jsから、↑のGitHubPagesを非同期で参照し、グラフ化する実装をする

### まだやらないこと

* この対応を本番に適用する
* GitHubPagesを本番サーバー？にデプロイしたりする

自動で本番まで反映するには色々リスクが（要検討）あるので、このissueは下準備。

**Comment by Nekoya3** [comment]
https://github.com/Nekoya3/covid19-graphql

graphQLのサーバ一応できました(Getだけですが)...datasのjsonファイルが変更すると5秒以内にgraphQLから帰ってくるデータも変わります

**Comment by daisuke-fukuda** [comment]
revertしたのでreopen
