### ISSUE TITLE
SNS投稿ボタンがあるとうれしい？

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#220]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 期待する見せ方・挙動 / Expected behavior
* リンク + 思ったこと でツイートしてる人がけっこういるようなので

**Comment by yuya894** [comment]
東京都のサイトの方で対応中ですので、そちらを待ってcherry-pickがいいかもしれない？
https://github.com/tokyo-metropolitan-gov/covid19/issues/853
