### ISSUE TITLE
about/#dataへのリンクの修正

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#227]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 「データについて」がトップに来た状態に遷移しない
* 別windowで開いちゃう

**Comment by tk-suzuki** [comment]
- 別windowで開いちゃう
あ、たしかにこれ別で開いちゃダメですね。申し訳ないです
- データについてがトップに来た状態に遷移しない
あれ、行きませんか？
こっちの環境だとJavaScriptのロード完了後に「データについて」までスクロールダウンされてます。

**Comment by daisuke-fukuda** [comment]
確認ありがとうございます。

あれ？機種依存とかかな？
少々お待ちを。

**Comment by daisuke-fukuda** [comment]
![ae5787daf6661dec43ed5a45eb12f1c5](https://user-images.githubusercontent.com/32258949/76528779-ae563e80-64b4-11ea-8fd9-e82b1d98008f.gif)

以下の環境で再現しました。

Mac/Chrome
Mac/Safari
Android/Chrome
