### ISSUE TITLE
本家の追従ルールを決める

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#23]
本家の改修がすごいスピードなので、、、

文言系の修正も多いので、適当なタイミングで随時取り込みだと、北海道化した箇所が思いっきりコンフリクトしそうです。

**Comment by watanavex** [comment]
途中から追従を止める。というか、独自路線で完全に分岐しちゃうしかないかなっと思ってました😰
他の方の意見も聞いてみたいです👂

**Comment by daisuke-fukuda** [comment]
そうですね。
文言の北海道化をするタイミング以降は基本完全分岐で、以降は本家のPRを適当に眺めて、必要そうなものだけcherry-pickですかねぇ🤔
