### ISSUE TITLE
感染ルート(誰から誰に)感染したかの図

### ISSUE THREAD

**Issue by koala-88** [codeforsapporo/covid19#230]
- [ ] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
*感染ルート(誰から誰に)感染したかの流れが分からない(どのサイトにも言えますが)
(AさんからBさんに感染したetc)

## 期待する見せ方・挙動 / Expected behavior
*感染ルート( 例　名古屋FNN　https://www.fnn.jp/posts/10519THK)

**Comment by Yfuruchin** [comment]
提案ありがとうございます。
現在のデータはサイトにありますようにそれぞれの患者さんの位置や経路に関するデータは荒いです。
また、そんな荒いデータで経路を可視化できたとしても、どのような貢献が期待できるかわたしはちょっとわからないので、こんなことに使えるんじゃないか、といったアイデアをお教え頂けると幸いです。

**Comment by koala-88** [comment]
ご興味を持っていただきありがとうございます。

http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijoukyou.htm#No.5
上部にある「周囲の患者の発生」で繋がりを見ることはいかがでしょうか。

下部にあるそれぞれのPDFを開くと詳細表現はさらにありますが。

<img width="754" alt="スクリーンショット 2020-03-12 19 55 13" src="https://user-images.githubusercontent.com/62087735/76514595-7a225400-649b-11ea-8742-76f1ae7a3144.png">

**Comment by koukita** [comment]
私の個人的意見ですが、
このまとめサイトは、今の段階でのコロナウイルスの客観的な情報をわかりやすく紹介するものだと思っています。誰が誰に感染させたのかということは、今の段階で必要だとは思えません。
データはオープンデータになっているので、分析しようと思えばできなくはないでしょうが、このサイトではなく、別の研究などで行ってはどうでしょうか。
そもそも、陽性患者となってしまったはじめの人も、別の人からうつされた人たちですので、その人がまるで発生源のような図は、恣意的なものになってしまうように感じます。
このサイト作成に参加されている方たちの意見も聞いたほうがいいですが、反対の方がいるなら、掲載はしないほうがいいと私は考えます。

**Comment by koala-88** [comment]
感染ルートの流れを把握することこそが
これ以上の感染を防ぐために重要かと思いました。
数だけよりもルートの把握があると良いのかと。


ただ反対が多ければやめれば良いのは同意です。

**Comment by Yfuruchin** [comment]
@koala-88 ありがとうございます、やり方はわかりました。
その経路の可視化でどのような貢献が得られるとお考えでしょうか？

**Comment by koala-88** [comment]
この前のコメントと同じタイミングで投稿されたかもしれないので短文にしますが、
感染ルートの流れを断つことです。

データは既に記述されているデータ以上に作成しようとは考えていません。

**Comment by koala-88** [comment]
ただ反対が多ければやめてください。

**Comment by koala-88** [comment]
他例だと海外事例で、見せ方は見づらいかもしれませんが、

https://www.straitstimes.com/singapore/grace-assembly-coronavirus-mystery-solved-mega-cluster-linked-to-2-wuhan-tourists-via-a
https://nextstrain.org/ncov?r=location (ゲノム)
特に上部リンクの図は流れがわかるかなと。

議論をしていただきありがとうございました。

**Comment by koukita** [comment]
あわかりだと思いますが、提案自体を否定しているわけではありません。
サイトに参加されている方々は並列ですので、自由な意見が必要です。
色んな意見がサイトを良くしていくと思います。
今後もお知恵をお貸しください。

**Comment by koala-88** [comment]
自由な意見とのことありがとうございます。

今回はこのサイトで反対意見の方もいらっしゃるかもしれないので、
このIssueを取り下げようと思います。

**Comment by tk-suzuki** [comment]
現在公開されている移動情報や位置情報は、個人情報や地域の混乱に配慮して情報をぼかしたあとの加工済みデータであり、それをもとに情報を導き出したとしても、不正確（ともすれば誤った）結果が可視化されることになります。

感染経路を可視化することは防疫の観点から大切なことではありますが、私の個人的な考えを言いますと、それが意味を持つのは取るべき対策の規模に対して十分な細かさの情報の粒度と情報量があり、かつ断定可能な情報が既に一定量得られる環境があってのものだと考えます（そういう意味では、全世界規模での感染ルートなどについては不確定情報をノイズとして排除したとしてもある程度のデータ量が揃いつつあるように思います）。
今回の場合ですと、私達は加工済みデータを得て個人情報に触れない範囲の可視化をすることしかできませんし、北海道内という狭いエリアのデータを可視化しているのに対し、得られる地理情報は必要な細かさを持っていません。また、あまりに接触者が不明な人が多く、可視化に耐えうるだけの感染者数も確定した濃厚接触者の関連付けも得られないと考えています。

この状況で感染ルートをマップ化するのは、データの読み方に不慣れな方がデマ情報を流布する一助にこそなれ、正しい分析に資するだけの経路情報をつくることにはならないと考えます。

取り下げるとご本人がお書きになったあとに付け加える形になり申し訳ないです。

**Comment by NEKOYASAN** [comment]
issueを取り下げるとのことですのでcloseいたします
ご意見ありがとうございました！
