### ISSUE TITLE
データのkeyは生データに準拠すべきでは？

### ISSUE THREAD

**Issue by Kanahiro** [codeforsapporo/covid19#231]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
- ある時点から、フロント側もデータも、使用するカラムの日本語keyを全て英字keyに切り替えた
- その時点ではウェブサイトからスクレイピングしたデータを利用していた
- 現在はオープンデータポータルやDATA SMART CITY SAPPOROからCSVデータを取得している
- CSVデータは日本語keyであり、道・札幌市の作業性からして妥当
- jsonデータの生成時に、読み込んだCSVデータの日本語keyを英字keyにtranslationしている
- このtranslationは、「あいうえお」というkeyを常に「abcde」と変換するようなもの
- なので、CSVデータに（何かの間違いで）カラムが追加され、それが偶然translationの対象になると予期せぬ動きをする可能性がある

## 期待する見せ方・挙動 / Expected behavior
- フロント側のkeyをCSVデータに準拠させては（日本語keyに戻しては）？

これは、日本語keyを排除するメリットがわからないための提案です。もしJavaScriptの仕様上の不都合などが想定される場合は、英字へのtranslationは必要と考えます。

たとえ日本語keyに戻ったとしても、多少translationする必要はありますが、対象件数が減り、前述の予期せぬ動作のリスクは大幅に減ると考えます。

また蛇足ですが、現在は以下のsampleのとおりkeyに日本語英字が混在しています（必要な分だけtranslationしているため使われないデータのkeyは生データのまま）。なのでもし今後データを再配布するようになったとして、利用側はかなり使いにくいのではないかと思われます。

>  {
            "no": "79",
            "date": "2020-03-03T00:00",
            "曜日": "",
            "place": "札幌市",
            "age": "60代",
            "sex": "女性",
            "属性": "会社員",
            "備考": "軽症　会話可",
            "補足": "",
            "退院": "",
            "周囲の状況": "No.70No.84No.85 No.97No.98No.110 No.111",
            "濃厚接触者の状況": "札幌市公表中"
        },

**Comment by NEKOYASAN** [comment]
私がkeyを英語に変更したのは

1. 私的に文字コードが変わった際に簡単にkeyが文字化けするという状況のままだと扱いやすいと言えるのかな？ということ
2. 今後もし、日本人以外が利用することがあればkeyだけでも英語のほうが直感的に何のデータかわかりやすいかな？ということ
3. 個人的にjsonのkeyなどの変数名にあたる部分にマルチバイト文字が用いられていることがあまり好ましく感じないため

という感じです
ECMAScriptとしても問題ないとされているためjavascriptでは問題は発生しないかと思いますので、戻してもフロント側の修正を同時に行えば問題ないと思います。

追記:
小計が日陽性数などに変更されている関係からフロント側の変更に気を付ける必要がありますね

**Comment by Kanahiro** [comment]
スクレイピングとかの頃は、keyは（ある意味）開発側で決めるようなものだったので今後使いやすいkeyにしても良いなとは思っていたんですが、生データが存在する以上、なるべくそのkeyに準拠させたいなと考えた次第です。

ですが

> 今後もし、日本人以外が利用することがあればkeyだけでも英語のほうが直感的に何のデータかわかりやすいかな？ということ

ここは想定外でした。確かに多言語対応の路線は捨ててはいけない気がします。
ただ英語だけでなく中国語なども同じように対応しようとすると、日本語のjsonを各言語に別途翻訳する仕組みにした方が良いかもしれません。

いずれにせよ、急を要する修正ではありませんが、CSV準拠のkeyへ修正するという事でよろしいですか？

**Comment by NEKOYASAN** [comment]
了解しました。CSVのkeyに戻すのであればそれでも大丈夫です。
グラフへのコンバートの部分の大幅な書き換えが必要なため少しお時間をいただいてもよろしいでしょうか？
また、CSVのキーが少しでも変わった場合Web側の表示ができない可能性が高いためキーが変更されてしまった際のアラートを早急に実装する必要があるかと思います。

**Comment by Kanahiro** [comment]
> また、CSVのキーが少しでも変わった場合Web側の表示ができない可能性が高いためキーが変更されてしまった際のアラートを早急に実装する必要があるかと思います。

完全自動化には上記が絶対に必要ですね。ただ実装には少し時間がかかるかと思います。
なので、ひとまず方向が定まったという事で、お互い焦らずやっていきましょう:)

**Comment by NEKOYASAN** [comment]
>グラフへのコンバートの部分の大幅な書き換えが必要なため少しお時間をいただいてもよろしいでしょうか？

これの理由としてはこれまでsubtotalに統一されていたのが「日陽性数」、「日治療終了数」、「日検査数」、「小計」に分かれてしまっているためそれに応じての処理に変更するためです...
申し訳ないですがお時間ください....

**Comment by Kanahiro** [comment]
その点ですが、おっしゃるとおりフロント側の修正が大きいと想定していた事もあり、すべてが日本語keyになっても、ある程度translationの必要はあるかな、と考えています。
たとえば、「日陽性数」、「日治療終了数」、「日検査数」をすべて「小計」に変換しておけば良いなと考えていました。

これまでは「性別」や「年代」など抽象的な単語が変換対象となっており、かつ、変換対象件数が多かったのでリスクが高いなと思っていました。
しかし、変換対象件数が減り、かつ、個別具体的な単語になるため、translationしてもはるかに安全と考えます。

なので、ひとまずフロント側はsubtotalから小計に戻す、程度にしませんか？

**Comment by NEKOYASAN** [comment]
わかりました...
結果的にtranslationするのであれば同じでは...?と思ってしまうのですが...
確実性がそちらの方が高いのであればそうしましょう。
すべて小計であればフロントの変更も小さく済みます。

**Comment by Kanahiro** [comment]
> 結果的にtranslationするのであれば同じでは...?と思ってしまうのですが...

おっしゃるとおりですw
ただただ、formatGraph.tsの修正が大変そうなのと、コードが複雑になっていきそうだなーという個人的な予感ですｗ
ちなみに修正いけそうです？急ぎの修正ではないのでゆっくりで大丈夫ですし、そうしましょうか:)

**Comment by NEKOYASAN** [comment]
「小計」への修正自体はかなり早くできるとは思います。
「日陽性数」、「日治療終了数」、「日検査数」への変更はformatGraph.tsの修正は多分結構な量になるかとは思いますｗ

**Comment by NEKOYASAN** [comment]
これは自分の考えなのですが
サーバ側で処理を分けてエラーが出たら修正する方がキーが変更されてからフロント側を修正するよりも楽かなーって思ってたのでkeyを英語に変換してたりもありました。
うーん日本語のままと英語に変換するのどっちもどっちって感じですかね...わからない..w

**Comment by Kanahiro** [comment]
ですよねーｗ
たぶん各々の考え方次第だと思うので、ひとまず継続検討案件としておきましょう（有識者が天啓を授けてくれるかも…）。
ご意見ありがとうございます:)

**Comment by NEKOYASAN** [comment]
そうですねいったんいろんな人の意見聞くべきですね....

**Comment by daisuke-fukuda** [comment]
興味深い議論ですね！私の意見としては

> 1. 私的に文字コードが変わった際に簡単にkeyが文字化けするという状況のままだと扱いやすいと言えるのかな？ということ

文字コードが変わった場合、valueも化けてしまうため、この点に優位性は無いと考えます。


> 2. 今後もし、日本人以外が利用することがあればkeyだけでも英語のほうが直感的に何のデータかわかりやすいかな？ということ

これはありますね。
今、良い感じにデータ作成処理とWebでリポジトリと処理がわかれています。

データが英語keyで統一されていれば、日本人以外の方が参画される時にWeb側はなんとかなる、というメリットがあります。


> 3. 個人的にjsonのkeyなどの変数名にあたる部分にマルチバイト文字が用いられていることがあまり好ましく感じないため

気持ちはわかりますw
が、ローマ字のkey（YouseiKanjaSuu）みたいなのを良しとするか、みたいな議論もあって、明確な正解は無いと考えます。（宗教論に近い）

このプロジェクトでは、扱っているkeyの意味合いが若干難しい場合があるので、日本語のままの方がわかりやすい気がします。（濃厚接触者の状況のわかりやすい英語とか思いつかない）

======================================-

まとめると、

-  2についてはメリットがあります
  - が、今の処i18n対応の目処もついてないため、強い動機にはなっていない
- 逆にそこまで重要で無いならシンプルにした方が良い
  - が、また戻すかもしれないし、工数もかかるから、今そこまで積極的にやるものでは無いかな〜

結論、私の意見としては今のところはどっちでも良い！です。


ご参考までに〜

**Comment by Kanahiro** [comment]
ご意見ありがとうございます。
現状動作してますし、バリデーションの処理でkeyの取り扱い方も変わるかもしれません。その中急いで修正を要するものでもないですね。

ということで現状維持とします、みなさまありがとうございました😃

**Comment by NEKOYASAN** [comment]
一晩寝ながらですが考え直すと英語のkeyに直す利点のほうが少なく感じていまして、現在英語に直す必要性が特にないと考えています（英語に直した人が何言ってんだというのはお許しください...）
ということでフロント側を日本語のkeyに対応させたバージョンを今日中には別branchのほうにpushしておこうかと思いますので、時間のあるときで大丈夫ですのでjsonへパースするほうもtranslateの処理を外したものをPRに上げておいていただけますとありがたいです。
また、「日陽性数」、「日治療終了数」、「日検査数」を「小計」に直さなくて大丈夫です！（フロント側で対応してしまいます）

昨日といっていることが真逆になっていることをお許しください。
よろしくお願いします！

**Comment by Kanahiro** [comment]
スクリプトの方PR上げてありますので:)

**Comment by NEKOYASAN** [comment]
フロントと同時にmargeしますね！
