### ISSUE TITLE
What's newのところ削除した方が良い？

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#239]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 3/9から更新されていない（手動で変更しないと更新されない
* 更新する予定もない

## 期待する見せ方・挙動 / Expected behavior
- 特に運用しないなら、今のリンクは別箇所で表示して、What’s newは消しちゃって良い気がしてきました

**Comment by NEKOYASAN** [comment]
運用予定がないなら削除が一番いいと思います！！！

**Comment by koukita** [comment]
「北海道発表の最新情報はコチラ」
とかに変えて、日付とかは削除でいいかと思います

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/76585419-aa143a80-6521-11ea-9fd9-b1f832b9cccb.png)
こんな感じでいかがでしょうか！！！

**Comment by koukita** [comment]
いいですね
