### ISSUE TITLE
GitHubとSlackの連携をいれたい

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#24]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* GitHubからの通知がメールベースなので気がつくのが

## スクリーンショット / Screenshot

本家のスクショ
<img width="560" alt="スクリーンショット 2020-03-06 13 30 19" src="https://user-images.githubusercontent.com/32258949/76051599-a5460880-5fae-11ea-8149-2a8ee3258739.png">
です

## 期待する見せ方・挙動 / Expected behavior
* GitHub側で更新があると、Slackに通知される
* ので、Slackを見ているだけで状況がなんとなく把握できる

**Comment by watanavex** [comment]
テスト

**Comment by watanavex** [comment]
slack通知テスト

**Comment by watanavex** [comment]
slack通知テスト

**Comment by watanavex** [comment]
連携できたので閉じます！
