### ISSUE TITLE
現在患者数に補足があるとうれしい

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#241]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 導出方法が書いていないので、誤解を招く可能性がある

## 期待する見せ方・挙動 / Expected behavior
* 陽性患者数 - 治療終了者数 - 死亡者数 = 現在患者数  という事がわかるようにする

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/76587292-bcdd3e00-6526-11ea-8c4a-ba1929ac1af5.png)
いっそのことこれ出しちゃいます？

**Comment by Yfuruchin** [comment]
たしかに。本家もトップこれなんですよね
![image](https://user-images.githubusercontent.com/4961152/76587371-fc0b8f00-6526-11ea-8617-d4a0a93b57d8.png)

**Comment by NEKOYASAN** [comment]
assignしますね

**Comment by daisuke-fukuda** [comment]
元々svgでメンテがきついから非表示にしたやつですね。

本家は脱SVG化すすめてたはずですが、、

**Comment by koukita** [comment]
テキストだけでも、今日のデータを出せばいいんではないかな

検査数累計　1234(+2)
陽性患者数累計　123(+4)
治療終了数累計　123(+3)
死亡累計　4(+1)
現在患者数　123(-3)
　　うち軽症・中等症　120(+3)
　　　　重症　3(0)

という感じ
数字は適当です

**Comment by Yfuruchin** [comment]
東京版SVG2HTML化ここが参照になるかも
https://github.com/tokyo-metropolitan-gov/covid19/issues/860

**Comment by koukita** [comment]
もし数字を自動的に計算する場合は、陽性患者数とその他の数字の発表時間が違うことも考慮する必要もあります。
陽性患者数の更新は当日の夕方18時くらい、その他は翌日の10時くらいですので、その間は、計算が合わないことになります。
計算が合う日にちで計算するか、補足説明を付けるか、検討が必要です

**Comment by NEKOYASAN** [comment]
現状
表での表示については完成済み
更新の面倒さについてはpropsで定義してるのでそんなにめんどくさくはなくしてます

現状困ってること
データの更新時間が異なるため同じ日のデータを持ってくるための方法を考えなきゃならぬ
データに小計のみなので累計を計算する必要がある（フロント、バックどちらか）

**Comment by takehirock** [comment]
逆Lあり、ただし治療終了者数を一番上に表示したい　ポジなデータを前にしたいという希望

**Comment by daisuke-fukuda** [comment]
まず、そもそもの始まりは、

「陽性患者数 - 治療終了者数 - 死亡者数 = 現在患者数」

という事がわかるようにするというのがこのissueの趣旨です。

# 逆Lのグラフで現在患者数の説明になるか

で、逆Lのグラフでそれがわかるかというと、

- 概念的には正しい
- が、データの更新タイミングの問題で、数字がずれる事がある
 
という現状から、私はわかりやすくは無いと考えます。（返って混乱する場合がある）

単純に、「陽性患者数 - 治療終了者数 - 死亡者数 = 現在患者数」という旨の補足テキストを入れるのが、現状では良いのでは、という意見です。


# 逆Lのグラフを表示するかどうか

逆Lのグラフ自体は、北海道がほぼこのままの形式で公式に表示している事から、表示する事による誤解は発生しにくく、強く反対する理由はありません。

一方で、このグラフっぽいものは「グラフっぽく描画しているが、棒グラフの高さは数字を表現していない」という代物なので、積極的に前に押し出すものでは無いと思います。

プラスで、データを自動取得できる環境も整っていません。


以上から、

1. 諸々（ここは検討）整うまでは非表示
2. 数字を抜いて、概念の説明的にどこかにおいておく
3. 下の方にしれっと表示（数字は手動更新）


のいずれかが良いと思います。

（1 > 2 > 3の順番で私が良いと思う順です）

**Comment by NEKOYASAN** [comment]
あの...ですね...とても申し上げずらいのですが...これ、グラフではなくテーブルなんです....
なのでL時になっている部分はこの中がこれに含まれるよーの意味合いでしかないです....
確かに表には見えないかもですね..

**Comment by NEKOYASAN** [comment]
> プラスで、データを自動取得できる環境も整っていません。

これについては解消いたしました！

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/76621691-592d3200-6573-11ea-9041-738576439fb6.png)
現在患者数の補足に「現在患者数とは陽性患者数のうち、治療終了者数と死亡者数を除いた人数です。なお、ご覧いただいている時間によってはデータ更新の関係上累計表示されている日付がずれており数値があわないことがあります。」と記述しました

**Comment by koukita** [comment]
@Nekoya3 ありがとうございます。
「現在患者数とは、陽性患者数から治療終了者数と死亡者数を除いた人数です。なお、ご覧いただいている時間によっては累計されている日付が違う場合がありますのでご注意ください。死亡者数は北海道のホームページを参照してください。」
ではどうでしょうか？

**Comment by NEKOYASAN** [comment]
いいですね！そちらにしましょう！

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/76622746-6ba86b00-6575-11ea-8479-69f8411e2fac.png)
変更したバージョンをすでにプッシュしてありますが見た目としてはこうなりますー

**Comment by NEKOYASAN** [comment]
これについては解決したのでクローズします。
検査陽性者の状況については別issueで
