### ISSUE TITLE
メインビジュアルの「あの子」に名前をつける

### ISSUE THREAD

**Issue by ymgt-design** [codeforsapporo/covid19#245]
- [x] 提案

## 起こっている問題 / Occurred problem
* メインビジュアルの「あの子」についに名前を

## スクリーンショット / Screenshot
![coro](https://user-images.githubusercontent.com/61897769/76606783-3ccecc80-6556-11ea-8f32-b75bfb6166bd.jpg)

なお、投票についてはSlack内にて実施します。

**Comment by ymgt-design** [comment]
- ドォウ
- イク
- ミッチ
- ミッツ
の4案もしくは自薦があればそれも

**Comment by daisuke-fukuda** [comment]
作者のKITOTANさんのご意見をまずは聞きたいです！

**Comment by ymgt-design** [comment]
KITOTANさんの意見も入っていますのであくまでフラットな状態にしていますー!

**Comment by daisuke-fukuda** [comment]
了解しました！

**Comment by NEKOYASAN** [comment]
https://codeforsapporo.slack.com/archives/CUJ8DH9DY/p1584091363079600
