### ISSUE TITLE
スマホでWhat's newだったところの改行がすれてる

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#259]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* アイコンと本文の間に謎の改行が

## スクリーンショット / Screenshot

<img width="286" alt="スクリーンショット 2020-03-14 19 42 45" src="https://user-images.githubusercontent.com/32258949/76680472-0bc0cb80-662c-11ea-8b03-f5fea897b9b4.png">

**Comment by NEKOYASAN** [comment]
たぶん元日付があったのでその分の改行かと。
StaticInfoに、変更するのも手だと思いますー

**Comment by daisuke-fukuda** [comment]
やります
