### ISSUE TITLE
ロンチまでのマストissueをまとめる

### ISSUE THREAD

**Issue by takehirock** [codeforsapporo/covid19#26]
ここまで揃ったら出しちゃおうみたいなマストissueの洗い出しと優先度

**Comment by watanavex** [comment]
東京都のページでグラフ表示されている情報4つ
- 陽性患者数
- 陽性患者の属性
- 新型コロナコールセンター相談件数
- 帰国者・接触者電話相談センター相談件数

これらのうち、
- 新型コロナコールセンター相談件数
- 帰国者・接触者電話相談センター相談件数

この2つは道が提供していないため、初回ローンチではドロップの方向かと思います。

https://github.com/codeforsapporo/covid19/issues/12#issuecomment-595633736
> おそらく公表はされない（する余裕がなさそう）なので、相談件数は非表示でもよいかもしれない

https://github.com/codeforsapporo/covid19/issues/11#issuecomment-595623012
> 相談件数は（2020-03-06現在では）道では公開していないので、提供をお願いする、あるいは機能をスポイルする必要があるかもしれない。

**Comment by Yfuruchin** [comment]
＋１

**Comment by watanavex** [comment]
現時点で #41 #61 だけはマスト、それ以外は後回しでもいいかなと思いますが
どうでしょう？

**Comment by ymgt-design** [comment]
#41は完了、#61は v1にするので、本件はクローズします
