### ISSUE TITLE
サイト情報の取りまとめ

### ISSUE THREAD

**Issue by takehirock** [codeforsapporo/covid19#27]
以下、どこまで、なにを決める（掲載する、しないも含めて）
ドメイン
名義
privacy policy
問合せ（フォーム、メール、電話）

**Comment by tk-suzuki** [comment]
https://github.com/codeforsapporo/covid19/blob/development/pages/about.vue
> 新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、東京都が開設したもの

新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、[東京都 新型コロナウイルス感染症対策サイト](https://github.com/tokyo-metropolitan-gov/covid19)をフォークして[Code for Sapporo](https://www.codeforsapporo.org/)が開設したもの

という感じですかね（他のAuthorなどの情報についてもCode for Sapporoという感じ？）

**Comment by watanavex** [comment]
Slackの過去のやりとりより。
> コピーライトはプロジェクトの性格上明記しなくてもよいと思います、あとで必要になったらなんか足しますか

https://codeforsapporo.slack.com/archives/CUJ8DH9DY/p1583449659141900

**Comment by tk-suzuki** [comment]
では、現時点では

新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、[東京都 新型コロナウイルス感染症対策サイト](https://github.com/tokyo-metropolitan-gov/covid19)をフォークしたもの

とだけ書く感じにしますか。

**Comment by daisuke-fukuda** [comment]
ドメインはこっちで対応
https://github.com/codeforsapporo/covid19/issues/36

**Comment by ymgt-design** [comment]
aboutでは問合せ先が「お問い合わせ先は現時点では表示しない」としてますが、それこそなにかあったときのためにでも、先ほど立ち上がったFBページへのリンクを掲載しておくのはいかがでしょうか。
それが完了すればここはおわりかな？
