### ISSUE TITLE
道内のコロナ情報リンクのとりまとめ

### ISSUE THREAD

**Issue by takehirock** [codeforsapporo/covid19#28]
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
*道民向けの有益なコロナ情報
*道や市への問合せリンク等

**Comment by Yfuruchin** [comment]
https://github.com/codeforsapporo/covid19/pull/25
ここで実装済みかも（確認おねがいします

**Comment by watanavex** [comment]
#25 ここでは、東京都サイトの外部リンク先 (都の情報) を道の内容の近いものに置き換えました！

**Comment by takehirock** [comment]
わー、ごめんなさい　closeしますね
