### ISSUE TITLE
ESLintをなんとかしたい

### ISSUE THREAD

**Issue by NEKOYASAN** [codeforsapporo/covid19#283]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* ESLintをあまり利用できていない（コーディング規約がないため？）

## 期待する見せ方・挙動 / Expected behavior
* ESLintをしっかりと利用できるようにしたい

## 起こっている問題の再現手段 / Steps to reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
*

**Comment by daisuke-fukuda** [comment]
本家の修正まとめ

https://github.com/tokyo-metropolitan-gov/covid19/issues/507
https://github.com/tokyo-metropolitan-gov/covid19/issues/594
https://github.com/tokyo-metropolitan-gov/covid19/issues/750
https://github.com/tokyo-metropolitan-gov/covid19/issues/1600
https://github.com/tokyo-metropolitan-gov/covid19/pull/381
https://github.com/tokyo-metropolitan-gov/covid19/pull/597
https://github.com/tokyo-metropolitan-gov/covid19/pull/620
https://github.com/tokyo-metropolitan-gov/covid19/pull/650
https://github.com/tokyo-metropolitan-gov/covid19/pull/752
https://github.com/tokyo-metropolitan-gov/covid19/pull/772
https://github.com/tokyo-metropolitan-gov/covid19/pull/1128
https://github.com/tokyo-metropolitan-gov/covid19/pull/1700

多い・・

**Comment by NEKOYASAN** [comment]
ESLint、Prettier周りは緩めでもコーディング規約決めないと設定大変そう…
