### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」を汎用的な情報へのリンクに置き換える

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#30]
## 起こっている問題 / Occurred problem
https://stopcovid19.metro.tokyo.lg.jp/flow
このページのコンテンツの北海道化が難しい。
よって、汎用的な厚労省の情報などの外部リンクへ飛ばす。

## 期待する見せ方・挙動 / Expected behavior
この辺のリンクに飛ばす
* http://www.pref.hokkaido.lg.jp/file.jsp?id=1270153
*  https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/dengue_fever_qa_00001.html#Q28

**Comment by yk-lab** [comment]
外国人旅行者向けコールセンターの情報を見つけたので共有します！
https://www.city.sapporo.jp/hokenjo/f1kansen/2019n-cov.html

**Comment by watanavex** [comment]
@howml すいません、
2902c0f2c2cd8b2ddf88f326f878d55a9d623b19
これちょっと意図が違いました💦

ここで議論してたんですが、
https://codeforsapporo.slack.com/archives/CUJ8DH9DY/p1583482951282900
「新型コロナウイルス感染症が心配なときに」をクリックしたら、
@yk-lab さんが上で貼ってくれたリンクに
https://www.city.sapporo.jp/hokenjo/f1kansen/2019n-cov.html
直で飛んじゃう感じが良いと思います❗️

**Comment by Yfuruchin** [comment]
v1以降になるかもですが、東京版ではflowのHTML化を進めているのでv1などで差し替え（＋翻訳？）という手法もありかと
https://github.com/tokyo-metropolitan-gov/covid19/issues/659

**Comment by watanavex** [comment]
以降は #45 にて。
