### ISSUE TITLE
API仕様をOpenAPIで公開する

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#301]
- [ ] バグ / Bug
- [*] 改善提案 / Suggestions for improvement

## 期待する見せ方・挙動 / Expected behavior
案として、
* Swagger-UIでAPI仕様を公開する
* github pagesでホスティングする

**Comment by watanavex** [comment]
`covid19hokkaido_scraping` のgh-pagesはもう使ってしまっているので、
`codeforsappor` でホスティングするか...
新規にリポジトリ作っちゃった方がいいかな🙄

**Comment by watanavex** [comment]
Swagger-UIじゃなくてこの辺でもいいかも
https://redocly.github.io/redoc

**Comment by takayuki-fuwa** [comment]
試しにこんな感じでswaggerに起こしてみましたけど、いかがでしょう？
https://github.com/yuesan/covid19hokkaido_webapi/blob/master/swagger.yaml

**Comment by watanavex** [comment]
@yuesan いい感じだと思います！ありがとうございます！

**Comment by watanavex** [comment]
@Kanahiro `covid19hokkaido_scraping` ここに index.htmlとリファレンスになるyamlを置いて一緒に公開するのってどう思います？
ごちゃつくので避けた方がいいですかね？

**Comment by watanavex** [comment]
これでAPI公開する場合、htmlファイル1個とyamlだけでいけちゃいます。
https://redocly.github.io/redoc

**Comment by Kanahiro** [comment]
gh-pagesでホスティングしたら見やすいのかなと思うので、別リポジトリでgh-pagesを使うのがよいと思います。なんならc4s.io使っちゃうとかはどうなんですかね。

**Comment by Kanahiro** [comment]
ただSwaggerというものに詳しくないため、お任せになってしまうかなと…🤔

**Comment by watanavex** [comment]
@Kanahiro ありがとうございます！
では一旦、別リポジトリ作ってやってみます！

**Comment by watanavex** [comment]
@yuesan codeforsapporoにforkしました！

**Comment by takayuki-fuwa** [comment]
https://github.com/codeforsapporo/covid19hokkaido_scraping/tree/gh-pages
にあったJSONファイルを基に、一通りOpenAPI定義に起こしてみました。
また、yamlファイル名を`swagger.yaml`としていたのですが、swagger-uiに限らず使えるので、`webapi.yaml`とリネームしました。

https://github.com/yuesan/covid19hokkaido_webapi/blob/master/webapi.yaml

**Comment by watanavex** [comment]
https://codeforsapporo.github.io/covid19hokkaido_webapi/
暫定で公開済み。

詳細は別issueで修正していく。
