### ISSUE TITLE
ODPのCSVのファイル数削減へ向けた対応

### ISSUE THREAD

**Issue by Kanahiro** [codeforsapporo/covid19#309]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
- 従来は「1CSV:1JSON」だったが、これだとCSVファイルが5つ必要になる。ファイルが多い事ははデータ更新担当者の作業性に悪影響を与える
- すでに[ODP](https://www.harp.lg.jp/opendata/dataset/1369.html)には、covid19_data.csvというデータが統合されたCSVデータがアップロードされている
- これを用いて「1CSV:nJSON」にすれば、ODPのCSVファイルは2つにまで削減可能

## 今後について
- covid19hokkaido_scrapingに、[上記に関するPR](https://github.com/codeforsapporo/covid19hokkaido_scraping/pull/15)を方針と共に上げてあります

## 統合後のCSV:JSON対照表
|  json  |  source  | file  |
| ---- | ---- | ---- |
|  last_update  | 実行時刻から生成 |  -  |
|  main_summary  | 北海道オープンデータポータル |  covid19_data.csv |
|  patients  | 北海道オープンデータポータル |  patients.csv |
|  patients_summary  | 北海道オープンデータポータル |  covid19_data.csv |
|  current_patients  | 北海道オープンデータポータル |  covid19_data.csv |
|  discharges_summary  | 北海道オープンデータポータル |  covid19_data.csv |
|  inspections  | 北海道オープンデータポータル |  covid19_data.csv |
|  contacts  | DATA SMART CITY SAPPORO |  contacts.csv  |
|  querents  | DATA SMART CITY SAPPORO |  querents.csv  |

**Comment by NEKOYASAN** [comment]
対応終了に伴いクローズします
