### ISSUE TITLE
札幌市データの取り扱い

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#31]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 札幌市さんからデータが来たので、サイトにどう取り込むか
* 更新をどうする

## 期待する見せ方・挙動 / Expected behavior
* サイトを２つ作ってもねじれのもとになるので、「札幌市」ウインドウを追加する？

**Comment by Yfuruchin** [comment]
とりあえず仮想フォルダに札幌市データを追加
https://github.com/codeforsapporo/covid19/tree/development/data/sapporo

CCBYライセンス

**Comment by tk-suzuki** [comment]
### 案

1. タブみたいなかたちで北海道と札幌市の表示を切り替えられるようにする
2. 北海道と札幌市のデータをワンページにタイリングしちゃう
3. グラフ内に重ねて配置してしまう

**Comment by Yfuruchin** [comment]
実装的には2が最短かなとおもいますがいかがでしょう。１と３は追々でもよいかも

**Comment by watanavex** [comment]
札幌市のデータって、定期的に新しいものが頂けそうな感じでしたっけ？
Slackで流れたような。。。

**Comment by Yfuruchin** [comment]
はい、札幌市ICT担当さんがこさえてくれる筈なのでオーダーだします。可能なら直接PRしてもらってもよいかも

**Comment by Yfuruchin** [comment]
札幌市ICT小笠原さんよりSlackでリアクション
https://codeforsapporo.slack.com/archives/CUKTK3R4K/p1583566661121800
>Q.定期的に提供されるのか？
>A.手作業なので不定期になると思いますが、出来る限り速やかにデータ更新しようと思っています。
次回は3/9を予定

**Comment by NEKOYASAN** [comment]
#43 にて自動更新をCKANから行うことで解決しましたのでclose
