### ISSUE TITLE
翻訳関係をTransifexに移行

### ISSUE THREAD

**Issue by NEKOYASAN** [codeforsapporo/covid19#310]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* Google Sheetsで翻訳関係を管理してるため少しごっちゃりしてしまっている

## 期待する見せ方・挙動 / Expected behavior
* Transifexへの移行を行う

**Comment by daisuke-fukuda** [comment]
Transifexはちょっと導入コストがかかる（翻訳する人が、Transifexの使い方を覚えないといけない）と噂を効きました

**Comment by NEKOYASAN** [comment]
そうなんですよね....東京版でDocsの整備が進んでるようなので少しずつ移行に手を付けていければなという感じですね

**Comment by daisuke-fukuda** [comment]
実際に翻訳している方がやりやすい方が良いと思います！

**Comment by Yfuruchin** [comment]
FYIですがTransifexによる貢献のやりかたはここにまとまっています
https://qiita.com/iten/items/1274f3b85e11261f3b5c

難しいですね、弊チームのリソースを勘案しつつ
[参加のしやすさ]と[システム的対応のやりやすさ]
のトレードオフになりますね、

**Comment by NEKOYASAN** [comment]
移行終了によりclose
