### ISSUE TITLE
AM3時くらいにエラー通知が来る

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#326]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* メンテによるものとのこと

## 期待する見せ方・挙動 / Expected behavior

* AM3時はデータ取得処理を実行しないように調整すれば良さそう

## 起こっている問題の再現手段 / Steps to reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
*

**Comment by NEKOYASAN** [comment]
https://github.com/codeforsapporo/covid19hokkaido_scraping/pull/19

こちらで対処済み

**Comment by daisuke-fukuda** [comment]
@Nekoya3 多分UTCだと思うんですよね、、、

**Comment by NEKOYASAN** [comment]
あ............

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/77894245-f8f6f980-72af-11ea-9185-58d0f24bae78.png)
ですねー....修正しますー..

**Comment by NEKOYASAN** [comment]
https://github.com/codeforsapporo/covid19hokkaido_scraping/pull/20

あってます..かね？
朝の３時は１８時..?
