### ISSUE TITLE
北海道の発生地図を作成したい

### ISSUE THREAD

**Issue by koukita** [codeforsapporo/covid19#33]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 北海道の感染者の居住地の地図を作成したい
* Leafletで作成
* /data/admini_point.csv　に全国の市役所役場のポイントデータが有り

## 期待する見せ方・挙動 / Expected behavior
* 感染者が追加されたら、居住地情報から緯度経度を結合し、ポイントを追加
* 感染者の数は、クラスタリングで表示。クリックで詳細表示

**Comment by koukita** [comment]
Leafletで地図は作成しましたが、こちらにPull requestおくるとき、特定の変更のみおくることって可能ですか？

**Comment by Yfuruchin** [comment]
実装については未決なので、まずはご自分のリポジトリに置いておくのはどうでしょう？

**Comment by koukita** [comment]
それでいいですか。そうしておきます。
[https://github.com/koukita/covid19/tree/development/map](https://github.com/koukita/covid19/tree/development/map)

**Comment by koukita** [comment]
テストサイト
[http://kouapp.main.jp/maps/COVID19/](http://kouapp.main.jp/maps/COVID19/)
こうしたらいいとかあればぜひお願いします。

あまり詳細にズームしないほうがいいと思い、最大ズームレベルは９

**Comment by koukita** [comment]
3月7日のデータに更新しました。
[https://github.com/koukita/covid19/tree/development/map](https://github.com/koukita/covid19/tree/development/map)

[http://kouapp.main.jp/maps/COVID19/](http://kouapp.main.jp/maps/COVID19/)

**Comment by Yfuruchin** [comment]
地図のチカラは強すぎるので、公開されている情報内容と照らし合わせて、他のサイトも見つつ表現方法（ズーム、色分け、ポイント/ポリゴン）について慎重な検討が必要かもしれません。

**Comment by koala-88** [comment]
こちらに記載するべきor新しくissueを投稿すべきか迷いましたが、

感染ルート(誰から誰に)感染したかの図があるとさらに良いかと思うますが、いかがでしょうか？
(AさんからBさんに感染したetc)

感染ルート( 例　名古屋FNN　https://www.fnn.jp/posts/10519THK)

**Comment by koukita** [comment]
感染ルートなら、別issue作ったほうがいいですね

**Comment by koala-88** [comment]
承知いたしました、別issue作成します。ご指示ありがとうございます。

**Comment by yuya8** [comment]
自分も地図がほしいと思い、作ってみています。
https://github.com/yuya8/covid19
<img src="https://user-images.githubusercontent.com/2116356/76524216-05581580-64ad-11ea-8c65-127d9cfe47f4.gif" width="300px">

自分の考え方としては、現在表示中の「"陽性患者の属性"を可視化する」というコンセプトです。
![image](https://user-images.githubusercontent.com/2116356/76524229-0ab56000-64ad-11ea-924f-4ef9c9141975.png)

**Comment by yuya894** [comment]
自分も地図がほしいと思い、作ってみています。
https://github.com/yuya8/covid19
自分が作っているのは、現在表示中の"陽性患者の属性"を地図上で可視化するというものです。
<img src="https://user-images.githubusercontent.com/2116356/76524229-0ab56000-64ad-11ea-924f-4ef9c9141975.png" width="250px"/><img src="https://user-images.githubusercontent.com/2116356/76525003-66ccb400-64ae-11ea-9567-4f64c3bdeb9c.png" width="200px"/>

### 「慎重な検討」について

@Yfuruchin さんの言う「地図のチカラが強い」というのは「詳細なデータまで載せてしまうとプライバシー侵害や、地域差別になったり色々ハレーションがありそう」ということですかね？

自分はそう思うので、「現在表示中のデータを可視化する」という方針としました。(表示中のデータはそういう問題を回避していると思うので....)

ズーム、色分け、ポイント/ポリゴンについては、開発用のサイトで見ながら調整していくのがいいと思います。

### 既存の開発(koukita さん作)との競合について
まず、急に割り込んできてすみません。

@koukitaさんのは独立したサイトとして作られていて、データ更新も必要なため、メンテが大変そうだなぁという印象でした。私が作っているものはVueベースであるため、500行くらいのコード変更で済みます。
https://github.com/yuya8/covid19/commit/9c513782c8e502c290abb5675dca85138a8d2934

また、ジオコーディングは [nominatim](https://wiki.openstreetmap.org/wiki/JA:Nominatim) というOSSを使っているため、自分で地図データを作成する必要もありません。

ただ、外部サービスに依存するので、正確さと速度はkoukita 製よりも劣ると思います。

1. 正確性と速さを求めるならばkoukitaさんのを採用
2. メンテナンス製を求めるならば自分のを採用
3. どちらも取るならデータ部分はkoukita製、画面はyUya製

みたいになると思っています。

状況を把握しきれてない部分もあるので、間違っていたらすみません。

**Comment by koukita** [comment]
提案ありがとうございます。
私もはじめは、感染者のポイントを地図化しようと考えていましたが、これだけ陽性の人数が増えて来ていて、半分以上は回復されている今の現状を考えると、感染源とか、感染ルートというのがはじめより意味をなさなくなってきていると感じています。そのため、このまとめサイトでは別に必要ないかなとも思い始めています。地図化したければ自分で独立したサイトを作ればいいので。
あと、このデータで難しいのは、 @Yfuruchin さんも言っているように地図の力が強すぎることです。公表は「市町村」とか「振興局管内」です。そのスケールは北海道では様々です。ポイントを市役所や振興局の建物に置いても、それは真ではありません。市町村のポリゴンにしてもしかり、「市町村界」でも「振興局界」でも大きすぎて、実際に近いのか遠いのかわからないのです。
しかもその程度の地図であれば、[NHKなどでもまとめているので](https://www.nhk.or.jp/sapporo/articles/slug-nf914806c8003)、そちらへのリンクで十分だと思います。
発生直後なら意味があったかもしれませんが、現状ではあまり意味がないように感じています。

しかし、このような議論が必要だと思います。

**Comment by yuya894** [comment]
> 「市町村界」でも「振興局界」でも大きすぎて、実際に近いのか遠いのかわからないのです。

これは確かにその通りですね。
が、別におおよその位置でいいのでは？とも思ってます。「管内、市内というデータなので振興局や市役所にマーカーを置いている」という注釈を付ければ何の問題もないと思います。[厚労省のサイト](https://mhlw-gis.maps.arcgis.com/apps/opsdashboard/index.html#/c2ac63d9dd05406dab7407b5053d108e)もそうなっています。

> しかもその程度の地図であれば、NHKなどでもまとめているので、そちらへのリンクで十分だと思います。

NHKのものは性別や年齢は分からないですよね。
私の目的は「陽性患者の属性」の表を見やすくすることです。マーカークリックにより詳細表示もしたいと思っています。

> 発生直後なら意味があったかもしれませんが、現状ではあまり意味がないように感じています。

確かに現状だと地図は必要ないかもしれません。
ただ私は「現在の見にくいデータを見やすくしたい」という思いで動いていました。

みなさんはもっと高度なものを描いているようなので、自分とは違うのかもしれません。

**Comment by koukita** [comment]
他の方の意見も聞きたいです。
見せ方を工夫すると、もしかしたら良いものができるかもしれません。
アイデアを含め、意見などお願いします。

**Comment by daisuke-fukuda** [comment]
私はこう思いました〜


========================================
誤解を招かない情報なのであれば、あっても良いと思います。

このプロジェクトの

「北海道による公式情報と客観的な数値をわかりやすく伝えることで、北海道にお住まいの方や、北海道内に拠点を持つ企業の方、北海道を訪れる方が、現状を把握して適切な対策を取れるようにすることを目的としています。」

という目的と基本的には合致しているのでは無いでしょうか。


> 誤解を招かない

ここが議論になるポイントかと思います。

基本方針として、陽性患者の属性データを元に地図上でマッピングするだけであれば、現在表示している情報をわかりやすくしただけなので、良いと思います。

一方で、陽性患者数累計だけでなく、現在患者数としても表示できるようにしないと、「現状を把握して」という点が弱いかな、と思います。（データ的に現在患者数と居住地のマッピングってできてるんでしたっけ、、、

**Comment by koukita** [comment]
残念ながら現在公開されている情報では、誰が完治した人なのかがわからないんです。
なので、今は感染者がいないのに、いつまでもそこにいるように見えてしまいます。

**Comment by yuya894** [comment]
うーん確かに時間が立つとマーカーが増えていって、「北海道全域ヤバい」みたいになると、変に誤解を招くかもしれません。

現在患者数と居住地のマッピングはないですが、「陽性患者の属性」にはリリース日というカラムがあるので、「直近1週間」とかの見せ方はできそうです。

ただ @koukita さんの言う通り、「今地図出してもなぁ...」という気分にもなってきました。
人が多いところは感染者数も多いのは当たり前ですし、他のサイトもあるし...。
https://gis.jag-japan.com/covid19jp/

それこそやりたいのなら個人でいいのかもしれません。

**Comment by koukita** [comment]
地図の必要性は、現状薄いので、Closeします
