### ISSUE TITLE
ドメインどうするか

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#36]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

https://github.com/codeforsapporo/covid19/issues/27
から切り出し

## 起こっている問題 / Occurred problem
* ドメインが未決
* カッチョいいのにしたい（）

## 状況
* @t.Suzukiさんより `hokkaido.dev` 提供のお申し出
https://codeforsapporo.slack.com/archives/CUJ8DH9DY/p1583544171339600

## 提案
* 東京都のドメインが
`stopcovid19.metro.tokyo.lg.jp`
なので
`stopcovid19.hokkaido.dev`
はどうか？

**Comment by nobuh** [comment]
さくらさんからサーバー提供があるのでさくらのクラウドでブランチを定期 pull するような形で実装中してみてます

前面はさくらのウェブアクセラレーターになり独自ドメイン登録が必要なので、stopcovid19.hokkaido.dev をお借りしようと思います。ありがとうございますー

**Comment by ymgt-design** [comment]
完了
