### ISSUE TITLE
当サイトについて　の内容更新

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#366]
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 北海道オープンデータポータルのデータ取得先が以前のままになている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4961152/78466219-aa2ae300-7739-11ea-9f1c-0fa8dd4e7765.png)

## 期待する見せ方・挙動 / Expected behavior
* 最新版では
covid19_data（検査数、陽性患者数、現在患者数（軽症・中等症、重症）、死亡数、陰性確認済み数　）のみからの取得になっている旨に更新

**Comment by watanavex** [comment]
#322 重複してたので閉じまーす！
