### ISSUE TITLE
Contributorの皆さんを再度まとめたい

### ISSUE THREAD

**Issue by NEKOYASAN** [codeforsapporo/covid19#383]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* Wikiに載せたあとからContributorの皆さんが増えてるかと思いますので更新したい
* Contributors.mdにまとめる？

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
*

**Comment by Kanahiro** [comment]
コーディングのつづりってCodingですよね？いまCordingになってるのであわせて直したい

**Comment by NEKOYASAN** [comment]
ですね

**Comment by NEKOYASAN** [comment]
@all-contributors please add Nekoya3 for code

**Comment by NEKOYASAN** [comment]
@all-contributors please add Nekoya3 for translation

**Comment by NEKOYASAN** [comment]
@all-contributors please add Nekoya3 for design

**Comment by NEKOYASAN** [comment]
@all-contributors please add Nekoya3 for coding

**Comment by NEKOYASAN** [comment]
All Contributors使うよりも手作業のほうが早いのでそちらに変更する
