### ISSUE TITLE
陽性患者の属性の日付のヘッダテキストは「リリース日」以外が良いのでは

### ISSUE THREAD

**Issue by y2naranja** [codeforsapporo/covid19#397]
FORKED.mdで見る限り、ヘッダテキスト自体は各サイトでとくに統一はされていませんが、「リリース日」は意味が分からないと思います。

**Comment by NEKOYASAN** [comment]
公表日とかでしょうか？

**Comment by y2naranja** [comment]
東京都だと「公表日」で、わかりやすいのはそれかなと思います。
単に「日付」でも、意図は伝わるかなとも思いますが、「公表日」が一番わかりやすいと思います。

**Comment by y2naranja** [comment]
取得元のオープンデータのcsvヘッダが「リリース日」なんですね。何故こんな名称に。
わざわざ置き換えるのは結構手間かもしれませんね。

**Comment by NEKOYASAN** [comment]
多分、患者情報のリリース日っていう意味合いでつけているんだと思うんですが、こちらで書き換え可能なので表示上だけ公表日に変更しますね。
（すこし後の変更になるかもですが）
