### ISSUE TITLE
日時表現が難しい

### ISSUE THREAD

**Issue by tk-suzuki** [codeforsapporo/covid19#4]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* JSON上では日時がISO 8601かつUTCで表現されている。（優先度: 低）

## 期待する見せ方・挙動 / Expected behavior
* データ更新者のリテラシーにあわせ、YYYY/MM/DD HH:MM表記のほうがよいのではないか

**Comment by takapiro99** [comment]
### Solution

Dateオブジェクトにして .toLocaleDateString などを使用するのはどうでしょうか  
  
[Dateオブジェクトにparse (MDN) ](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)  

[Dateをフォーマット (MDN)](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

[フォーマットのoption指定](http://js.studio-kingdom.com/javascript/date/to_locale_date_string#0.detail)

それで難しければ [moment.js](https://momentjs.com/) を使うという手もあると思います

**Comment by NEKOYASAN** [comment]
すでに解決済みなためclose
