### ISSUE TITLE
検査実施日別状況のグラフを非表示にする

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#40]
## 起こっている問題 / Occurred problem
検査実施日別状況の取得元が定まっていない

## スクリーンショット / Screenshot
<img width="819" alt="スクリーンショット 2020-03-07 14 46 28" src="https://user-images.githubusercontent.com/3221619/76137655-de4fad00-6082-11ea-90da-526b043fb2a6.png">

## 期待する見せ方・挙動 / Expected behavior
* V0では一旦非表示にする

**Comment by Yfuruchin** [comment]
コールセンター相談件数は札幌市のデータ使ってはどうでしょう？

**Comment by Yfuruchin** [comment]
contacts
querents
は札幌市データがあります（へんなとこにおいててすみません）
https://github.com/codeforsapporo/covid19/tree/development/data/sapporo

**Comment by watanavex** [comment]
おースミマセン！良いですね！
では、 `新型コロナコールセンター相談件数 (札幌市)` みたいにして出しちゃいますか！

**Comment by Yfuruchin** [comment]
ぜひぜひ！これで札幌市ICTさんのコミットも報われる（）はず！

**Comment by watanavex** [comment]
関連 #31

**Comment by watanavex** [comment]
では、
- 検査実施状況だけ非表示にする
- 相談件数は札幌市の情報を使う
っという事で！

**Comment by ghost** [comment]
#40 自体は対応終了してるのでクローズしていいと思います

**Comment by watanavex** [comment]
#46 ここの対応でデータが消えたから非表示になってるけど、index.vueにタグは残ってる。
予期せぬ修正で復活されてもアレなので、消しちゃった方が良いかな。。。

**Comment by NEKOYASAN** [comment]
generateしたときにタグ消えますっけ....消えるのであれはあとで検査数のデータをV1で取得可能になりそうなので残しておいてもいいかと思います

**Comment by watanavex** [comment]
すいません、私のみてたソースが古かったかもです 💦

**Comment by watanavex** [comment]
すいません、ここで対応されてましたね💦
a540530edb7eae361a7b974f34685b84dd517516
クローズします！
