### ISSUE TITLE
翻訳に不備がある

### ISSUE THREAD

**Issue by y-chan** [codeforsapporo/covid19#404]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 英語版において「件」の翻訳が消えている...?

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/34832037/79543704-dbf06200-80c8-11ea-96db-23bf332b135a.png)

## 期待する見せ方・挙動 / Expected behavior
* 件の翻訳が正しく表記されるようにする

## 起こっている問題の再現手段 / Steps to reproduce
1. https://stopcovid19.hokkaido.dev にアクセスし、言語を英語に切り替える。

## 動作環境・ブラウザ / Environment
*

**Comment by NEKOYASAN** [comment]
person personsの処理振り分けとかの関係で非表示にしてた覚えも...どうだったっけな..

**Comment by y-chan** [comment]
日本語は特に振り分けられてないですね....
https://github.com/codeforsapporo/covid19/blob/development/assets/locales/ja.i18n.json#L120

**Comment by y-chan** [comment]
https://github.com/codeforsapporo/covid19/blob/development/components/cards/QuerentsCard.vue#L11
こちらも特に接尾語がついてるわけではないよう...

**Comment by y-chan** [comment]
そもそも翻訳がまだ(?)ないですね....
https://github.com/codeforsapporo/covid19/blob/development/assets/locales/en.i18n.json#L122

**Comment by NEKOYASAN** [comment]
1件は1case
2件以上は2casesになるのでそこをどうやってやるかっていうのがあって、なくてもいいよねって話で英語では表示消してるんだったかなと...i18nのチャンネル見直してきますー

**Comment by y-chan** [comment]
なるほどー
意図的に消しているのであれば、このIssueはcloseした方がよいですね...

**Comment by NEKOYASAN** [comment]
あ、いや、
https://codeforsapporo.slack.com/archives/C0100A8KXEU/p1584247812023600
personsで対応完了してるのでそれと同じ対応した方がいいですね

**Comment by NEKOYASAN** [comment]
私の認識不足でしたー...申し訳ない..

**Comment by NEKOYASAN** [comment]
TransifexのmanualSyncによって対応しました
