### ISSUE TITLE
陽性患者のリストをリリース日desc(新→旧)にする

### ISSUE THREAD

**Issue by y2naranja** [codeforsapporo/covid19#409]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 陽性患者の属性のリストの初期表示がリリース日昇順になっている
* 表を見た人は、ヘッダをクリックすることで並べ替えができることがわかりづらいと思われるので、最新のデータから見られるリリース日降順の方がよい

## 期待する見せ方・挙動 / Expected behavior
* 陽性患者の属性の表がリリース日降順で初期表示される

## 起こっている問題の再現手段 / Steps to reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
*

**Comment by NEKOYASAN** [comment]
お願いなので issue templateに沿った形でissueを立てて下さい.......

**Comment by y2naranja** [comment]
すみません。これで良いでしょうか。

**Comment by NEKOYASAN** [comment]
ありがとうございます

**Comment by NEKOYASAN** [comment]
![Screenshot_20200425-121842](https://user-images.githubusercontent.com/17000370/80269913-fc36a700-86ee-11ea-95f2-c26268eb54cb.png)
通常、リリース日降順かと思いますがどの環境で発生している状況かお教えいただけますか？

**Comment by y2naranja** [comment]
Windows10ではEdgeとFirefox,Android9ではFirefoxです。
また、Windows10のEdgeでは1行目が明細の途中に出ています。
Edgeでグラフが崩れる現象が出ているので、別途issueをたてます。

# OS:Windows10
## Chrome
リリース日降順
## Edge
※リリース日昇順・1行目(1/28)が明細の途中に出ている（画像では一番下の行）
![Image of Edge](https://stopcovid19-sites.site/image/20200426_win10_Edge.jpg)
## Firefox
※リリース日昇順
![Image of Firefox](https://stopcovid19-sites.site/image/20200426_win10_Firefox.jpg)
## Opera
リリース日降順

# OS:Android9
## Chrome
リリース日降順
## Edge
リリース日降順
## Firefox
※リリース日昇順
![Image of Firefox](https://stopcovid19-sites.site/image/20200426_android-firefox_s.jpg)
## Opera
リリース日降順
