### ISSUE TITLE
What's newの取り扱い

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#41]
## 起こっている問題 / Occurred problem
What's new的な領域があるが
* 情報の取得元はどこにする？
* 更新は手動？自動？

## スクリーンショット / Screenshot
<img width="506" alt="スクリーンショット 2020-03-07 14 53 41" src="https://user-images.githubusercontent.com/3221619/76137736-85344900-6083-11ea-94f5-76bdc3768584.png">

## 期待する見せ方・挙動 / Expected behavior
* このissueで議論したく

**Comment by Yfuruchin** [comment]
道庁には昔懐かしいRSSがまだ生きてるので「コロナ」で引っ掛けてくるとかどうでしょう
http://www.pref.hokkaido.lg.jp/rss/index.htm

**Comment by ymgt-design** [comment]
とりあえずは北海道ではなく、厚労省のtwitterデータを持ってくるのはいかがですか？
https://twitter.com/MHLWitter

**Comment by watanavex** [comment]
TwitterのAPIは審査とか敷居が高いイメージがあるので、IFFFT経由でgithub actionをトリガーするとか...
アリかなぁ🤔

**Comment by ymgt-design** [comment]
なるほど。それであれば、厚労省の新着記事にリンクでも良いかもですよね。
本来は北海道の情報をのっけたいところが整理ついていない感じってだけなので。ひとまず。
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/topics_shingata_09444.html

**Comment by NEKOYASAN** [comment]
> TwitterのAPIは審査とか敷居が高いイメージがあるので、IFFFT経由でgithub actionをトリガーするとか...
> アリかなぁ🤔

TwitterAPIで厚労省の最新ツイートを表示とかは結構簡単にできるとは思いますが、どうせタスクとかで定期的に情報取得しないといけないのでIFTTTで取得するのもありかとおもいます

**Comment by ymgt-design** [comment]
こちらどうしましょうか。

**Comment by NEKOYASAN** [comment]
V0では手動対応でもいいかもしれないですね

**Comment by watanavex** [comment]
そうしましょう。とりあえず、なんの情報出しておきます？

**Comment by watanavex** [comment]
道庁のHPで、一番目立つところで伝えたそうなもの、コレだったので、
http://www.pref.hokkaido.lg.jp/hf/kth/kak/kinnkyuuzitaisengenn0305.pdf
ここへのリンクなんで如何でしょう？

**Comment by watanavex** [comment]
あーダメか、 `7〜8日の外出は控えましょう` って、すぐ情報の古さ出ちゃう。。。

**Comment by watanavex** [comment]
このリンクなんてどうでしょうか？
http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijyoukyou0308yousei_0307genzai.pdf
#84 で当該の表を非表示にしちゃうので (まだマージされてないけど)
そのかわりに、V0では外部リンクで見せる！

**Comment by ymgt-design** [comment]
こちらV0での扱い終わったとみなしてv1にもっていく感じでどうでしょうか?

**Comment by watanavex** [comment]
あ、まだ #85 がマージされてないんですよね...
@takkundayo さんが上の内容でOKだと言ってくださったらセルフマージしちゃいますー！

**Comment by ymgt-design** [comment]
こちらv1に持っていくのに新しくissue立ち上げたほうがいい感じなんですかね？

**Comment by watanavex** [comment]
マージあざます❗️どっちでもOKです🙆‍♂️

**Comment by ymgt-design** [comment]
v1へ移動
20200308現在手動で設定中。

**Comment by NEKOYASAN** [comment]
whats newから日付を削除しurlと内容を固定して運用という形に落ち着いたためclose
