### ISSUE TITLE
Windows10/Edgeでグラフの表示が崩れている

### ISSUE THREAD

**Issue by y2naranja** [codeforsapporo/covid19#412]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* Windows10/Edgeのみ、グラフの表示が崩れている
Chrome,Firefox,Opera,Android版のEdge,Chrome,Firefox,Operaでは発生しない

## スクリーンショット / Screenshot

![Image of Edge](https://stopcovid19-sites.site/image/20200426_win10_Edge_graph01_s.jpg)
![Image of Edge](https://stopcovid19-sites.site/image/20200426_win10_Edge_graph02_s.jpg)
![Image of Edge](https://stopcovid19-sites.site/image/20200426_win10_Edge_graph03_s.jpg)
![Image of Edge](https://stopcovid19-sites.site/image/20200426_win10_Edge_graph04_s.jpg)
![Image of Edge](https://stopcovid19-sites.site/image/20200426_win10_Edge_graph05_s.jpg)

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to reproduce
1. Winsdows10にて、Edgeでトップページを表示させる

## 動作環境・ブラウザ / Environment
* Windows10/Edge

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/80309328-59c21500-880f-11ea-933b-2d7f91a1f127.png)

発生しません...

**Comment by y2naranja** [comment]
うちのモニタが古くて、モニタの解像度が低いためででしょうか。
（多分1600x1200）
またはモニタの設定の問題なのか。
とりあえず設定を見直してみます。

ちなみに東京都版でも、同じような表示になってしまいます。

**Comment by Kanahiro** [comment]
## Windows10 64bit でのEdgeのサンプル

<img width="1013" alt="sample_edge" src="https://user-images.githubusercontent.com/20744195/80323977-4774c500-8869-11ea-9e15-8cace61b149d.png">

レイアウト崩れは発生しなかった。

## バージョン

Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363


@y2naranja 
Edgeのバージョンを確認していただけますか？
最新でない場合は更新のうえ動作確認してみてください。

**Comment by Kanahiro** [comment]
バージョンは、Edgeの右上の「…」→設定→全般の一番下に記載されています。

<img width="343" alt="スクリーンショット 2020-04-27 9 32 01" src="https://user-images.githubusercontent.com/20744195/80324110-15b02e00-886a-11ea-99cf-57ed2ff83409.png">

<img width="591" alt="スクリーンショット 2020-04-27 9 32 41" src="https://user-images.githubusercontent.com/20744195/80324112-18ab1e80-886a-11ea-94d8-0524a4c6f102.png">

**Comment by y2naranja** [comment]
バージョンを確認してみましたが、最新の状態でした。
モニタの解像度が1680x1050なので、その影響でしょうか。
![version of Edge](https://stopcovid19-sites.site/image/20200427_win10_Edge_graph_version.jpg)

**Comment by y2naranja** [comment]
モニタの解像度を1024x768にして確認してみたところ、同様にEdgeでだけグラフが崩れ、Chrome、Firefox、Operaでは発生しませんでした。

**Comment by Kanahiro** [comment]
仮想環境上ですが、解像度を落としてもレスポンシブサイトなので影響はありませんでした。
ところで少し気になったのですが、この緑のアイコンはウイルス対策ソフトの類ですか？

<img width="49" alt="スクリーンショット 2020-04-27 9 57 01" src="https://user-images.githubusercontent.com/20744195/80324830-87d64200-886d-11ea-9ff5-0d2598d686e1.png">

@y2naranja さんと私の環境の違いはもはやこのアイコンの有無くらいですので、原因究明のため表示しないような設定をトライしていただきたいです。

**Comment by y2naranja** [comment]
緑のアイコンは、カスペルスキーのプラグインです。切って表示してみましたが、結果は変わりませんでした。
![version of Edge](https://stopcovid19-sites.site/image/20200427_win10_Edge_graph_01.jpg)

**Comment by Kanahiro** [comment]
スクリーンショットに見受けられるノイズ（棒グラフや「累計」の背景）は圧縮などによるものですか？それともそのとおりブラウザで表示されていますか？

**Comment by y2naranja** [comment]
Edgeの場合のみ、この通りに表示されています。Chrome、Firefox、Operaでは出ません。
下記はChromeの場合ですが、グラフは崩れません。
![View of Chrome](https://stopcovid19-sites.site/image/20200427_win10_Chrome_graph_01.jpg)

**Comment by takehirock** [comment]
以下、環境再現しない

Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362

Microsoft Windows バージョン 1903(OSビルド 18362.720)

**Comment by NEKOYASAN** [comment]
@y2naranja https://deploy-preview-413--code-for-sappor-covid19-deploy-preview-free.netlify.app/
こちらでも発生しますか？

**Comment by y2naranja** [comment]
グラフは正常に表示されるようになりました。
日別／累計のボタンは、累計のときだけボタンに線が入りますが、マウスオーバーで消えます。
念の為、Chrome、Firefox、Operaで確認しましたが、問題なく表示されました。
![graph of Edge](https://stopcovid19-sites.site/image/20200427_win10_Edge_graph_02.jpg)
![botton of Edge](https://stopcovid19-sites.site/image/20200427_win10_Edge_graph_03.jpg)

**Comment by NEKOYASAN** [comment]
他の発生報告がないため、PC側の環境の問題かと思います。
