### ISSUE TITLE
札幌市データをDATA-SMART CITY SAPPOROのAPIから持ってくる

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#43]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 札幌市データを手作業で持ってくる必要がある

## 提案(こうなるとすげえ未来感😍、むしろ理想形
1. 札幌市担当がDATA-SMART CITY SAPPOROに登録
2. DATA-SMART CITY SAPPOROにおけるCKANのAPI経由で本システムが取得
3. 本システムの可視化に**自動で**反映
![image](https://user-images.githubusercontent.com/4961152/76140110-5c6b7e00-609a-11ea-925b-0d8c4df4a0a4.png)

FYI
API(LOD?)仕様書
https://data.pf-sapporo.jp/apiuse
AEDデータのAPI
https://ckan.pf-sapporo.jp/dataset/30261af2-4e83-4fff-8605-6b6e7247449d/resource/5cf273d1-595f-412c-92de-36e7a88ef9e9?view_id=1413bd47-0a64-4593-9c71-ffd7bdfbc8eb
![image](https://user-images.githubusercontent.com/4961152/76140186-12cf6300-609b-11ea-917e-e629f075375f.png)

**Comment by ysk8hori** [comment]
## クライアントからJSONPにてロードする方式を検討しました

結論としては、上手くいきませんでした。以下理由です。

- axiosでのjsonp、jqueryでのjsonp、いずれもデータ取得APIにjsonp固有のパラメータが付与されることでサーバー側で404や409扱いとなりました。（jsonp固有のパラメータとはコールバック関数名やリクエストのIDを指します）
- jsonp固有のパラメータを除いたとしても、CORBのエラーにより取得したデータを参照することができませんでした。

クライアントからのJSONPでの取得は諦めた方が良さそうです。

### 次の検討事項の提案（誰かよろしく！）

ビルドのタイミングでスクリプトを走らせて（やり方どころか、できるかどうかも知らないで書いてます。）データを取得しjsonファイルを吐き出すか、どなたかのローカルでスクリプトなり手動なりでデータの取得とjsonファイル作成を行う方式で検討する。

### 検証内容

#### 札幌駅前通地下歩行空間（チ･カ･ホ）人流データで仮実装

仮に、以下のページの「札幌駅前通地下歩行空間（チ･カ･ホ）人流データ」をブラウザからJSONPにて取得できるか試みました。

https://ckan.pf-sapporo.jp/dataset/chikaho-jinryu/resource/39977340-d391-4b15-bfae-0946cce68812

このデータは、CSVデータまたはAPIを使用するとJSON形式で取得可能です。

例）APIでの取得サンプル
```
https://ckan.pf-sapporo.jp/api/action/datastore_search?resource_id=39977340-d391-4b15-bfae-0946cce68812&limit=5
```

コレをブラウザからJSONPで実行してデータの取得を試みました。
しかし、上述の通り404やCORBにより上手くいきませんでした。

ちなみに、サンプル上述のチカホ人流データのページにjqueryでの実装例が載っていましたが、それを使用しても404になりました。

**Comment by aruneko** [comment]
せっかくGithub Actionが有効化されているので、ビルド（あるいはデプロイ手前）のタイミングで自動的にデータ取得と成型を行う形にするとシンプルにできそうかと思います。

あるいは、NuxtのSSRをしているのであればCORBを回避して直接読み込みに行けるかもしれないですが、こちらは未検証です...

**Comment by NEKOYASAN** [comment]
SSRしてないんです！！！SSR詐欺ごめんなさい！！！nuxt generateで静的ファイルにして公開するのでCORB回避するのはすこし面倒化と..

**Comment by aruneko** [comment]
補足ありがとうございます！

であればCIでデータ取得を自動化してしまう方向にするのが良さそうですね。

**Comment by Yfuruchin** [comment]
相談データはここにUPされました
https://ckan.pf-sapporo.jp/dataset/covid_19_soudan

**Comment by Yfuruchin** [comment]
おっと、
https://codeforsapporo.slack.com/archives/CUKTK3R4K/p1583737793255000
工藤_札幌市  18分前
ちなみに、今後もこちらで追加・更新していきたいと思うのですが、CKANの機能上データセット内のリソースの更新ということができず、ファイルを削除して新しいものをアップしなおすという形をとっています。
工藤_札幌市  18分前
これによりリソースページのURLが変わってしまいそうなのですが、API利用するならまずいですよね・・・？

**Comment by ysk8hori** [comment]
以下の確認をお願いしたいです。
* URLは本当に変わってしまうのか？
* csvのURLも変わってしまうのか？

URLが変わるなら、まずそのタイミングで教えて貰う事になります。

その後最新データの取り込みと反映の作業が必要でしょうが、出来れば全て自動化したいですね・・・。

これからSSR化するのは難しいんでしょうかね？

**Comment by Yfuruchin** [comment]
札幌市小笠原さんより
https://codeforsapporo.slack.com/archives/CUKTK3R4K/p1583737793255000
→Githubのこのスレにお呼びしました
```
N.Ogasawara  2時間前
@furukawa データの更新(削除後、新しいファイルをUP)をする機会があったので、作業前後のurlをチェックしたので間違いなくurl変わります。
CKANの機能上の制約だと思いますが、削除したファイルは所謂論理削除となり、DB上には残っている状態のようです。
明日改めて旧urlにアクセスして旧データが表示されるのか、確認して情報提供致します。
N.Ogasawara  2時間前
併せて、こちらの保守ベンダへ問合せもしておりますので、回答がありましたらこちらも情報提供致します。
```

**Comment by Nar-Ogasawara** [comment]
@Yfuruchin お呼ばれしましたので来てしまいました。
少しでもお役に立てるよう頑張りたいと思いますので、よろしくお願いします。

**Comment by ysk8hori** [comment]
よろしくお願いいたします。

URLが変わってしまうのは仕方がないことですので、その場合の対処を（今は手動でやるにせよ）腰を据えて検討していくことになるかと思います。

**Comment by kdshunko** [comment]
札幌市工藤です。
URLが変わる件、クリアできました。
変わらないようにアップできるようになりましたので、今後そのようにいたします。

**Comment by NEKOYASAN** [comment]
了解しましたありがとうございます！
データ取得するコードの方で自動取得組ませていただきますー！

**Comment by NEKOYASAN** [comment]
https://github.com/codeforsapporo/covid19hokkaido_scraping
でほぼ取得については自動化できているためクローズします
