### ISSUE TITLE
グラフ用表示期間スライダーの注釈と、実際の表示範囲で差異がある

### ISSUE THREAD

**Issue by paichi81** [codeforsapporo/covid19#464]
- [x] バグ / Bug

* 移植先の埼玉県版対策サイトでバグを発見したのでフィードバックします。
https://github.com/codefortoda/covid19-saitama/issues/93

## 起こっている問題 / Occurred problem
* グラフの範囲スライダーの注釈文言では最小14日となっているが、グラフ・スライダーの実際の表示と異なる
* スライダーは最小15日で、グラフは最小16日分で表示される

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/4400857/90305344-8ef88d00-defc-11ea-8a47-96c86fa44a72.png)

## 期待する見せ方・挙動 / Expected behavior
* スライダーの範囲を注意文言にあわせる
* グラフの表示をスライダーにあわせる

## 起こっている問題の再現手段 / Steps to reproduce
1. グラフ下の表示期間スライダーを15日の期間にする

## 動作環境・ブラウザ / Environment
* Chrome(Windows)

**Comment by paichi81** [comment]
こちらのリポジトリのfolkがうまくできなかったので、PR送れませんが修正点↓になります。

https://github.com/paichi81/covid19-sapporo/commit/00d0539946e6047388713c11a66098c377fa7fa1

**Comment by NEKOYASAN** [comment]
ありがとうございますー！
SliderMaxをWatchしてるところで0をSliderMinに変更してるのって何か問題発生したからでしたか？

**Comment by paichi81** [comment]
いえ、そのままでも問題はなかったかと。
埼玉県版修正時に福岡県版DateSelectSliderを使ったのですが、そちらが最小値をマジックナンバーからsliderMinに変えていたようなので、たんにそのまま流用しただけです。

**Comment by NEKOYASAN** [comment]
なるほど！ありがとうございますー
