### ISSUE TITLE
北海道IT推進協会のロゴを表示する

### ISSUE THREAD

**Issue by koukita** [codeforsapporo/covid19#471]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 左サイドバーの「JUST道IT」の下に、北海道IT推進協会のロゴを表示する

![Itkyou_rogo](https://user-images.githubusercontent.com/13256642/105051404-0fc24300-5ab2-11eb-8043-1d672fb81625.png)

**Comment by Kanahiro** [comment]
``** by``の**の部分ですが。

- これまでは@nobuhさんがsakuraのサーバーを運用されていた
- 今後はsakuraのサーバーを北海道IT推進協会さんが運用される

ということで、Operation byが妥当かと思います。
