### ISSUE TITLE
鈴木北海道知事のツイートから数値データを抜く

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#49]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 道庁のwebではPDF画像化されている数値があってパースできない
* 生の数値データがwebに公開されるのはかなり先とみられる

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4961152/76142923-8d0ce100-60b5-11ea-839b-adb2361d437e.png)

## 期待する見せ方・挙動 / Expected behavior
* 知事は[毎日10時頃に数値をツイートするようなので](https://twitter.com/suzukinaomichi/status/1236096938287783937)、web表のスクレイピングでは得られない値（検査人数・退院累計等？）パースしてログ化する
* ログををシステムに取り込めるようにする

**Comment by Yfuruchin** [comment]
@Nekoya3 さんが調査検討してくださるとのこと　THXXX

**Comment by Yfuruchin** [comment]
参考
https://github.com/codeforsapporo/covid19/issues/2

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/76145533-7a060b00-60cd-11ea-9286-7f626d742d8f.png)
ツイート文章の取得はすでにできたのでそう時間かからずこれ自体はできるかと思います

**Comment by koukita** [comment]
本日発表された３月７日付けの情報から、退院数が「陰性確認済累計」と変わっています。グラフなどにされる場合は、言葉を合わせたほうがいいかも。
データは「discharges_summary」です

**Comment by Yfuruchin** [comment]
語句変更は
https://github.com/codeforsapporo/covid19/issues/74
に切り出し

**Comment by NEKOYASAN** [comment]
道から近日中にcsvなどでデータの提供をいただけるようであればこれよりも確実かつ開発コスト低いのでクローズしたいのですがどうでしょう？

**Comment by watanavex** [comment]
> これよりも確実かつ開発コスト低いのでクローズ

大賛成です

**Comment by NEKOYASAN** [comment]
csvのデータを提供いただくまでに時間がかかる場合はreopenしますが、現状この方法よりも確実かつ、開発コストが低いものが #144 #154 #180 にて協議され、実装できる見込みもついているため一度クローズします
