### ISSUE TITLE
文言の北海道化

### ISSUE THREAD

**Issue by tk-suzuki** [codeforsapporo/covid19#5]
関連 #17 

- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 「東京」。

## 期待する見せ方・挙動 / Expected behavior
* まず「東京」という文字を全部「北海道」にする

**Comment by watanavex** [comment]
https://github.com/codeforsapporo/covid19/issues/27#issuecomment-595632423

**Comment by watanavex** [comment]
grepするとまだ '東京都' の文言が残ってる！

**Comment by watanavex** [comment]
#30 での対応が完了すれば、一旦完了かなと思います。
クローズします！
