### ISSUE TITLE
OGP画像が東京都のまま

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#53]
## 起こっている問題 / Occurred problem
SSIA

/static下の `ogp.png` を変更しても反映されなかった。
恐らく、nuxt.config.jsのこの辺変更しなきゃいけないと思われる。
```
      {
        hid: 'og:image',
        property: 'og:image',
        content: 'https://stopcovid19.metro.tokyo.lg.jp/ogp.png'
      }
```
@daisuke-fukuda さんによると、相対パスでもダメかも？

**Comment by daisuke-fukuda** [comment]
軽くググったやつ
https://workabroad.jp/posts/630

**Comment by daisuke-fukuda** [comment]
仮でdevelopmentのURL（https://admiring-davinci-e0cd70.netlify.com/）を指定しています。

本ドメインと、本番サーバが確定したら差し替える必要があります。（変更箇所は3箇所ありましたので、↑のコミットを参照ください）

**Comment by Yfuruchin** [comment]
v0ローンチ前にカッチョイイOGPが表示されるか再度確認しましょうー

**Comment by aricone** [comment]
OGP画像は下記のURLとなっているようで
https://stopcovid19.hokkaido.dev/ogp.png
↓
http://133.242.52.161:58000/ogp.png
上記の画像が正しいのかなと思いました

**Comment by NEKOYASAN** [comment]
公開後であれば上のURLのがいいんだとは思うんですが...どうしましょ...

**Comment by daisuke-fukuda** [comment]
https://stopcovid19.hokkaido.dev を落としてるのって、なにか理由ありましたっけ？？

もうすぐ公開という事を考えれば、サーバを復活させても問題ないと思います。（robots.txtでdenyは入っているので、そこまでリスクは無いはず、、、

**Comment by Yfuruchin** [comment]
そろそろ最終の細かいチェックなのでよいかと

**Comment by nobuh** [comment]
master ってまだ東京のままですが、とりあえず先にあげてそれからマージしますか？

**Comment by daisuke-fukuda** [comment]
確かに、masterを全然更新してなかったですね。

以下でいかがでしょう？

==== 現状のを一旦本番まであげて、本番でしかできない事チェック ====

①本番サーバ復活
②development -> masterにマージ
③本番に反映される
④ogタグチェック、その他本番環境でないとできない事チェック


引き続きdevelopmentでの開発はしつつ、一旦あげちゃいましょー、という作戦です

**Comment by watanavex** [comment]
#114 一応PR作りました。
マージしちゃいますね！

**Comment by watanavex** [comment]
master更新されましたん！

**Comment by watanavex** [comment]
確認できましたね！closeしますぅ〜！
