### ISSUE TITLE
Copyrigytが Tokyo Metropolitan Government のまま

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#54]
## 起こっている問題 / Occurred problem
SSIA

#27 (comment) このコメントに則って、コピーライトは主張しない

**Comment by Yfuruchin** [comment]
oh
これではどうでしょう？
https://github.com/codeforsapporo/covid19/issues/27#issuecomment-595631953

**Comment by watanavex** [comment]
そうしましょう！
