### ISSUE TITLE
道庁・道旗ロゴ対応

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#58]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 本サイトは北海道庁公式のサイトではないのでローディング時の北海道ロゴや道旗faviconのマークは誤解を招くかもしれないです（作ってもらったのにすみません）

>道庁の機関以外で使用いただくことはできません。
- http://www.pref.hokkaido.lg.jp/ss/tkk/chosei/mark.htm#maru1

道旗はいいのかな？うーんでもちょっとアレかも
- https://ja.wikipedia.org/wiki/%E5%8C%97%E6%B5%B7%E9%81%93%E6%97%97

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4961152/76144979-ae2afd00-60c8-11ea-8cf7-0b05eda763ad.png)

![image](https://user-images.githubusercontent.com/4961152/76144975-a4a19500-60c8-11ea-8df3-d430ce5650a9.png)

## 期待する見せ方・挙動 / Expected behavior
* 北海道の形状等に差し替え？

**Comment by NEKOYASAN** [comment]
これ用にロゴを作るのもありかもしれませんね

**Comment by watanavex** [comment]
LITTLEKIT氏 (https://twitter.com/LITTLEKIT) に依頼してみましょう！

**Comment by Yfuruchin** [comment]
LITTLEKIT氏こさえてくれました！
![image](https://user-images.githubusercontent.com/4961152/76155464-8d49c280-612f-11ea-9fc3-11c401048f33.png)

ファイルは下記に
[covid19-hokkaido_logo_set.zip](https://github.com/codeforsapporo/covid19/files/4302734/covid19-hokkaido_logo_set.zip)
