### ISSUE TITLE
表現リファクタリング

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#59]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* https://github.com/codeforsapporo/covid19/issues/58 に関連して、本プロジェクトは有志によって公的機関の情報を有志が分解（）再構築しているため、 情報発信元にご迷惑もおかけしないように「北海道庁が主体的にこのサイトで発信している」ような表現はミュートにしたほうがよいかもです

## 期待する見せ方・挙動 / Expected behavior
* 公的なロゴや文言・タイトルはやわらかく差し替え
* OGPテキストもちょっとreadmeなどを参照にリライトしたほうがいいかも
>北海道 新型コロナウイルスまとめサイト
>当サイトは新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、東京都公式 新型コロナウイルス対策サイトをフォークし、Code for Sapporoが開設したものです。

**Comment by ymgt-design** [comment]
対応完了しているのでクローズしますね
