### ISSUE TITLE
センター相談件数が札幌市の情報であることを明記

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#60]
- [ ] バグ / Bug
- [*] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
以下の2つのデータは札幌市の情報になっている。
本サイトは「北海道まとめサイト」なので、札幌市の情報を明記するべき
* 新型コロナコールセンター相談件数
* 帰国者・接触者電話相談センター相談件数

## 期待する見せ方・挙動 / Expected behavior
* `(札幌市)` とか付ける

**Comment by koukita** [comment]
「札幌市保健所」のデータであると明記したほうがいいかもしれません。
