### ISSUE TITLE
検査陽性者の状況の欄がSVGイメージのため自動更新ができない？かも？

### ISSUE THREAD

**Issue by NEKOYASAN** [codeforsapporo/covid19#61]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 検査陽性者の状況の欄SVGイメージのため自動更新ができない？かも？

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17000370/76145759-db2ede00-60cf-11ea-94b2-a526f545f488.png)

## 期待する見せ方・挙動 / Expected behavior
* せっかくchart.js入ってるんで円グラフとかで表示しませんか？

**Comment by koukita** [comment]
この図の中の、軽症、中等症、重症別のデータは公開されていないです。感染者がすべて入院している前提であれば、感染者ｰ退院者が入院中ですが、たぶんそうではないような気がします。

**Comment by NEKOYASAN** [comment]
症状別のデータが公開されてないのですね...了解しました。
であれば検査実施人数、陽性者数、現在患者数、退院人数、死亡人数を何かしらの方法で表示できるといいかもしれないですね

**Comment by daisuke-fukuda** [comment]
svgになってる経緯はここらへんのようです
https://github.com/tokyo-metropolitan-gov/covid19/issues/309
https://github.com/tokyo-metropolitan-gov/covid19/issues/436

**Comment by Yfuruchin** [comment]
道庁ではそれっぽいpdfを出し始めた
http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijyoukyou0308yousei_0307genzai.pdf

**Comment by koukita** [comment]
この図のもととなるデータは、data/better_patients_summary.csvになると思うのですが、この表は日付がカラムになっているので、分かりづらいですね。
他のテーブルと同じように、日付をレコードにしてもいいでしょうか？
また、図に合わせて、検査数、陽性患者数、死亡数、退院数は累計で、患者数は現在の値としていいでしょうか？
陽性患者数累計＝現在患者数＋死亡数累計＋退院数累計
となってわかりやすいので。

**Comment by koukita** [comment]
[こちら](https://docs.google.com/spreadsheets/d/1JuUGlxLRA7EDAMh17f-Nfi3E8z2HI_PV3GZZ3PTU55g/edit?usp=sharing)の「better_patients_summary_hkd」シートを参照

**Comment by koukita** [comment]
v0ではとりあえず削除するということですが、
本日の知事のツイートから、軽症、中等症、重症の症状別内訳が出てきたので、ツイートを自動取得するのであれば、図じゃなく、数字だけでも掲載する形でもいいかもしれませんね。
v1以降かな

**Comment by NEKOYASAN** [comment]
現在患者数をグラフで表示する（日別表示も）

**Comment by Kanahiro** [comment]
## 経緯
表題のUIはデータがあれば動的に生成出来るようになった
- 必要なデータ形式は？

## 現在の議論
データをどこで用意するか

#### 現状
- 1CSV→1json→1UI（例：patients.csv → patients.json → 陽性患者の属性）
- 道の5つのCSVを読み込んでおり、今回のUIに載せるべきデータは全てそれらのCSVに含まれているため、必ずしも新たなCSVデータの追加を必要としない

#### 案
1. フロントで取得したデータからオブジェクトを生成する
2. PythonでCSVを解析してjsonを生成する
3. オープンデータポータルに追加でCSVを用意してもらう

- 3は一番シンプル、だが担当者の手間が増える。
- 2はデータの変更・追加に弱くなる予感。また、現状の5つのCSVの中にもデータの重複はあるので、その統合も一度にやらないと手戻りがつらい。
- 1は2の後者の理由と同様。

私は3が望ましいと考えます。
UIに必要なデータ形式がわかりませんが、別添画像の表がCSVになっていれば大丈夫だと思われます（前日比・日次データ不要）。

![06B770F4-7591-467C-B47A-D7119CA907F0](https://user-images.githubusercontent.com/20744195/76700359-08941100-66fa-11ea-8486-f68202473673.jpeg)

**Comment by koukita** [comment]
現状オープンデータポータルにあるの５つのCSVのうち、陽性者属性を除く４つのCSVを１つにまとめて、そこに累計もデータとして追加しておけばどうでしょう。
現状は、日毎のデータしかCSVには記載していませんが、入力する人が数値を確認する意味でも累計はあると助かります。
１番新しい日付で、現在患者数に数値が入っている日付のデータを、上記の表に記載すればいいと思います。
日付も、年、月、日を分けて記録するようにすると、入力時のデータの揺れもなくなります。
図：CSVの例
![image](https://user-images.githubusercontent.com/13256642/76700566-1fd3fe00-66fc-11ea-9214-f5790ed2eb18.png)

この例では、３月１３日のデータでJsonを作ればいいかと思います。

**Comment by Kanahiro** [comment]
おっしゃられるようにCSV構造から見直すのが最も良いとは思います。
ただ手数が多そうなので時間がかかりそうです（CSV1つに1つJSONが紐付く設計のため）。

**Comment by NEKOYASAN** [comment]
jsonを分けずにcsvから直接パースするとすればバック、フロント共に変更点は少ないかとは思います。
ですが、見通しは悪くなりそうですね

**Comment by Kanahiro** [comment]
もしCSV構造が見直されたら、私ならフロントでUIにそのまま流し込めるようjsonを作成すると思います。
すなわち、今と同じjsonをCSVの集計から出力する、という事です（フロントを修正しないように）。

**Comment by koukita** [comment]
jsonを分けたのは、データが長くなってしまうので分けた経緯もあるので、Jsonはそのまま種別ごとに分けたままでいいと思います。１つのCSVから必要なデータをそれぞれのJsonに割り振ればいいと思います。

プログラムの修正には時間がかかるでしょうから、オープンデータポータルには、新旧のデータを両方載せておいて、移行期間を設けてもいいと思います。

**Comment by Kanahiro** [comment]
> 私ならフロントでUIにそのまま流し込めるようjsonを作成する

って言っておいてアレですけど、バックエンドかフロントかどっちか選択ですね。
1. フロントをいじらず、バックエンドで2つのCSVから5つのjsonを出力する
2. バックエンドをいじらず、2つのCSVから2つのjsonを出力してフロントで整形

1CSV1JSONを取るか、1JSON1UIを取るか
ベストプラクティスがわからないのでなんとも

あと、L字UIに必要なデータ構造サンプルあります？

**Comment by NEKOYASAN** [comment]
> あと、L字UIに必要なデータ構造サンプルあります？

帰宅後送ります！

**Comment by Kanahiro** [comment]
あとは工数があんまりかからなそうな、「重症か否か」の表示を諦めちゃう、これを推したい…w
他の数字は集計が容易（のはず、ほかのUIにのってる数字だし）、道の表と若干変わっちゃうが…

ただまあ、今後のCSV更新の担当者への引き渡しを視野に入れるとここいらでCSVを作業性高いものにするのはアリ寄りのアリと考えます。

**Comment by NEKOYASAN** [comment]
重症か否かの集計ってそんなにきついですかね…軽症・中等症者の日別をすべて足すのと、重症者の日別をすべて足すのなので現状あるデータからという面では他のデータと変わらないように思うのですが…
（表のデータぐらいならフロントで処理してもいいのかなーとも思いますが）

> ただまあ、今後のCSV更新の担当者への引き渡しを視野に入れるとここいらでCSVを作業性高いものにするのはアリ寄りのアリと考えます。

これについては私もとてもありだと思います

**Comment by Kanahiro** [comment]
> 重症か否かの集計ってそんなにきついですかね

今後の変更を考えたときに気が進まないというのが本音です。
というのも、今は1データ（CSVに限らない）：1JSON：1UIという構成になっています。
jsonを切り分ける際にAPIへの対応も含めて、上記のような実装になりました。ご存知のとおり、データの追加や変更は基本的に設定ファイルの修正のみで済みます。

一方、もしデータを集計して新たにjsonを生成するように実装すると、こうは行かなくなります。出力するjsonファイルごとに別々の実装になるでしょう。今は@Nekoya3さんと私が更新などをしていて、それなりにデータの構成もわかっているのでフロントもバックもスムーズに修正ができると思います。がしかし、業務ではなく有志である以上、属人性は低くしたいと考える訳です。そんな訳で設定ファイルに切り出していた訳ですね。

以上の理由から「特別な理由がなければ」やりたくない、という意見でした。
ただ今後、必ずしもITに明るくない道担当者さんに引き継ぐ事を視野に入れると、担当者にとって「CSVを使いやすくする」というのは私は特別な理由に該当すると考えます（また、そのうえで保守性の高いコードにするのもプログラマーの仕事かなとも思います)。

なので、もしやるならCSVの構成も見直したうえで、という意見になります。

**Comment by NEKOYASAN** [comment]
理解しました。たしかにそのとおりですね。
道担当者に引き継ぐのを考えるのであれば上にあるcsv構造の変更例が一番良いかと思います（累計の入力もあるためデータのズレが少なくなるかと…）

**Comment by Kanahiro** [comment]
（正直キレイに収まったからそのままにした〜いという気持ちもちょっとあります🙃）

そんな訳で、CSV構造の見直しを踏まえてという事になりますが、どうせなら道担当者さんの手間が少なくなるような構造がいいですね（さっきの@koukitaさんがあげていた構造になるんですかね）。

ODPに集約されたCSVがきたら、以下の修正をしようと思います。
- 集約されたCSVの要素を集計し、現状と同じjsonファイルを出力する
- 追加で、逆L字のUIに対応するjsonファイルを作る

**Comment by NEKOYASAN** [comment]
> （正直キレイに収まったからそのままにした〜いという気持ちもちょっとありますupside_down_face）

わかります…

とりあえず自動更新の部分はPR通してフロント側も通しちゃいますね

**Comment by NEKOYASAN** [comment]
L字UIに必要なデータ構造についてなんですが、検査人数、陽性者数、患者数、軽症・中等症者数、重症者数、死亡者数、陰性確認数のそれぞれ累計のデータがあればそのまま表にできますね

**Comment by Kanahiro** [comment]
了解です:)
それらを参考にkeyにしますね

**Comment by Kanahiro** [comment]
https://github.com/codeforsapporo/covid19hokkaido_scraping/pull/13
main_summaryとして、以下の形式のデータを出力する機能を追加しました。

```
{
    "検査人数": 1462,
    "陽性者数": 152,
    "患者数": 82,
    "軽症・中等症者数": 73,
    "重傷者数": 9,
    "死亡者数": 5,
    "陰性確認数": 65
}
```

他のデータは、個別にデータソースがありそれの取得日時をlast_updateとしていますが、このデータは、スクリプトにより生成されるのでlast_updateはありません。

**Comment by NEKOYASAN** [comment]
現状対応する必要がないためclose
もし、今後作成する必要が出たらreopenします
