### ISSUE TITLE
告知FBベージの作成

### ISSUE THREAD

**Issue by takehirock** [codeforsapporo/covid19#68]

**Comment by takehirock** [comment]
https://www.facebook.com/JUST%E9%81%93IT-106299527656125/?modal=admin_todo_tour

**Comment by takehirock** [comment]
アイキャッチの追加

**Comment by takehirock** [comment]
アイコン追加

**Comment by takehirock** [comment]
管理者追加

**Comment by Yfuruchin** [comment]
素材はこちら、カバー画像はKIKOTANが作ってくれているかも？

https://github.com/codeforsapporo/covid19/files/4302734/covid19-hokkaido_logo_set.zip

**Comment by ymgt-design** [comment]
仮のカバー画像を追加。
サイズはFBカバーの安全範囲で作成してます。
![coro](https://user-images.githubusercontent.com/61897769/76159579-8f2e7880-6165-11ea-94ba-41dada760f1a.jpg)

**Comment by watanavex** [comment]
PRマージしたらcloseしちゃったんですけど、まだ開けておいた方が良いですよね？
Reopenしますね？

**Comment by NEKOYASAN** [comment]
あーごめんなさい！！！TwitterのほうもReopenしていただいてもいいですか！

**Comment by ymgt-design** [comment]
そうですね。ここはFBの本体の編集系なのかなと思ってましたー

**Comment by ymgt-design** [comment]
https://www.facebook.com/JUST%E9%81%93IT-106299527656125/
とりあえず見れる状況までには設定済みとなりました
@takehirock @Yfuruchin @watanavex @Nekoya3 
どなたか見てOKであればクローズしてくださいー!
