### ISSUE TITLE
告知twitterカウントの作成

### ISSUE THREAD

**Issue by takehirock** [codeforsapporo/covid19#69]

**Comment by Yfuruchin** [comment]
そざいはこちら
https://github.com/codeforsapporo/covid19/issues/68#issuecomment-596158909

**Comment by watanavex** [comment]
<img width="235" alt="スクリーンショット 2020-03-08 13 45 45" src="https://user-images.githubusercontent.com/3221619/76158125-d0b72780-6155-11ea-9697-694bb2aeab25.png">

いま、ここ道庁のアカウントになってますけど、
このissueで作ったアカウントに差し替えた方がいいですかね？

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/76158298-de6dac80-6157-11ea-94d0-714a99d895e4.png)

道庁公式Twitterは上のメニューに含めて、これはこのissueのものに変えてもいいのではないでしょうか？

**Comment by ghost** [comment]
これやっちゃってもいいですか

**Comment by watanavex** [comment]
ぜひぜひ！
issueのAssigneesをご自身に変更して、対応して頂ければと！

**Comment by NEKOYASAN** [comment]
Assignできないっぽいんでそのままいきます!
上のmameは自分です...アカウント間違えました...

**Comment by NEKOYASAN** [comment]
https://twitter.com/Just_douit
つくりましたー

**Comment by watanavex** [comment]
PRマージしたら閉じちゃったけど、Reopenします〜

**Comment by NEKOYASAN** [comment]
https://twitter.com/Just_douit
カバーイメージなど設定しました！
もんだいなければここもクローズお願いします。

**Comment by ymgt-design** [comment]
確認OKでした!
