### ISSUE TITLE
データ出典の明記

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#71]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* https://github.com/codeforsapporo/covid19/issues/59 から派生
* グラフ下部にデータ出典がない
* 「公的なデータを示している」というエビデンスとして重要

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4961152/76155734-7dcc7880-6133-11ea-9ded-d6e8ce0ab4e9.png)

## 提案
* リンク付き出典テキストを各グラフコンテンツの更新日の前に追記する？
* 北海道の場合は
`出典：北海道庁webサイトより`
リンク先は
http://www.pref.hokkaido.lg.jp/ss/tkk/singatakoronahaien.htm
または
http://www.pref.hokkaido.lg.jp/

* 札幌市の場合は
 `出典：札幌市役所webサイトより`
リンク先
https://www.city.sapporo.jp/kinkyu_202002.html
または
https://www.city.sapporo.jp

**Comment by watanavex** [comment]
関連 #60

**Comment by koukita** [comment]
データ出典は各グラフに書いたほうがいいですね。

**Comment by ymgt-design** [comment]
データ出典ですが、原則的にまとめて別ページのほうが望ましい感じしています。
あまり文字が多いとビジュアルでやっている効果が薄く感じますが皆さんはいかがですか？

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/76160608-ec7af780-616e-11ea-9ced-e666103f1253.png)
出典をもし各グラフに書くとしたらこういった形ですかね

**Comment by ymgt-design** [comment]
この感じだとシンプルでいいですね。タップorクリックで元データに飛んでいけるならありだと思います!

**Comment by Yfuruchin** [comment]
#97 のマージでFIX
