### ISSUE TITLE
メインビジュアルのライセンスについて

### ISSUE THREAD

**Issue by ymgt-design** [codeforsapporo/covid19#72]
## 起こっている問題 / Occurred problem
* KITOTANが描いてくれたメインビジュアルのライセンスについて

## スクリーンショット / Screenshot
![illust_19vs39_1](https://user-images.githubusercontent.com/61897769/76156060-32689900-6138-11ea-90b6-aeae5e89dc49.jpg)

**Comment by Yfuruchin** [comment]
そうでした、作者様と確認がよいですね

**Comment by ymgt-design** [comment]
本人に確認した結果、CC BY 4.0 で表示をLITTLEKITとすることで確定したのでクローズしますー
