### ISSUE TITLE
道庁での語句変更対応

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#74]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 喜多さんより
３月７日付けの情報から、「退院数」が「陰性確認済累計」に変更

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/4961152/76156276-43ff7000-613b-11ea-8480-5ed12f39c2b8.png)

http://www.pref.hokkaido.lg.jp/ss/tkk/singatakoronahaien.htm

## 提案
* 「退院数」→「陰性確認済累計」とグラフなどの言葉を合わせる
* データは「discharges_summary」

**Comment by watanavex** [comment]
#144 が重複し、議論が進んでしまったのでコチラはcloseします
