### ISSUE TITLE
V0ローンチ前のチェック

### ISSUE THREAD

**Issue by Yfuruchin** [codeforsapporo/covid19#80]
- [x] 改善提案 / Suggestions for improvement

## 提案
* v0ローンチ前に下記チェックポイントについてチェック

• 扱ってるデータが少々センシティブなので、ローンチ広報前に道内データとのリンク確認をダブル・トリプルチェック

• ロンチ後のデータ更新フローの確認

• 広報タイミング/媒体

**Comment by ymgt-design** [comment]
- [ ] 扱ってるデータが少々センシティブなので、ローンチ広報前に道内データとのリンク確認をダブル・トリプルチェック
- [ ] ロンチ後のデータ更新フローの確認
- [x] 広報タイミング/媒体
広報についてはローンチ時に同時に行います。FB&twitter

**Comment by NEKOYASAN** [comment]
V0ローンチ済みなためいったんクローズします
