### ISSUE TITLE
陽性患者数のデータ作成

### ISSUE THREAD

**Issue by watanavex** [codeforsapporo/covid19#9]
# 道が公開しているデータをパースして、グラフ化出来る形に変換する。
関連: #1 #2 

| | |
|--|--|
|対応するデータファイル| /data/patients_summary.csv |
|取得元| http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijoukyou.htm |
|変換処理| 実装済み https://github.com/Kanahiro/covid19hokkaido_scraping |

## スクリーンショット / Screenshot
<img width="331" alt="スクリーンショット 2020-03-06 11 10 39" src="https://user-images.githubusercontent.com/3221619/76043523-2398af80-5f9b-11ea-9c7e-371495de67ef.png">

## 期待する見せ方・挙動 / Expected behavior
基本は都の見せ方に準拠だが、必要なデータが無い場合は別途検討。
ex) 日毎のデータがないのでグラフではなくテキストにする等

**Comment by watanavex** [comment]
反映先はこの辺り？
https://github.com/codeforsapporo/covid19/blob/development/data/patients_summary.csv

**Comment by watanavex** [comment]
> データに関しては暫定版ですけど上がってます
ただしwebページがどんな変態フォーマット進化をするか未知数ではありますが

☝️ @Yfuruchin さん談 (slackにて)

具体的な残タスクなどあれば追記お願いします！

**Comment by tk-suzuki** [comment]
陽性患者数は[発生状況テーブル](http://www.pref.hokkaido.lg.jp/hf/kth/kak/hasseijoukyou.htm)のパースで取得可能（ @Yfuruchin がコミット済）。

**Comment by watanavex** [comment]
https://github.com/codeforsapporo/covid19/issues/2#issuecomment-595581341
> 私用のリポジトリ上で、15分おきにCSVとJSONに書き出すようになりました。使えそうなら本体に取り込めれば…

**Comment by tk-suzuki** [comment]
誘導ありがとうございます！

**Comment by watanavex** [comment]
情報が分散していてスイマセン🙇‍♂️

**Comment by koukita** [comment]
### **提案**
patients.csvの居住地フィールドは、市町村と振興局の2つに分けたほうがいいように思います。
こんな感じでどうでしょうか？
[https://github.com/koukita/covid19/blob/development/data/patients.csv](https://github.com/koukita/covid19/blob/development/data/patients.csv)
道庁のホームページから自動でこんなテーブルにスクレイピングできますかね？

**Comment by watanavex** [comment]
@koukita 
> patients.csvの居住地フィールドは、市町村と振興局の2つに分けたほうがいいように思います。
こんな感じでどうでしょうか？

すいません、カラム増えた場合にnuxt側が都合悪いかも知れないので、別issue立てますね！

**Comment by koukita** [comment]
そうですよね。ありがとうございます！

**Comment by Yfuruchin** [comment]
分岐してこの項としては概ね解決しているのでclose
