### ISSUE TITLE
各種説明に出てくる「フォーク」という言葉がエンジニア以外に伝わらない気がする

### ISSUE THREAD

**Issue by daisuke-fukuda** [codeforsapporo/covid19#91]
- [ ] バグ / Bug
- [x] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem

ここらへんの文章
「当サイトは、道内の新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するため、ICTエンジニアやデザイナーなどによって結成された「JUST道IT」が東京都公式 新型コロナウイルス対策サイトをフォークしたものです。」

## 期待する見せ方・挙動 / Expected behavior

東京都公式 新型コロナウイルス対策サイトを元に作成（フォーク）したものです

とかでしょうか。うーん、、、、

**Comment by Yfuruchin** [comment]
それ、０稿かいたわたしもおもいました。そうですよね

>当サイトは、道内の新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するため、複製・改変が許されたオープンソースライセンスで公開されている東京都公式新型コロナウイルス対策サイトのソースコード（リンク）を元に、ICTエンジニアやデザイナーなどによって結成された「JUST道IT」が開発を行いました。

とかどうでしょう？長いかな

**Comment by ymgt-design** [comment]
それでいいと思います。

**Comment by ymgt-design** [comment]
すません。ソースコードとか言っちゃうと、それもわかんない感じしてきちゃいました。

>当サイトは、道内の新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するため、複製・改変が許されたオープンソースライセンスで公開されている東京都公式新型コロナウイルス対策サイトシステムの仕組みを利用して、ICTエンジニアやデザイナーなどによって結成された「JUST道IT」が開発を行いました。

ってな感じのほうが一般的にはまだ脳内変換出来そう

**Comment by Yfuruchin** [comment]
SSG
+1

**Comment by daisuke-fukuda** [comment]
まじめに考え出すとすごい難しいですね、これ。

> 当サイトは、道内の新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために作成されました。開発は、ICTエンジニアやデザイナーなどによって結成された「JUST道IT」が行っています。
> 
> 複製・改変が許されたオープンソースライセンスで公開されている、東京都公式新型コロナウイルス対策サイト（https://stopcovid19.metro.tokyo.lg.jp/）の仕組みを利用しています。

一般の方に伝えたい情報を前半、IT関連の方向けに伝えたい情報を後半にわけてみました。

**Comment by Yfuruchin** [comment]
SSG
＋１＋１

**Comment by ymgt-design** [comment]
ソレでいきましょう。こちらでプルリクあげますね!

**Comment by daisuke-fukuda** [comment]
twitterやfbも対象にすると良さげです！

<img width="637" alt="スクリーンショット 2020-03-08 21 06 37" src="https://user-images.githubusercontent.com/32258949/76162399-c52d2600-6180-11ea-820f-16143653f7f8.png">

**Comment by ymgt-design** [comment]
FB対応完了。twitterは @Nekoya3 かな?

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/76163104-c3666100-6186-11ea-8a07-69be43ed4dd9.png)
160字制限があるため一部省略していますが、twitter更新しました！！！

**Comment by ymgt-design** [comment]
ありがとうございます!クローズします!
