### ISSUE TITLE
データの更新日時を理解しやすいように変更する

### ISSUE THREAD

**Issue by aricone** [codeforsapporo/covid19#93]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 日付表記が「2020-03-08T17:53:42.579128 更新」のようになっている場合があります

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/13171920/76161970-d9baef80-617b-11ea-9d16-6c1cade26d2c.png)

## 期待する見せ方・挙動 / Expected behavior
* 日付の表記を東京版と同じく2020/03/06 20:00 更新の形にする

**Comment by NEKOYASAN** [comment]
対応中です!
自分で立てとけばよかったです...申し訳ない...
