### ISSUE TITLE
累計値の前日比がNaN人となります

### ISSUE THREAD

**Issue by aricone** [codeforsapporo/covid19#95]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* indexページの累計値の前日比がNaNと表示されて正しくない

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/13171920/76162300-d590d100-617f-11ea-9549-c7e27980c6f6.png)

## 期待する見せ方・挙動 / Expected behavior
* 東京都版と同じく、表示されること

**Comment by daisuke-fukuda** [comment]
調べてます

**Comment by daisuke-fukuda** [comment]
TimeBarChart.vueのdisplayCumulativeRatioがNaNになっている

**Comment by daisuke-fukuda** [comment]
cummulativeとcumulativeのtypo。

本家どうなってるか見てみます。

**Comment by daisuke-fukuda** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/pull/461/files
これが取り込まれていなかったから。cherry-pickします。
