### ISSUE TITLE
「最終更新」が表示されていない

### ISSUE THREAD

**Issue by aricone** [codeforsapporo/covid19#98]
- [x] バグ / Bug
- [ ] 改善提案 / Suggestions for improvement

## 起こっている問題 / Occurred problem
* 最新更新の日時が表示されていない

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/13171920/76162436-20f7af00-6181-11ea-9fdb-58635c0706ff.png)

## 期待する見せ方・挙動 / Expected behavior
* 最新更新の時間について、何の時間を表示するか確定すること
* 最新更新が表示されるもしくは削除されること

**Comment by ymgt-design** [comment]
#41 でとりあえず直接打ち込みにしてるので、まずは本日の日付を入れます。

**Comment by Yfuruchin** [comment]
…とはいえ自動更新は実装が望ましいかも

**Comment by ymgt-design** [comment]
本来自動になってるんですが、多分「なにか」でダメになってる。

**Comment by NEKOYASAN** [comment]
自動更新対応させました！

**Comment by aricone** [comment]
可能なら
最終更新 2020/03/08
のフォーマットが可能ですといいと思いました！

**Comment by NEKOYASAN** [comment]
グラフの形式に合わせますね

**Comment by ymgt-design** [comment]
あれ、グラフって/をつかってるんでしたっけ

**Comment by ymgt-design** [comment]
というよりも、東京も/利用なんですね。なるほど。
オープンデータ系だからてっきり-つかってるんだと思いこんでました。すいません。
